== Addestrare la mente

Addestrare la mente. In effetti nella mente non c’è nulla. È in se
stessa e di per se stessa semplicemente radiosa. È serena per natura. La
ragione per cui la mente non si sente serena è perché si perde nei suoi
stessi umori. Nella mente non c’è nulla. Dimora semplicemente nel suo
stato naturale, questo è tutto. Se a volte la mente si sente serena e
altre volte no, è perché viene ingannata da questi suoi stati mentali.
La mente non addestrata manca di saggezza. È stolta. Gli stati mentali
arrivano e la ingannano, facendole provare piacere per un minuto e
sofferenza nel minuto successivo. Prima felicità, poi tristezza. Però,
lo stato naturale della mente di una persona non è la felicità o la
tristezza. L’esperienza della felicità e della tristezza non è la vera
mente, la mente in se stessa, bensì sono gli stessi stati mentali che
l’hanno ingannata. La mente si perde, portata via da questi stati
mentali senza aver alcuna idea di cosa stia avvenendo. Il risultato è
che, di conseguenza, sperimentiamo piacere e dolore perché la mente non
è ancora stata addestrata. Non è ancora molto abile. E così continuiamo
a pensare che la nostra mente stia soffrendo o che la nostra mente sia
felice, quando in verità si è solo perduta nei suoi umori.

Il punto è che questa nostra mente è davvero serena per natura. È calma
e immobile come una foglia che non agitata dal vento. Però, quando il
vento soffia, ecco che allora svolazza. Lo fa a causa del vento. La
stessa cosa avviene con la mente a causa dei suoi umori: resta
intrappolata nei pensieri. Se la mente non si perdesse in questi suoi
stati mentali, non svolazzerebbe qui e là. Se comprendesse la natura dei
pensieri, resterebbe immobile. Questo si chiama stato naturale della
mente. La ragione per cui siamo ora qui a praticare è per vedere la
mente in questo suo stato originario. Pensiamo che la mente stessa sia
contenta o serena. Però, la mente non ha in effetti creato alcun reale
piacere o dolore. Questi pensieri sono arrivati e l’hanno ingannata, ed
essa è rimasta loro prigioniera. È davvero per questo che siamo dovuti
venire qui e che dobbiamo addestrare la nostra mente affinché cresca la
saggezza in modo tale da comprendere la vera natura dei pensieri, invece
di seguirli ciecamente.

La mente è serena per natura. È solo per capire questo che ci siamo
dovuti riunire per svolgere questa difficile pratica della meditazione.
