= Che cos’è la contemplazione?

____
Questo insegnamento è tratto da una sessione di domande e risposte
intercorse tra un gruppo di discepoli di lingua inglese e il venerabile
Ajahn Chah che ebbe luogo al monastero Wat Gor Nork durante il Vassa del
1979. Sono stati necessari alcuni ritocchi nella sequenza della
conversazione per facilitare la comprensione.
____

_Domanda._ Quando insegni l’importanza della contemplazione, parli di
quando ci si siede in meditazione e si pensa ad argomenti particolari,
ad esempio alle “trentadue parti del corpo”?footnote:[“Trentadue
parti del corpo”. Un tema di meditazione il quale prevede che si
investighino le parti del corpo, quali i capelli (_kesa_), i peli
(_loma_), le unghie (_nakha_), i denti (_danta_), la pelle (_taco_) e
così via, in rapporto al loro essere non attraenti (_asubha_) e
insoddisfacenti (_dukkha_).]

_Risposta._ Se la mente è davvero serena non è necessario. Il giusto
oggetto d’investigazione diviene ovvio quando la tranquillità si è
insediata in modo opportuno. Quando la contemplazione è vera non c’è
discriminazione tra “giusto” e “sbagliato”, “buono” e “cattivo”,
non c’è nulla di tutto questo. Non è che ti siedi e pensi: « Oh, questo
è così e quell’altro è cosà », e via di seguito. È una forma grossolana
di contemplazione. Con la contemplazione meditativa non è in questione
il pensiero. Si tratta piuttosto di quel che chiamiamo “contemplazione
silenziosa”. Durante la nostra routine quotidiana prendiamo
consapevolmente in considerazione la reale natura dell’esistenza
mediante paragoni. Anche in questo caso è un genere grossolano
d’investigazione, ma conduce alla Verità.

_D._ Quando dici di contemplare il corpo e la mente, però, ci serviamo
del pensiero? Il pensiero può produrre vera visione profonda? Questa è
_vipassanā_?footnote:[_vipassanā._ Visione profonda di natura intuitiva
dei fenomeni fisici e mentali, del loro sorgere e scomparire.]

_R._ All’inizio abbiamo bisogno di lavorare usando il pensiero, ma in
seguito andremo al di là di esso. Se stiamo facendo vera contemplazione,
tutto il pensiero dualistico è cessato, ma abbiamo bisogno di iniziare
considerando le cose in modo dualistico. Alla fine tutto il pensiero e
tutte le considerazioni cessano.

_D._ Dici che ci deve essere una sufficiente tranquillità (_samādhi_)
per contemplare. Quanta tranquillità intendi?

_R._ Sufficientemente tranquilli affinché ci sia presenza mentale.

_D._ Intendi stare con il “qui e ora”, senza pensare al passato e al
futuro?

_R._ Pensare al passato e al futuro va bene, se comprendi cosa siano in
realtà queste cose, ma non devi restarci intrappolato. Trattale nello
stesso modo in cui tratteresti ogni altra cosa, ma non restarci
intrappolato. Quando vedi il pensiero solo come pensiero, questa è
saggezza. Non credere a nessun pensiero! Riconosci che tutto è solo
qualcosa che è sorto e che cesserà. Semplicemente, vedi tutto nel modo
in cui è, è quel che è, la mente è la mente, di per sé non è qualcosa o
qualcuno. Quando lo comprenderai, andrai al di là del dubbio.

_D._ Continuo a non capire. La vera contemplazione e il pensiero sono la
stessa cosa?

_R._ Utilizziamo il pensiero come strumento, ma la conoscenza che sorge
a causa di esso è al di sopra e al di là del processo del pensiero, e
conduce a non essere più ingannati dai nostri pensieri. Riconosci che
tutti i pensieri sono solo un movimento della mente, e pure che il
conoscere né nasce né muore. Da dove pensi che provenga tutto questo
movimento chiamato “mente”? Tutto quel che chiamiamo mente – tutta
l’attività – è solo la mente convenzionale. Non è affatto la mente
reale. Ciò che è reale “è” solamente, né sorge né cessa.

Però, cercare di capire queste cose solo parlandone, non funziona.
Dobbiamo prendere veramente in considerazione l’impermanenza,
l’insoddisfazione e l’impersonalità (_aniccā_, _dukkha_,
_anattā_),footnote:[Le qualità di tutti i fenomeni; impermanenza
(_anicca_), carattere insoddisfacente (_dukkha_) e non-sé (_anatta_).
Nel _Glossario_, p. FIXME:pageref, si veda Tre Caratteristiche
(_tilakkhaṇa_).] ossia dobbiamo usare il pensiero per contemplare la
natura della realtà convenzionale. Da questo lavoro nasce la saggezza e,
se si tratta di saggezza reale, tutto è completato, finito, riconosciamo
la vacuità. Benché ci possano essere pensieri, sono vuoti, non ne siamo
influenzati.

_D._ Come possiamo arrivare a questo livello della mente reale?

_R._ Lavorando con la mente che già avete, ovviamente! Vedete che tutto
quel che sorge è incerto, che non c’è nulla di stabile o di sostanziale.
Vedetelo con chiarezza e comprendete che davvero in nessun luogo c’è
qualcosa a cui aggrapparsi: è tutto vuoto. Quando vedrete le cose che
sorgono nella mente per quello che sono, non dovrete lavorare più con il
pensiero. Non avrete più alcun dubbio al riguardo.

Parlare della “mente reale” e così via, può essere solo di relativa
utilità per aiutarci a capire. Inventiamo parole allo scopo di studiare,
ma in realtà la natura è solo così com’è. Star seduti qui sul pavimento
di pietra del piano inferiore, ad esempio. Il pavimento è la base, non
si muove e non va da nessuna parte. Il piano superiore, sopra di noi, è
ciò che è sorto da essa. Il piano superiore è come tutto quello che
vediamo nella nostra mente: forma, sensazione, memoria, pensiero. In
realtà, essi non esistono nel modo in cui presumiamo che esistano. Sono
unicamente la mente convenzionale. Appena sorgono, svaniscono di nuovo,
di per sé non esistono realmente.

Nelle Scritture c’è una storia sul venerabile Sāriputta che esamina un
_bhikkhu_ prima di consentirgli di andare a svolgere le pratiche
ascetiche itineranti (__dhutaṅga__footnote:[_dhutaṅga._ Pratica ascetica
volontaria. Se ne parla più dettagliatamente nel _Glossario_,
p. FIXME:pageref.] _vaṭṭa_). Gli chiese come avrebbe risposto se gli
fosse stato chiesto: « Cosa succede al Buddha dopo la morte? » Il
_bhikkhu_ rispose: « La forma, la sensazione, la percezione, il pensiero
e la coscienza dopo essere sorti, svaniscono. » Il venerabile Sāriputta
accettò la risposta.

La pratica non è però solo questione di parole sul sorgere e sul
cessare. Dovete vederlo da voi. Quando siete seduti in meditazione,
vedete semplicemente cosa stia in realtà succedendo. Non seguite nulla.
Contemplazione non significa essere catturati dai pensieri. Il pensiero
contemplativo di chi è sul Sentiero non è uguale al pensiero del mondo.
Se non comprendete in modo giusto cosa s’intende con “contemplazione”,
più pensate più sarete confusi.

La ragione per cui sottolineiamo l’importanza di coltivare la
consapevolezza è perché abbiamo bisogno di vedere con chiarezza cosa
succede. Dobbiamo comprendere il modo in cui funziona il nostro cuore.
Quando sono presenti questa consapevolezza e questa comprensione, allora
tutto è a posto. Per quale motivo pensi che “Colui che Conosce la Via”
non agisca mai mosso dall’ira o dall’illusione? Le cause che fanno
sorgere queste cose sono assenti. Da dove potrebbero giungere? La
consapevolezza ha avvolto tutto.

_D._ La mente di cui stai parlando è chiamata “Mente Originaria”?

_R._ Che cosa vuoi dire?

_D._ È come se tu stessi dicendo che c’è qualcos’altro al di fuori del
convenzionale corpo-mente (i cinque _khandhā_).footnote:[_khandhā._
Aggregato, insieme di elementi col quale ci si identifica; le componenti
fisiche e mentali della personalità e dell’esperienza sensoriale in
generale.] C’è qualcos’altro? Come lo chiami?

_R._ Non c’è nulla e non lo chiamo affatto. Questo è tutto quel che ci
deve essere. Fatela finita con tutte queste cose. Perfino la conoscenza
non appartiene a nessuno, perciò facciamola finita, facciamola finita
con tutto! Non c’è nulla che valga la pena di volere! Tutto questo è
solo un mucchio di problemi. Quando si vede con chiarezza in questo
modo, allora tutto è finito.

_D._ Non potremmo chiamarla “Mente Originaria”?

_R._ Visto che insisti, puoi chiamarla in questo modo. Puoi chiamarla in
qualsiasi modo ti piaccia in rapporto alla realtà convenzionale. Devi
però comprenderlo bene questo punto. È davvero importante. Se non
facessimo uso della realtà convenzionale, non avremmo alcuna parola o
concetto mediante il quale prendere in considerazione la realtà
effettiva: il Dhamma. È davvero importante capirlo.

_D._ Di quale grado di tranquillità parli a questo livello? E quale
genere di consapevolezza è richiesta?

_R._ Non c’è bisogno di pensare in questo modo. Se non si avesse la
giusta dose di tranquillità, non si sarebbe affatto in grado di
affrontare questi argomenti. C’è bisogno di sufficiente stabilità
mentale e di concentrazione sia per sapere quel che sta succedendo sia
perché sorgano lucidità e comprensione.

Se fai domande di questo genere significa che stai ancora dubitando. C’è
bisogno di una tranquillità mentale sufficiente per non restare più
intrappolati nei dubbi su quello che stiamo facendo. Se avessi
praticato, queste cose le comprenderesti. Più vai avanti con questo tipo
di domande, più rendi le cose confuse. Va bene se aiuta la
contemplazione, ma parlare non ti mostrerà il modo in cui sono davvero
le cose. Questo Dhamma non si comprende perché qualcun altro te ne
parla, devi vederlo da te, _paccattaṃ_.footnote:[_paccattaṃ._ Da
sperimentare individualmente e personalmente (_veditabba_) da parte dei
saggi (_viññūhi_).] Se hai la capacità di comprendere di cosa abbiamo
parlato, allora diciamo che il tuo dovere di fare qualcosa è finito, e
questo significa che non fai nulla. Se c’è ancora qualcosa da fare,
allora è tuo dovere farlo.

Deponi semplicemente qualsiasi cosa, e sappi che è questo che stai
facendo. Non c’è sempre bisogno di starsi a controllare, preoccupandosi
di cose del tipo “quanto _samādhi_” … sarà sempre la giusta quantità.
Qualsiasi cosa sorga nella tua pratica, lasciala andare. Sappi che tutto
è incerto, impermanente. Ricordatelo! È tutto incerto. Falla finita con
tutto. Questa è la Via che ti porterà alla fonte, alla tua Mente
Originaria.
