== Conoscere il mondo

Tutte le cose manifestano la verità così come sono. Però, noi abbiamo
pregiudizi e preferenze su come vorremmo che fossero. _Lokavidū_
significa conoscere il mondo con chiarezza. Il mondo è questi fenomeni
(_sabhāva_)footnote:[_sabhāva._ Letteralmente, “natura propria”.
Principio o condizione della natura, qualcosa che è come veramente è.]
che in esso dimorano così come sono. Per dirla semplicemente, il mondo è
_arom_.footnote:[_arom_, in thailandese (อารมณ์). Tutte le condizioni o
stati, oppure oggetti della mente, felici o infelici, interni o
esterni.] Si può dire così, facilmente. Il mondo è _arom_. “Mondo” è
un’espressione piuttosto ampia. Gli _arom_ sono il mondo è molto più
semplice. Il mondo è _arom_. Essere illusi dal mondo significa essere
illusi da _arom_. Essere illusi da _arom_ significa essere illusi dal
mondo. _Lokavidū_, conoscere il mondo con chiarezza: come che sia, il
mondo è ciò che dovremmo conoscere. Esso esiste in accordo con le sue
condizioni. Dovremmo avere una totale e attuale consapevolezza del
mondo.

Pure i _saṅkhāra_ li dovremmo conoscere per quello che sono, e
sviluppare la saggezza che conosce i _saṅkhāra_. È la verità che
dovremmo conoscere, quale che sia la verità dei _saṅkhāra_, quale che
sia il modo in cui essi veramente sono. Questa è chiamata saggezza che
accetta e conosce senza ostacoli. Abbiamo bisogno di sviluppare una
mente che abbia nello stesso tempo sia la tranquillità sia la saggezza
di tenere le cose sotto controllo. Stiamo parlando di _sīla_, _samādhi_
e _paññā_, e delle meditazioni _samatha_ e _vipassanā_. In realtà, però,
sono tutte la stessa cosa. Sono la stessa cosa, ma ci confondiamo perché
le suddividiamo in differenti categorie. Uso spesso una semplice
analogia – le cose possono essere paragonate – per facilitare la
contemplazione e la comprensione di questo argomento.

Quello che prima è un piccolo mango, in seguito diventa un mango grande
e maturo. Il piccolo mango è lo stesso frutto di quello grande? È lo
stesso mango fin dal tempo in cui era solo un germoglio in fiore
sull’albero. Quando cresce è solo soggetto a un cambiamento e diventa
prima un mango piccolo e poi diventa sempre più grande, quasi maturo e
infine maturo. Per gli aspetti della pratica di cui stiamo parlando è la
stessa cosa. _Sīla_ significa semplicemente rinunciare alle cattive
azioni. Chi è privo di _sīla_ si trova in una condizione di
incandescenza. Rinunciare alle cattive azioni e ai modi malvagi di
essere reca serenità e protezione contro pericoli e cattive conseguenze.
Il beneficio che proviene da questa libertà dalle cattive conseguenze è
una mente tranquilla, ossia il _samādhi_. Quando la mente è in
_samādhi_, pulita e pura, vede molte cose. È come l’acqua quando è
ferma, indisturbata. In essa potete vedere il vostro volto. Potete
vedervi riflesse anche cose più lontane. Anche i tetti di quegli edifici
laggiù. Se sui tetti si posa un uccello, riuscite a vederlo. Tutti
questi fattori sono davvero una sola cosa, proprio come quel mango. Il
piccolo frutto è quello stesso, unico mango. Il frutto che cresce è lo
stesso mango. Il frutto maturo è lo stesso mango. Da verde a giallo, è
lo stesso mango; è soggetto al cambiamento, e questa è la ragione per
cui vediamo delle differenze.

Avere questo semplice tipo di conoscenza può farci sentire a nostro
agio. I dubbi diminuiranno. Se invece facciamo affidamento su testi e
spiegazioni dettagliate, è probabile che finiremo per sentirci confusi.
È per questo che dobbiamo osservare la nostra mente.
« _Bhikkhu_!footnote:[_bhikkhu_. Un monaco buddhista.] Dovreste
osservare la vostra mente. Coloro che vigilano sulla propria mente
sfuggiranno ai lacci di _Māra_. » Sia a _Māra_ sia ai suoi lacci. Questo
dipende dalla vostra investigazione.

Il mio modo di praticare era un po’ strano. Dopo l’ordinazione
monastica, quando iniziai a praticare avevo molti dubbi e problemi. Però
mi piaceva non chiedere a nessuno. Non feci molte domande nemmeno ad
Ajahn Mun,footnote:[Ajahn Mun. Probabilmente fu il più rispettato e
influente maestro di meditazione del secolo scorso in Thailandia. Sotto
la sua guida l’ascetica Tradizione Thailandese della Foresta (_dhutaṅga
kammaṭṭhāna_) divenne veramente importante nella rinascita della pratica
della meditazione buddhista. La maggioranza dei grandi maestri di
meditazione della Thailandia di recente deceduti o ancora viventi sono
stati diretti discepoli del venerabile Ajahn Mun oppure furono
profondamente influenzati dal suo insegnamento. Egli morì nel novembre
del 1949. Nella traduzione si è scelto di lasciare “Mun”, come di
solito si rinviene nei testi inglesi. Si avverte il lettore italiano
che, però, l’esatta pronuncia thailandese è “Màn”.] quando lo
incontrai. Volevo farlo, ma non lo feci. Mi sedetti e ascoltai il suo
insegnamento. Avevo delle domande, ma non volli farne. Fare domande a
qualcun altro è come chiedere in prestito un coltello per tagliare
qualcosa. Non avremo mai il nostro coltello. Questa era la mia
percezione. Per questa ragione non facevo molte domande agli altri. Se
restavo un anno o due con un insegnante, ascoltavo i suoi discorsi e
cercavo di lavorare alle cose per conto mio. Avrei cercato le mie
risposte. Ero diverso dagli altri discepoli, ma ero in grado di
sviluppare la saggezza. Questo modo di essere mi fece diventare
intelligente e pieno di risorse. Non divenni distratto, contemplai anzi
le cose finché non fui in grado di capire da me, accrescendo la mia
comprensione e rimuovendo i miei dubbi.

Vi consiglio di non lasciarvi intrappolare da dubbi e problemi.
Lasciateli andare e contemplate direttamente qualsiasi cosa vi capiti di
sperimentare. Qualsiasi piacere o dolore fisico sperimentiate, non
trasformatelo in una gran cosa. Quando sedete in meditazione e iniziate
a sentirvi stanchi o a disagio, modificate la vostra posizione.
Sopportate più che potete, poi muovetevi. Non esagerate. Sviluppate
molta consapevolezza, questa è la cosa importante. Fate la meditazione
camminata e seduta più che potete. L’obbiettivo è sviluppare la
consapevolezza più che potete, conoscendo pienamente le cose. È
sufficiente.

Per favore, utilizzate queste mie parole per la contemplazione.
Qualsiasi forma di pratica stiate svolgendo, quando sorgono degli
oggetti mentali, sia interni sia esterni, questi sono detti _arom_.
Colui che è consapevole dell’_arom_ è chiamato … bene, comunque vogliate
chiamarlo va bene. Potete chiamarlo “mente”. L’_arom_ è una cosa, e
colui che conosce l’_arom_ è un’altra. È come l’occhio e gli oggetti che
esso vede. L’occhio non è gli oggetti, ma gli oggetti non sono l’occhio.
L’orecchio sente i suoni, ma l’orecchio non è il suono, e il suono non è
l’orecchio. Quando c’è contatto tra i due, è allora che le cose
avvengono. Tutti gli stati mentali, felici o infelici, sono detti
_arom_. Qualsiasi cosa possano essere, non preoccupatevi, dovremmo
costantemente rammentare a noi stessi che “questo non è certo”.

La gente non tiene in grande considerazione che “questo non è certo”.
Anche da solo, è un elemento essenziale che reca saggezza. È davvero
importante. Per porre fine al nostro continuo andirivieni e cercare
riposo, abbiamo solo bisogno di dire a noi stessi: « Questo non è
certo. » A volte possiamo essere affranti per una cosa fino al punto di
piangere; si tratta comunque di una cosa non certa. Quando ci
raggiungono stati d’animo di desiderio o di avversione, dovremmo
unicamente ricordare a noi stessi solo questa cosa. In piedi,
camminando, seduti o distesi, qualsiasi cosa appaia è incerta. Riuscite
a farlo? Continuate senza tener conto di quel che succede. Provateci.
Non c’è bisogno di molto, già solo questo funzionerà. È una cosa che
reca saggezza.

Il modo in cui io pratico la meditazione non è molto complicato: è tutto
qui. Tutto si riduce a questo: « È incerto. » Si riunisce tutto in
questo punto. Non prestate attenzione alle varie manifestazioni
dell’esperienza mentale. Quando sedete, possono apparire, essere visti o
conosciuti vari generi di cose, possono essere sperimentati differenti
stati mentali. Non interessatevene e non fatevi coinvolgere. Dovete solo
ricordare a voi stessi che sono cose incerte. È sufficiente. È facile da
fare. È semplice. Poi potete fermarvi. La conoscenza arriverà, ma non
ingigantitela troppo né attaccatevi a essa. La vera investigazione,
investigare in modo corretto non coinvolge il pensiero. Appena qualcosa
entra in contatto con l’occhio, l’orecchio, il naso, la lingua o il
corpo, tutto succede immediatamente da sé. Non dovete scegliere che cosa
osservare: le cose si presentano da sole e l’investigazione avviene da
sé. Noi parliamo di _vitakka_, di “pensiero iniziale”. Significa
suscitare qualcosa. _Vicāra_ è il “pensiero discorsivo”. È
l’investigazione, vedere i piani dell’esistenza (_bhūmi_) che appaiono.

In ultima analisi, la Via del Buddha fiorisce mediante l’impermanenza. È
sempre attuale e pertinente, sia ai tempi del Buddha sia in altri
periodi del passato, nel presente o nel futuro. È sempre l’impermanenza
a dominare. È una cosa su cui dovreste meditare. Le parole giuste e vere
del saggio non trascureranno di menzionare l’impermanenza. Questa è la
verità. Se non viene menzionata l’impermanenza, non sono le parole di un
saggio. Non sono parole del Buddha o degli _ariya_;footnote:[_ariya._
Nobile; chi ha ottenuto la visione trascendente in uno dei quattro stadi
dell’Illuminazione.] sono discorsi che non accettano la Verità
dell’esistenza.

Tutto ha bisogno di una via di sfogo. Contemplazione non significa
tenersi stretti le cose o attaccarsi ad esse. È un modo per liberarsi.
Una mente che non può liberarsi dei fenomeni è in uno stato
d’intossicazione. Nella pratica, è importante non essere intossicati.
Quando la pratica sembra andare davvero bene, non intossicatevi con quel
bene. Se ve ne intossicate, diverrà qualcosa di nocivo, e la vostra
pratica non sarà più corretta. Facciamo del nostro meglio, ma è
importante non ubriacarsi dei nostri sforzi, altrimenti non siamo in
armonia con il Dhamma. Questo è il consiglio del Buddha. Perfino il bene
è qualcosa con cui non intossicarsi. Siatene coscienti, quando succede.

Una diga necessita di una chiusa che consenta all’acqua di defluire.
Nella pratica è la stessa cosa per noi. Usare la forza di volontà per
costringerci e per controllare la mente è una cosa che possiamo fare
ogni tanto, ma non ubriacatevene. Noi vogliamo insegnare alla mente in
modo da farla diventare consapevole, non controllarla semplicemente.
Sforzarvi troppo vi farà diventare matti. Quel che è fondamentale è
continuare a incrementare la consapevolezza e la sensibilità. Il nostro
Sentiero è così. Si possono fare molti paragoni. Potremmo parlare dei
lavori di costruzione e ricondurli al modo di addestrare la mente.

Possiamo ottenere molti benefici dalla pratica di meditazione, dal
sorvegliare la mente. Questo è il compito primario, il più importante.
Gli insegnamenti che potete studiare dalle Scritture e dai Commentari
sono veri e preziosi, ma secondari. È gente che spiega la Verità. Però,
c’è una Verità effettiva che supera le parole. A volte le esposizioni
che da Essa derivano non sono omogenee, oppure non sono molto
accessibili, e con il passare del tempo possono indurre in confusione.
Però, la Verità effettiva sulla quale si basano resta la stessa, non è
influenzata da quel che gli altri dicono o fanno. È l’originale,
naturale stato delle cose che non muta né si deteriora. Le spiegazioni
ideate dalla gente sono secondarie o terziarie, stanno uno o due passi
più in là e sono soggette a deteriorarsi per quanto possano essere di
beneficio e per quanto fiorenti possano essere per un po’ di
tempo.footnote:[In quanto sono ancora nel reame dei concetti.]

È come quando con l’aumento della popolazione continuano ad aumentare
pure i problemi. È piuttosto naturale. Più gente c’è, più numerosi
saranno i problemi da affrontare. I governanti e gli insegnanti
cercheranno di mostrarci il modo giusto di vivere, di fare del bene e di
risolvere i problemi. Può essere plausibile e necessario, ma non è la
stessa cosa rispetto alla realtà su cui quelle buone idee poggiano. Il
vero Dhamma, che è l’essenza di tutto il bene, non ha modo di decadere o
di deteriorarsi perché è immutabile. È la fonte, il _saccadhamma_, che
esiste così com’è. Tutti coloro che seguono la Via del Buddha e
praticano il Dhamma devono sforzarsi di comprenderlo. Potranno trovare
vari mezzi per esporlo. Col passare del tempo le spiegazioni perdono la
loro incisività, ma la fonte rimane la stessa. È per questo che il
Buddha insegnò a focalizzare l’attenzione e a investigare. Praticanti in
cerca della Verità, non siate attaccati ai vostri modi di vedere e alla
vostra conoscenza. Non siate attaccati alla conoscenza degli altri. Non
siate attaccati alla conoscenza di nessuno. Sviluppate invece una
conoscenza particolare: consentite al _saccadhamma_ di rivelarsi
pienamente. Addestrando la mente, investigando il _saccadhamma_, le
nostre menti si trovano dove è possibile vederlo. Quando dubitiamo di
qualcosa, dovremmo prestare attenzione ai nostri pensieri e alle nostre
sensazioni, ai nostri processi mentali. Questo è ciò che dovremmo
conoscere. Il resto è superficiale.

Praticando il Dhamma, incontreremo numerosi tipi di esperienza, come la
paura. Su cosa faremo affidamento? Quando la mente è avvolta dalla
paura, non riesce a trovare nulla su cui fare affidamento. Si tratta di
una cosa che ho vissuto. La mente illusa resta bloccata nella paura, è
incapace di trovare un luogo sicuro. Come si può risolvere la questione?
Può essere risolta esattamente nel posto in cui essa si pone. Ovunque
essa sorga, proprio quello è il posto in cui cessa. Ovunque la mente
abbia paura, proprio là può porre fine alla paura. Diciamolo
semplicemente: quando la mente è completamente colma di paura, non può
andare da nessun’altra parte, e può fermarsi proprio lì. Il posto dove
non c’è la paura è lì, dove sta la paura. Ad esempio, quali che siano
gli stati mentali ai quali la mente è sottoposta, non importa se essa
durante la meditazione fa esperienza di _nimitta_,footnote:[_nimitta._
Segno mentale, immagine, o visione che può sorgere durante la
meditazione.] di visioni o di conoscenza: ci è stato insegnato a
focalizzare la consapevolezza sulla mente nel presente. Questo è il
criterio. Non andate a caccia di fenomeni esteriori. Tutte le cose che
contempliamo si concludono alla fonte, dove sorgono. Lì stanno le cause.
Questo è importante. La paura è un buon esempio, perché è facile da
vedere. Se ci consentiamo di sperimentarla fino al punto che non vi è
altro luogo in cui andare, allora non avremo più paura, perché essa si
esaurirà. Perde il suo potere, e per questo non abbiamo più paura. Non
provare più paura significa che la paura è diventata vuota. Accettiamo
qualsiasi cosa si presenti sul nostro cammino, e nulla su di noi ha più
potere.

Su questo il Buddha voleva che riponessimo la nostra fiducia, non voleva
che fossimo attaccati ai nostri modi di vedere o che fossimo attaccati
ai modi di vedere degli altri. È davvero importante. Stiamo mirando alla
conoscenza che proviene dalla realizzazione della Verità, e per questo
non vogliamo restare bloccati nell’attaccamento alle opinioni e ai modi
di vedere sia nostri sia altrui. Quando però abbiamo delle nostre idee o
entriamo in contatto con quelle degli altri, osservarle quando entrano
in contatto con la nostra mente può essere illuminante. La conoscenza
può nascere proprio nelle cose che abbiamo e di cui facciamo esperienza.

Quando osserviamo la mente e coltiviamo la meditazione, ci possono
essere numerosi aspetti di errata comprensione o fraintendimenti. Alcuni
mettono a fuoco l’attenzione sugli stati mentali e vogliono analizzarli
troppo, e perciò la loro mente è sempre attiva. Oppure esaminiamo i
cinque _khandhā_, o entriamo in ulteriori dettagli con le “trentadue
parti del corpo”.footnote:[“Trentadue parti del corpo”. Un tema di
meditazione il quale prevede che si investighino le parti del corpo,
quali i capelli (_kesa_), i peli (_loma_), le unghie (_nakha_), i denti
(_danta_), la pelle (_taco_) e così via, in rapporto al loro essere non
attraenti (_asubha_) e insoddisfacenti (_dukkha_).] Le classificazioni
insegnate per la contemplazione sono numerose. Così, riflettiamo e
analizziamo. Se osservare i cinque _khandhā_ non sembra condurci ad
alcuna conclusione, continuando sempre ad analizzare e investigare
potremmo allora avvalerci delle “trentadue parti del corpo”. Però,
secondo me il nostro atteggiamento nei riguardi di questi cinque
_khandhā_, di questi aggregati che vediamo proprio qui, dovrebbe essere
un atteggiamento di stanchezza e disincanto, perché essi non seguono i
nostri desideri. Penso che questo sia probabilmente abbastanza. Se
sopravvivono, non dovremmo essere troppo contenti, al punto di
dimenticarci di noi stessi. Se si disgregano, non dovremmo abbatterci
troppo. Rendersi conto di questo dovrebbe essere sufficiente. Non è
necessario separare la pelle dalla carne e dalle ossa.

È una cosa di cui ho parlato spesso. Alcuni devono analizzare le cose in
questo modo, anche se stanno guardando un albero. Coloro che studiano
vogliono sapere cosa siano i meriti e i demeriti, che forma abbiano, a
cosa somiglino. Io spiego loro che queste cose sono prive di forma. Il
merito consiste nell’aver retta comprensione, retto comportamento. Però,
vogliono conoscere tutto nei minimi dettagli. Per questo ho usato
l’esempio dell’albero. Gli studiosi guarderanno un albero e vorranno
sapere tutto sulle parti che lo compongono. Bene, un albero ha radici,
ha foglie. Vive grazie alle radici. Gli studiosi vogliono sapere di più.
Quante radici ha? Radici grandi, radici piccole, rami, foglie, vogliono
sapere tutti i dettagli con i relativi numeri. Così penseranno di avere
una chiara conoscenza dell’albero. Però, il Buddha disse che chi mira a
una conoscenza di questo genere è in realtà piuttosto stupido. Si tratta
di cose che non è necessario conoscere. Sapere solo che ci sono foglie e
radici è sufficiente. Volete contare tutte le foglie di un albero? Se
osservate una foglia, dovreste essere in grado di avere un’immagine
complessiva. Per la gente è la stessa cosa. Se conosciamo noi stessi,
comprendiamo tutte le persone dell’universo senza che ci sia bisogno di
andare a osservarle una per una. Il Buddha voleva che osservassimo noi
stessi. Come siamo noi, così sono gli altri. Siamo tutti
_sāmaññalakkhaṇa_,footnote:[_sāmaññalakkhaṇa._ Indica che tutto è
identico nei termini delle Tre Caratteristiche: impermanenza (_aniccā_),
carattere insoddisfacente (_dukkha_) e non-sé (_anattā_).] abbiamo tutti
le stesse caratteristiche. Tutti i _saṅkhāra_ sono così.

Così, noi pratichiamo il _samādhi_ per essere in grado di rinunciare
alle contaminazioni, per far nascere la conoscenza e la visione profonda
e per lasciar andare i cinque _khandhā_. Alcuni parlano di _samatha_. A
volte parlano di _vipassanā_. Penso che questo possa indurre confusioni.
Chi pratica il _samādhi_ loderà il _samādhi_. Però, esso serve solo a
rendere la mente tranquilla, per poter conoscere le cose di cui abbiamo
parlato. Ci saranno poi altri che dicono: « Non ho molto bisogno di
praticare il _samādhi_. In futuro, un giorno questo piatto si romperà.
Non va già bene così? Succederà, vero? Non sono molto abile con il
_samādhi_, però già so che prima o poi quel piatto si romperà. Certo, io
me ne prendo cura perché temo che si romperà, ma so che questo è il suo
futuro e quando si romperà, non soffrirò. Vero che è giusto questo mio
modo di pensare? Non ho bisogno di praticare molto _samādhi_, perché già
ho questa comprensione. Si pratica il _samādhi_ solo per sviluppare
questa comprensione. Dopo aver addestrato la mente mediante la
meditazione seduta si perviene a questo modo di vedere. Non la pratico
molto, ma già sono certo che questo è il modo di essere dei fenomeni. »
Questa è una domanda per noi praticanti.

Ci sono molti gruppi di insegnanti che propagandano i loro vari metodi
di meditazione. Questo induce confusione. Però, la cosa davvero
importante è essere in grado di riconoscere la Verità, di vedere le cose
così come veramente sono, ed essere liberi dal dubbio. Secondo me, una
volta che abbiamo una corretta comprensione, la mente è in nostro
potere. Quale potere? Il potere sta nel sapere che tutto è impermanente,
_aniccā_. Tutto si ferma lì quando vediamo con chiarezza, e ciò diventa
per noi la causa per lasciar andare. Allora lasciamo che le cose siano
secondo la loro natura. Se non succede nulla dimoriamo nell’equanimità.
Se qualcosa affiora, contempliamo: quel che è successo ci causa
sofferenza? Ci aggrappiamo con attaccamento tenace? Lì c’è qualcosa?
Questo è ciò che supporta e sostiene la nostra pratica. Se ognuno di noi
pratica e arriva a questo punto, penso che si raggiungerà la vera pace.
Solo questo è quel che conta, che si stia praticando la meditazione di
_vipassanā_ o quella di _samatha_. Di questi tempi, però, mi sembra che
quando i buddhisti parlano di queste cose secondo le tradizionali
spiegazioni, tutto diventa vago e confuso. E tutto rimane com’è. Per
questo ritengo che sia meglio andare alla fonte, osservare il modo in
cui le cose si originano nella mente. Non c’è poi molto da fare.

Nascere, invecchiare, ammalarsi e morire: si fa in fretta a dirlo, ma è
una verità universale. Comprendetelo con chiarezza e accettate questi
dati di fatto. Se li comprendete e accettate, sarete in grado di lasciar
andare. Guadagno, posizione sociale, lode e felicità con i loro opposti:
potrete lasciarli andare, perché li riconoscerete per quello che sono.
Se raggiungiamo questo luogo, quello del “riconoscimento della
Verità”, saremo persone non complicate, ci accontenteremo di cibo e di
dimore semplici, e saremo poco esigenti a riguardo degli altri generi di
prima necessità. Il nostro modo di fare sarà affabile e poco
pretenzioso. Privi di difficoltà e di problemi, vivremo a nostro agio.
Chi medita e realizza una mente tranquilla sarà così.

Ora stiamo cercando di praticare alla maniera del Buddha e dei suoi
discepoli. Quegli esseri avevano raggiunto il Risveglio, però
continuarono a praticare per tutta la vita. Agivano a beneficio di se
stessi e degli altri, e perfino quando ebbero ottenuto tutto quel che
era possibile ottenere continuarono a sostenere la pratica, alla ricerca
del benessere loro e altrui. Penso che dovrebbero servire come modello
per la nostra pratica. Questo significa non diventare compiacenti. Una
cosa era profondamente connaturata in loro: mai allentare l’impegno.
L’impegno era nel loro modo di essere, una loro naturale abitudine. Così
è il carattere dei saggi, dei veri praticanti. Lo si può paragonare alla
gente ricca e a quella povera. I ricchi sono particolarmente laboriosi,
molto più dei poveri. E meno sforzi i poveri fanno, ancora minori sono
le loro possibilità di diventare ricchi. I ricchi sanno e hanno
esperienza di molte cose, e così hanno l’abitudine di essere diligenti
in tutto quel che fanno.footnote:[Ovviamente si fa riferimento a una
società contadina, nella quale la ricchezza proveniva dal lavoro e
dall’abilità di gestire i pochi mezzi a disposizione.]

Se vogliamo prenderci una pausa o riposarci un po’, troveremo riposo
nella stessa pratica. Una volta che abbiamo praticato per giungere alla
meta, conosciamo la meta e siamo la meta, e allora siamo attivi, non c’è
modo che s’incorra in perdite o che ci venga fatto del male. Quando
siamo seduti immobili, non è possibile che ci venga fatto del male. In
qualsiasi situazione, nulla ci colpisce. La pratica è maturata
completamente e abbiamo raggiunto la destinazione. Forse oggi non
abbiamo la possibilità di sederci e di praticare il _samādhi_, però ci
sentiamo bene. _Samādhi_ non significa sedersi solamente. Il _samādhi_
può esserci in ogni postura. Se stiamo davvero praticando in tutte le
posture, proveremo diletto nel _samādhi_. Non ci sarà nulla che possa
interferire. Non si pronunceranno parole di questo genere: « La mia
mente non è limpida, e perciò non posso praticare. » Non avremo idee di
questo tipo. Non ci sentiremo mai così. La nostra pratica è ben
sviluppata e completa: così dovrebbe essere. Quando siamo liberi da
dubbi e perplessità, ci fermiamo lì e contempliamo.

Convinzioni personali, dubbio e scetticismo, attaccamento superstizioso
a riti e rituali: dentro queste cose si può guardare. Il primo passo è
liberarsene. La mente ha bisogno di liberarsi di qualsiasi genere di
conoscenza che si possa conseguire. A cosa somigliano? In che misura li
abbiamo ancora? Siamo gli unici che possono saperlo; dobbiamo saperlo da
noi. Chi meglio di noi può saperlo? Se siamo bloccati nell’attaccamento
a convinzioni personali, dubbi, se c’è superstizione o dubbio, oppure se
stiamo andando a tentoni, allora lì c’è ancora il concetto del sé. Però,
adesso riusciamo solo a pensare che se non c’è alcun sé, chi è allora
che vuole praticare?

Tutte queste cose vanno di pari passo. Se perveniamo a conoscerle per
mezzo della pratica e poniamo fine a esse, viviamo in modo normale.
Proprio come il Buddha e gli _ariya_. Vissero proprio come gli esseri
mondani (_puthujjana_).footnote:[_puthujjana._ Una persona comune,
ordinaria, non illuminata; un essere “mondano” che non ha ancora
realizzato alcuna Illuminazione.] Usarono lo stesso linguaggio degli
esseri mondani. La loro vita quotidiana non era molto diversa. Si
avvalsero per larga parte delle stesse convenzioni. Ciò in cui erano
diversi risiedeva nel fatto che nelle loro menti la sofferenza non si
generava. Non avevano sofferenza. Questo è il punto cruciale: andarono
al di là della sofferenza, estinsero la sofferenza. Nibbāna significa
“estinzione”. Estinzione della sofferenza, estinzione del bollore e
del tormento, estinzione del dubbio e dell’ansia.

Non c’è bisogno di nutrire dubbi sulla pratica. Tutte le volte che si
dubita di qualcosa, non dubitate del dubbio, guardatelo direttamente e
frantumatelo in questo modo. Inizialmente ci addestriamo per pacificare
la mente. Può essere difficile. Dovete trovare una meditazione che si
adatti al vostro temperamento. Questo renderà più facile ottenere la
tranquillità. In verità, però, il Buddha voleva che rientrassimo in noi
stessi, che ci assumessimo la responsabilità di guardare noi stessi.

La collera è rovente. Il piacere, l’estrema indulgenza, è troppo freddo.
L’estremo del tormentarsi da soli è rovente. Non vogliamo né il caldo né
il freddo. Vogliamo conoscere il caldo e il freddo. Conoscere tutte le
cose che appaiono. Ci causano sofferenza? Creiamo attaccamenti?
L’insegnamento che la nascita è sofferenza non significa solo morire in
questa vita e rinascere nella prossima. Così si va troppo lontano. La
sofferenza della nascita avviene proprio ora. Si dice che il divenire è
la causa della nascita. Cos’è il “divenire”? Tutto ciò a cui ci
attacchiamo e attribuiamo importanza è divenire. Tutte le volte che
vediamo qualcosa come sé, come altro da sé o come appartenente a noi,
senza sapere con saggio discernimento che si tratta solo d’una
convenzione, tutto questo è divenire. Ogni volta che ci attacchiamo a
qualcosa come “noi” o “nostro”, e poi quel qualcosa è sottoposto al
cambiamento, la mente ne è scossa. È scossa da una reazione positiva o
negativa. Quella sensazione del sé che sperimenta felicità o infelicità
è nascita. La nascita reca in sé sofferenza. Invecchiare è sofferenza,
ammalarsi è sofferenza, morire è sofferenza.

Proprio in questo momento, siamo soggetti al divenire? Siamo consapevoli
di questo divenire? Prendiamo come esempio gli alberi nel monastero.
L’abate del monastero può nascere come verme in ogni albero del
monastero se non ha consapevolezza di sé, se davvero sente che è il
“suo” monastero. Questo aggrapparsi al “mio” monastero con i
“miei” alberi è il verme che lo lega lì. Se ci sono migliaia di
alberi, diventerà mille vermi. Questo è divenire. Quando gli alberi
vengono tagliati o sono in qualche modo danneggiati, i vermi ne sono
affetti. La mente è scossa e in questa ansia si nasce. C’è allora la
sofferenza della nascita, la sofferenza dell’invecchiamento e così via.
Siete consapevoli del modo in cui tutto questo avviene?

Bene, gli oggetti nelle nostre case o i nostri orti sono cose ancora un
po’ lontane. Osserviamo direttamente noi stessi, che stiamo qui, seduti.
Siamo composti di cinque aggregati e di quattro elementi. Questi
_saṅkhāra_ sono designati come sé. Vedete questi _saṅkhāra_, queste
supposizioni, per come sono veramente? Se non li vedete in verità,
allora c’è il divenire, il rallegrarsi o il rattristarsi a proposito dei
cinque _khandhā_, ed ecco che nasciamo con tutte le sofferenze che ne
derivano. Questa rinascita avviene proprio ora, nel presente. Questo
bicchiere adesso non è rotto, e ne siamo felici. Se ora però si rompe,
proprio ora ce ne rattristiamo. È così che succede, si è turbati o
felici senza alcuna saggezza che controlli la situazione. Si va
solamente incontro alla rovina. Non c’è bisogno di guardare molto
lontano per capirlo. Quando mettete a fuoco la vostra attenzione qui,
potete sapere se c’è o no il divenire. Quando sta succedendo, ne siete
consapevoli? Siete consapevoli delle convenzioni e delle supposizioni?
Le comprendete? La questione fondamentale è l’attaccamento,
l’aggrapparsi, se davvero crediamo o meno alle designazioni di “io” e
“mio”. Questo attaccamento è il verme, ed è questo che causa la
nascita.

Dov’è questo attaccamento? Aggrapparsi alla forma, alla sensazione, alla
percezione, ai pensieri e alla coscienza, ci attacchiamo alla felicità e
all’infelicità, ci offuschiamo e nasciamo. Ciò avviene quando vi è il
contatto sensoriale. Gli occhi vedono le forme, e questo succede nel
presente. Questo il Buddha voleva che guardassimo, riconoscere il
divenire e la nascita che avvengono per mezzo dei nostri sensi. Se
conosciamo i sensi interni e gli oggetti esterni, possiamo lasciar
andare, interiormente ed esteriormente. Lo si può vedere nel presente.
Non si tratta di una cosa che avviene quando si muore in questa vita. È
l’occhio che vede le forme proprio ora, l’orecchio che ascolta i suoni
proprio ora, il naso che sente gli odori proprio ora, la lingua che
prova i sapori proprio ora. State nascendo con essi? Siate consapevoli e
riconoscete la nascita appena si presenta. Così va meglio. Per farlo
bisogna avere la saggezza di impiegare costantemente la consapevolezza e
la chiara comprensione. Allora potete essere consapevoli di voi stessi e
sapere quando siete soggetti a divenire e nascita. Non avrete bisogno di
chiedere a un indovino.

Nella regione centrale della Thailandia ho un amico di Dhamma. Ai vecchi
tempi praticavamo insieme, ma molti anni fa prendemmo strade diverse. Di
recente l’ho rivisto. Pratica i fondamenti della consapevolezza, recita
i _sutta_ e offre insegnamenti su tutto questo. Però non ha ancora
risolto i suoi dubbi. Si è prostrato e mi ha detto: « Oh, _ajahn_, sono
così felice di vederti! » Gli ho chiesto perché. Mi ha detto di essersi
recato presso un santuario ove la gente va per pratiche divinatorie.
Toccò la statua del Buddha e disse: « Se ho già conseguito la purezza,
che io possa essere in grado di sollevare questa statua. » E poi fu in
grado di farlo. Ciò lo rese molto felice. Solo questa piccola cosa,
priva di qualsiasi fondamento reale, significò moltissimo per lui e gli
fece pensare di essere puro. Perciò, fece scolpire su una pietra queste
parole: « Ho sollevato la statua del Buddha ed ho perciò raggiunto la
purezza. »

I praticanti di Dhamma non dovrebbero essere così. Non vedeva affatto se
stesso. Stava solamente guardando all’esterno e vedeva oggetti esteriori
fatti di pietra e cemento. Non vedeva le intenzioni e i movimenti della
sua mente nel momento presente. Se è qui che la nostra meditazione
guarda, non avremo dubbi. Secondo me, la nostra pratica può anche essere
buona, ma non c’è nessuno che possa garantire per noi. Come questa sala,
all’interno della quale sediamo. Fu costruita da uno che aveva la
licenza elementare. Ha fatto un gran bel lavoro, anche se non è famoso.
Non poté offrire garanzie e attestati, mostrare titoli di studio al pari
di un architetto esperto e che ha concluso tutti gli studi, ma ha fatto
comunque le cose per bene. Il _saccadhamma_ è così. Anche se non abbiamo
studiato molto e non conosciamo spiegazioni dettagliate, riusciamo a
riconoscere la sofferenza, riusciamo a riconoscere e a lasciar andare
quel che conduce alla sofferenza. Non abbiamo bisogno di investigare le
spiegazioni né qualsiasi altra cosa. Osserviamo solo le nostre menti,
osserviamo queste cose.

Non fate diventare confusa la vostra pratica. Non createvi un sacco di
dubbi. Quando avete un dubbio, controllatelo vedendolo unicamente per
quello che è, e lasciate andare. Davvero, non c’è nulla. Creiamo la
sensazione che ci sia qualcosa, ma in realtà non c’è nulla: c’è
_anattā_. La nostra mente dubbiosa pensa che invece ci sia qualcosa, ed
ecco che c’è _attā_. Allora la meditazione diventa difficile perché
pensiamo di dover ottenere o diventare qualcosa. State praticando la
meditazione per ottenere o per essere qualcosa? È questa la via giusta?
Solo _taṇhā_ è coinvolta nell’ottenere e nel divenire. Praticando in
questo modo, non si può intravedere la fine. Stiamo parlando di
cessazione, di estinzione. Stiamo parlando dell’estinzione di tutto,
della cessazione mediante la conoscenza, non di uno stato di
indifferente ignoranza. Se riusciamo a praticare in questo modo, avendo
quale garante la nostra stessa esperienza, qualsiasi cosa gli altri
dicano non ha importanza.

Perciò, per favore, quando praticate non perdetevi nei dubbi. Non
attaccatevi ai vostri modi di pensare. Non attaccatevi ai modi di
pensare degli altri. Restando in questa posizione di mezzo, può nascere
la saggezza, correttamente e in piena misura. Offro spesso una semplice
analogia, e paragono l’attaccamento al posto in cui viviamo. Ad esempio,
ci sono il soffitto e il pavimento, il piano di sopra e quello di sotto.
Se qualcuno va al piano di sopra, sa di essere salito sopra. Se scende
al piano di sotto, sa di stare al piano di sotto, in piedi sul
pavimento. Possiamo capirlo tutti. Abbiamo la sensazione di dove ci
troviamo, sia al piano di sopra sia al piano di sotto. Non siamo però
consapevoli dello spazio che sta nel mezzo, perché non abbiamo modo di
individuarlo o di misurarlo. È solo spazio. Non comprendiamo lo spazio
nel mezzo. Esso però rimane così com’è, che qualcuno scenda o meno dal
piano di sopra non ha importanza. Così è il _saccadhamma_, non va da
nessuna parte, non cambia. Allora possiamo parlare di “non divenire”,
ossia di quello spazio mediano, non marcato o identificato da nulla. Non
può essere descritto.

Ad esempio, oggigiorno i più giovani che s’interessano al Dhamma
vogliono sapere del Nibbāna. A cosa somiglia? Però, se a loro parlate di
un posto privo di divenire, non vogliono andarci. Si tirano indietro.
Diciamo loro che questo posto è cessazione, pace, ma vogliono sapere
come vivranno, quale cibo mangeranno e quali divertimenti ci saranno.
Perciò non c’è fine. Le giuste domande per chi vuole conoscere la
Verità, sono domande su come praticare.

Un asceta incontrò il Buddha e gli chiese: « Chi è il tuo maestro? » Il
Buddha rispose: « Ho ottenuto l’Illuminazione grazie ai miei sforzi. Non
ho maestro. » Però, a quell’asceta itinerante questa risposta risultò
incomprensibile. Era troppo diretta. Le loro menti erano in posti
differenti. Anche se l’asceta avesse fatto domande per tutto il giorno e
per tutta la notte, non vi era nulla che fosse in grado di capire. La
mente illuminata è immobile e, perciò, non può essere compresa. Possiamo
sviluppare la saggezza e rimuovere i nostri dubbi solo per mezzo della
pratica, di nient’altro.

Allora non dovremmo ascoltare il Dhamma? Dovremmo, sì, però dovremmo
anche mettere in pratica la conoscenza che ne ricaviamo. Questo non
significa che stiamo seguendo una persona che ci insegna. Seguiamo
l’esperienza e la consapevolezza che sorge quando mettiamo in pratica
l’insegnamento. Abbiamo questa percezione, ad esempio: « Questa cosa mi
piace davvero. Mi piace fare le cose in questo modo! » Il Dhamma però
non consente questo piacere e quest’attaccamento. Se ci affidiamo
davvero al Dhamma, allora, quando comprendiamo che quell’oggetto che ci
attrae è contrario al Dhamma, lo lasciamo andare. A questo serve la
conoscenza.

Un sacco di parole: ora forse siete stanchi. Avete qualche domanda?
Bene, forse sì. Dovreste avere consapevolezza del lasciar andare. Le
cose passano e voi le lasciate andare, ma non in modo indolente e
indifferente, senza capire cosa stia avvenendo. Ci deve essere
consapevolezza. Tutto quello che vi ho detto suggerisce che è necessario
avere una consapevolezza che vi protegga in continuazione. Significa
praticare con saggezza, non con illusione. Quando la saggezza diverrà
chiara e continuerà ad aumentare, otterremo la vera conoscenza.
