= Dottrina vuota

____
Discorso informale tenuto da Ajahn Chah presso la sua kuṭī a un gruppo
di laici, una sera del 1978.
____

Due sono i modi di sostenere il buddhismo. Uno è noto come _āmisapūjā_,
il sostegno tramite offerte materiali, ossia i quattro beni di prima
necessità: cibo, abiti, ricovero e medicinali. Sono offerte materiali
per il Saṅgha dei monaci e delle monache, e consente loro di vivere in
un benessere ragionevole per la pratica del Dhamma. Ciò favorisce la
diretta realizzazione dell’insegnamento del Buddha, che a sua volta
apporta una continua prosperità alla religione buddhista.

Il buddhismo può essere paragonato a un albero. Un albero ha delle
radici, un tronco, dei rami, dei ramoscelli e delle foglie. Tutto, le
foglie e i rami, incluso il tronco, dipendono dalle radici per
l’assorbimento del nutrimento dal terreno. Proprio come l’albero dipende
dalle radici per il sostentamento, le nostre azioni e le nostre parole
sono come “rami” e “foglie” che dipendono dalla mente, la “radice”
che assorbe il nutrimento poi inviato al “tronco”, ai “rami” e alle
“foglie”. A loro volta queste fruttificano come parole e azioni. Quale
che sia lo stato in cui la mente si trova, salutare o meno che tale
stato possa essere, essa esprime le sue qualità esteriormente per mezzo
delle nostre azioni e delle nostre parole.

Perciò, sostenere il buddhismo mediante l’applicazione pratica
dell’insegnamento è il tipo di sostegno più importante. Ad esempio,
nella cerimonia per l’assunzione dei precetti nei giorni di osservanza
lunare, l’insegnante descrive le azioni non salutari che dovrebbero
essere evitate. Però, se durante questa cerimonia non riflettete sul
significato dei precetti, sarà difficile progredire e non sarete in
grado di realizzare la vera pratica. Il vero supporto del buddhismo deve
perciò essere attuato per mezzo della _paṭipattipūjā_, l’offerta della
pratica del Dhamma, coltivando vera moderazione, concentrazione e
saggezza. Allora saprete cos’è il buddhismo. Se non capite per mezzo
della pratica, anche se imparate tutto il _Tipiṭaka_ continuerete a non
sapere.

Ai tempi del Buddha c’era un monaco chiamato Tuccho Pothila. Era colto
davvero, profondamente versato nelle scritture e nei testi, così famoso
da essere riverito ovunque e alle sue cure erano affidati diciotto
monasteri. Quando la gente sentiva nominare Tuccho Pothila si sentiva in
soggezione e la reverenza in cui era tenuta la sua padronanza degli
insegnamenti era tale che nessuno osava mettere in questione nulla di
ciò che lui esponeva. Tuccho Pothila fu uno dei più colti discepoli del
Buddha. Un giorno andò a porgere omaggio al Buddha. Mentre lo faceva, il
Buddha disse: « Ah, salve, venerabile Dottrina Vuota! » Proprio così!
Conversarono per un po’, fino a che non giunse il momento di andare e,
quando Tuccho Pothila stava per accomiatarsi, il Buddha gli disse: « Oh,
stai per andar via, venerabile Dottrina Vuota? »

Il Buddha disse solo queste cose. All’arrivo: « Ah, salve, venerabile
Dottrina Vuota! » Quando era giunto il momento di andare: « Oh, stai per
andar via, venerabile Dottrina Vuota? » Il Buddha non si dilungò, solo
questo fu l’insegnamento che impartì. Tuccho Pothila, maestro eminente,
era perplesso: « Perché il Buddha lo ha detto? Che voleva dire? »
Pensando e ripensando, passò in rassegna tutto ciò che aveva imparato
fino a che non capì: « È vero! Venerabile Dottrina Vuota, un monaco che
studia ma non pratica. » Quando guardò nel suo cuore vide che, in
realtà, non era diverso dai laici. Aspirava alle stesse cose alle quali
aspiravano i laici, si dilettava con le stesse cose con cui si
dilettavano i laici. Dentro di lui non vi era proprio alcun
_samaṇa_,footnote:[_samaṇa._ Un contemplativo. Letteralmente, chi
abbandona gli obblighi convenzionali della vita sociale per un modo di
vivere più in sintonia con la natura.] davvero non vi era alcuna
profonda qualità in grado di insediarlo stabilmente sul Nobile Sentiero
e di dargli una pace vera.

Decise perciò di praticare. Per lui, però, non vi era un posto nel quale
recarsi. Tutti i maestri dei dintorni erano suoi discepoli, nessuno
avrebbe osato accoglierlo. Di solito, quando le persone hanno a che fare
con il loro maestro diventano timide e deferenti, e per questo nessuno
avrebbe osato diventare il suo insegnante. Infine egli andò a trovare un
giovane novizio, che era però un Illuminato, e gli chiese di praticare
sotto la sua guida. « Certo che puoi praticare con me, ma solo se sei
sincero; se non sei sincero, non ti accetterò », disse il novizio.
Tuccho Pothila si impegnò come discepolo del novizio.

Il novizio gli disse di indossare le sue vesti al completo. Nei pressi
vi era un fangoso acquitrino. Quando Tuccho Pothila ebbe indossato per
bene tutte le sue vesti, alcune delle quali anche costose, il novizio
disse: « Bene, adesso corri a rotolarti in quel fangoso acquitrino. Fino
a quando non ti dirò di fermarti, non fermarti. Se non ti dico di
uscirne, non uscirne. Bene, corri! »

Tuccho Pothila, vestito di tutto punto, si tuffò nell’acquitrino. Il
novizio non gli chiese di fermarsi fino a quando non fu completamente
ricoperto di fango. Infine gli disse: « Ora puoi fermarti. » Così, egli
si fermò. « Bene, adesso vieni fuori! » E lui ne venne fuori. Questo
indicò con chiarezza al novizio che Tuccho Pothila aveva rinunciato al
suo orgoglio. Era pronto ad accogliere l’insegnamento. Siccome era un
maestro molto famoso, se non fosse stato pronto a imparare non si
sarebbe gettato nell’acquitrino in quel modo, ma lui lo fece. Il giovane
novizio seppe allora che Tuccho Pothila era sinceramente determinato a
praticare.

Quando Tuccho Pothila uscì dall’acquitrino, il novizio gli impartì
l’insegnamento. Gli insegnò a osservare gli oggetti dei sensi, a
conoscere la mente e a conoscere gli oggetti dei sensi, usando la
similitudine dell’uomo che cattura una lucertola nascosta in un
termitaio. Se il termitaio ha sei fori, come farà a catturarla? Dovrà
sigillare cinque fori e lasciarne aperto solo uno. Poi, dovrà limitarsi
a osservare e attendere, sorvegliando quel foro. Quando la lucertola
uscirà, potrà catturarla.

Questo è il modo per osservare la mente. Chiudendo gli occhi, gli
orecchi, il naso, la lingua e il corpo, resta solo la mente.
“Chiudere” i sensi significa contenerli e calmarli, osservando solo la
mente. La meditazione è come catturare la lucertola. Usiamo _sati_ per
osservare il respiro. _Sati_ è la qualità del rammemorare, come quando
chiedete a voi stessi: « Che cosa sto facendo? »
__Sampajañña__footnote:[_sampajañña._ “Chiara comprensione”,
consapevolezza di sé, auto-rammemorazione, attenzione, consapevolezza,
presenza mentale, comprensione profonda.] è la consapevolezza che “ora
sto facendo così e così”. Osserviamo il respiro che entra ed esce con
_sati_ e _sampajañña_.

Questa qualità del rammemorare è una cosa che sorge dalla pratica, non
può essere imparata dai libri. Significa conoscere le sensazioni che
sorgono. La mente può essere relativamente inattiva per un po’, ed ecco
che sorge una sensazione. _Sati_ lavora in connessione con queste
sensazioni, rammemorandole. C’è _sati_, il rammemorare che “parlo”,
“vado”, “siedo” e così via, e poi c’è _sampajañña_, la
consapevolezza che “ora sto camminando”, “sto giacendo”, “sto
sperimentando questo o quello stato d’animo”. Con _sati_ e con
_sampajañña_ possiamo conoscere le nostre menti nel momento presente e
sapere come la mente reagisce alle impressioni sensoriali.

Ciò che è consapevole degli oggetti sensoriali si chiama “mente”. Gli
oggetti dei sensi “vagano dentro” la mente. Ad esempio, c’è un suono,
come quello del trapano elettrico che sta qui. Esso entra attraverso
l’orecchio e viaggia all’interno della mente, la quale riconosce che è
il rumore di un trapano elettrico. Ciò che riconosce il suono si chiama
“mente”. Ora, la mente che riconosce quel suono è piuttosto semplice.
È solo la mente comune. Forse sorge in colui che prova del fastidio.
Dobbiamo addestrare ulteriormente “colui che riconosce” affinché
divenga “Colui che Conosce” in accordo con la Verità, noto come
_Buddho_. Se non conosciamo con chiarezza in accordo con la Verità, ecco
che siamo infastiditi dai rumori della gente, delle automobili, dei
trapani elettrici e così via. Questa è solo una mente ordinaria e non
addestrata che, con fastidio, riconosce il suono. Conosce in accordo con
le sue preferenze, non in accordo con la realtà. Dobbiamo addestrarla
ulteriormente per conoscere mediante la visione profonda
(_ñāṇadassana_),footnote:[_ñāṇadassana._ Conoscenza e visione, anche
all’interno delle Quattro Nobili Verità.] con il potere della mente
affinata, affinché conosca il suono semplicemente come suono. Se non ci
attacchiamo al suono non c’è fastidio. Il suono sorge e noi
semplicemente lo notiamo. Sorge in conseguenza di condizioni, non è un
essere, un individuo, un sé, un “noi” o “loro”. È solo un suono, e
la mente lo lascia andare.

Questo conoscere è chiamato _Buddho_, quella conoscenza che è chiara e
penetrante. Con questa conoscenza possiamo lasciare che un suono sia
semplicemente un suono. Non ci disturba, a meno che non lo disturbiamo
noi pensando: « Non voglio sentire quel suono, è fastidioso. » La
sofferenza sorge a causa di questo pensiero. Proprio qui sta la causa
della sofferenza, nel fatto che non conosciamo la verità al riguardo,
che non abbiamo sviluppato _Buddho_. Non siamo ancora liberi, non ci
siamo ancora risvegliati, non siamo ancora consapevoli. Questa è la
mente grezza, non addestrata. Questa mente non ci è molto utile.

Per questa ragione il Buddha insegnò che questa mente deve essere
addestrata e sviluppata. Dobbiamo potenziare la mente proprio come
potenziamo il corpo, ma lo facciamo in modo differente. Per sviluppare
il corpo dobbiamo allenarlo, correndo al mattino e alla sera, e così
via. Questo è allenare il corpo. Il risultato è che il corpo diventa più
agile, più forte, il sistema respiratorio e il sistema nervoso diventano
più efficienti. Per esercitare la mente non dobbiamo tenerla in
movimento, ma indurla a fermarsi, indurla a riposare.

Ad esempio, quando pratichiamo la meditazione assumiamo come nostro
fondamento un oggetto, come l’inspirazione e l’espirazione. Questo
diventa il centro della nostra attenzione e riflessione. Osserviamo il
respiro. Osservare il respiro significa seguire il respiro con
consapevolezza, notarne il ritmo, il suo andare e venire. Applichiamo la
consapevolezza al respiro, seguendo la naturale inspirazione ed
espirazione e lasciando andare tutto il resto. Il risultato del rimanere
con un solo oggetto di consapevolezza è che la nostra mente si riposa.
Se lasciamo che la mente pensi a questo, a quello e a quell’altro ancora
gli oggetti di consapevolezza sono troppi; la mente non si unifica, non
riesce a riposarsi.

Dire che la mente si ferma significa che essa percepisce di essersi
fermata, non va scappando di qui e di là. È come avere un coltello
affilato. Se lo usiamo per tagliare di tutto indiscriminatamente,
pietre, mattoni ed erba, il nostro coltello presto non sarà più
tagliente. Dovremmo usarlo solo per tagliare le cose giuste. La nostra
mente è la stessa cosa. Se lasciamo che la mente vaghi rincorrendo
pensieri e sensazioni senza valore o inutili, si stanca e s’indebolisce.
Se la mente non ha energia, non sorgerà la saggezza, perché la mente
priva di energia è la mente priva di _samādhi_.

Se la mente non si ferma, non potete vedere con chiarezza gli oggetti
dei sensi per quello che sono. La conoscenza che la mente è la mente e
gli oggetti dei sensi sono solo gli oggetti dei sensi è la radice dalla
quale il buddhismo è cresciuto e si è sviluppato. Questo è il cuore del
buddhismo. Dobbiamo coltivare questa mente, svilupparla, addestrarla
alla calma e alla visione profonda. Addestriamo la mente a essere
moderata e saggia facendola fermare, consentendo alla saggezza di
sorgere, conoscendo la mente così com’è.

Sapete come siamo noi esseri umani, come facciamo le cose, siamo proprio
come dei bambini. Un bambino non sa nulla. Per un adulto che osserva il
comportamento di un bambino, il modo in cui gioca saltando qua e là e le
sue azioni non sembrano avere molto senso. La nostra mente, se non è non
addestrata, è come un bambino. Parliamo senza consapevolezza e agiamo
senza saggezza. Possiamo andare in rovina o causare mali indicibili
senza nemmeno saperlo. Un bambino è ignorante, gioca, come fanno i
bambini. La nostra mente ignorante è la stessa cosa.

Perciò dovremmo addestrare questa mente. Il Buddha ci insegnò ad
addestrare la mente, a insegnare alla mente. Anche se sosteniamo il
buddhismo con i quattro beni di prima necessità, il nostro sostegno è
ancora superficiale, raggiunge solo la “corteccia” o l’“alburno”
dell’albero. Il vero sostegno al buddhismo deve essere costruito per
mezzo della pratica, in nessun altro modo, cioè addestrando le nostre
azioni, le nostre parole e i nostri pensieri secondo gli insegnamenti.
Questo è molto più fruttuoso. Se siamo retti e onesti, se siamo
contenuti e saggi, la nostra pratica porterà prosperità. Non ci saranno
le cause per dispetti e ostilità. Così ci insegna la nostra religione.

Se prendiamo i precetti solo per tradizione, allora anche se l’_ajahn_
insegna la Verità, la nostra pratica sarà manchevole. Potremmo anche
essere capaci di studiare gli insegnamenti e di ripeterli, ma dobbiamo
praticarli se vogliamo davvero capire. Se non sviluppiamo la pratica,
ciò potrebbe essere d’ostacolo alla nostra comprensione profonda del
buddhismo per innumerevoli vite future. Non capiremo l’essenza della
religione buddhista.

Per questa ragione la pratica è come una chiave, la chiave della
meditazione. Abbiamo in mano la chiave giusta e non importa quanto
saldamente sia chiusa la serratura. Se prendiamo la chiave e la giriamo,
la serratura si apre. Se non abbiamo la chiave, non possiamo aprire la
serratura. Non sapremo mai cosa c’è nel baule.

Ci sono due tipi di conoscenza. Chi conosce il Dhamma non parla usando
solo la memoria, dice la Verità. La gente del mondo di solito parla con
presunzione. Supponiamo ad esempio che ci siano due persone che non si
vedono da molto tempo; forse sono andate a vivere in province o in
nazioni diverse per un po’ e, poi, un giorno, capita che si incontrino
sul treno: « Oh! Che sorpresa. Stavo proprio pensando di cercarti! »
Forse non è vero. In realtà non avevano pensato affatto l’uno all’altro,
ma lo dicono perché sono preda dell’entusiasmo. E così nasce una
menzogna. Sì, è mentire per disattenzione. Questo è mentire senza
saperlo. È una forma sottile di contaminazione, e avviene molto spesso.

Per quanto concerne la mente, Tuccho Pothila seguì le istruzioni del
novizio: inspirare, espirare, piena consapevolezza di ogni respiro, fino
a che non vide il mentitore che stava dentro di lui, il mentire della
sua stessa mente. Vide le contaminazioni man mano che affioravano,
proprio come si vedrebbe la lucertola che esce dal termitaio. Le vide e,
appena sorgevano, ebbe la percezione della loro vera natura. Notò come
la mente inventava una cosa ora e qualcos’altro nel momento successivo.

Pensare è _saṅkhata-dhamma_,footnote:[_saṅkhata-dhamma._ Fenomeno
condizionato, realtà convenzionale, in contrapposizione con
l’Incondizionato (_asaṅkhata-dhamma_), ossia il _Nibbāna_.] un qualcosa
che si crea o si inventa sulla base di condizioni che fungono da
supporto. Non è _asaṅkhata-dhamma_, l’incondizionato. La mente ben
addestrata di chi è dotato di perfetta consapevolezza non architetta
stati mentali. Questo tipo di mente penetra le Nobili Verità e trascende
ogni necessità di dipendere da cose esteriori. Conoscere le Nobili
Verità è conoscere la Verità. La mente che prolifera cerca di sfuggire a
queste verità dicendo “questo è bene” o “questo è bello”, ma se
nella mente c’è _Buddho_, essa non può più ingannarci perché la
conosciamo per quello che è. La mente non può più creare stati mentali
illusori, perché vi è chiara consapevolezza del fatto che tutti gli
stati mentali sono instabili, imperfetti e fonte di sofferenza per chi
s’aggrappa a essi.

“Colui che Conosce” era sempre nella mente di Tuccho Pothila, ovunque
egli andasse. Osservò le varie creazioni e proliferazioni della mente
con comprensione. Vide in quanti modi la mente è menzognera. Afferrò
l’essenza della pratica, vedendo che « questa mente menzognera è quel
che bisogna osservare, questo è ciò che ci conduce agli estremi della
felicità e della sofferenza, e ci induce a vorticare nel ciclo del
_saṃsāra_ con il suo piacere e il suo dolore, il suo bene e il suo male,
tutto avviene a causa di questa mente menzognera. » Tuccho Pothila
comprese la Verità, e afferrò l’essenza della pratica, proprio come
l’uomo che afferra la lucertola per la coda. Vide la mente illusa mentre
lavora.

Per noi è la stessa cosa. Solo la mente è importante. Questa è la
ragione per cui abbiamo bisogno di addestrarla. Ora, se la mente è la
mente, con che cosa l’addestreremo? Avendo ininterrottamente _sati_ e
_sampajañña_ saremo in grado di conoscere la mente. Colui che Conosce
sta un passo al di là della mente, è ciò che conosce lo stato della
mente. La mente è la mente. Ciò che conosce la mente come semplice mente
è Colui che Conosce. È al di sopra della mente. Colui che Conosce è al
di sopra della mente ed è perciò in grado di sorvegliarla, di insegnarle
a conoscere ciò che è giusto e ciò che è sbagliato. Alla fine tutto
torna a questa mente che prolifera. Se la mente resta catturata dalle
sue proliferazioni non vi è consapevolezza e la pratica è infruttuosa.

Dobbiamo perciò addestrare questa mente ad ascoltare il Dhamma, a
coltivare _Buddho_, la chiara e radiosa consapevolezza, ciò che esiste
al di sopra e al di là della mente ordinaria e che conosce tutto quello
che succede al suo interno. Per questo meditiamo con la parola _Buddho_,
per essere in grado di conoscere la mente oltre la mente. Osservate solo
tutti i movimenti della mente, buoni o cattivi che siano, finché Colui
che Conosce non comprende che la mente è semplicemente la mente, non un
sé o una persona. Questo è chiamato _cittānupassanā_, contemplazione
della mente.footnote:[_cittānupassanā._ La contemplazione della mente,
uno dei quattro fondamenti della consapevolezza esposti dettagliatamente
nel _Mahāsatipaṭṭhāna Sutta_ (D. 22.); si veda il
<<glossary#satipatthana,Glossario, satipaṭṭhāna>>.] Vedendo in questo modo
capiremo che la mente è transitoria, imperfetta e priva di un
proprietario. La mente non ci appartiene.

Riassumendo. La mente è ciò che riconosce gli oggetti dei sensi. Gli
oggetti dei sensi sono oggetti dei sensi, distinti dalla mente. “Colui
che Conosce” conosce sia la mente sia gli oggetti dei sensi per quello
che sono. Dobbiamo utilizzare _sati_ per tenere costantemente pulita la
mente. Tutti hanno _sati_, perfino un gatto quando sta per catturare un
topo. Un cane quando abbaia alla gente. È una forma di _sati_, ma non è
_sati_ in coerenza con il Dhamma. Tutti hanno _sati_, ma vari sono i
livelli di _sati_, proprio come si possono guardare le cose a differenti
livelli. Quando ad esempio dico di contemplare il corpo, alcuni
affermano: « Che c’è da contemplare nel corpo? Tutti possono vederlo.
_Kesā_, i capelli, possiamo già vederli. _Lomā_, i peli, possiamo già
vederli. Capelli, peli, unghie, denti e pelle, tutte cose che possiamo
già vedere. E allora? »

La gente è fatta così. Può vedere bene il corpo, ma ha la vista
difettosa, non vede mediante _Buddho_, “Colui che Conosce”, il
Risvegliato. Vede il corpo solo nel modo ordinario, lo vede visivamente.
Vedere semplicemente il corpo non è abbastanza. Se vediamo solamente il
corpo ci sono problemi. Dovete vedere il corpo nel corpo, allora le cose
diventano molto più chiare. Solo vedendo il corpo ne sarete ingannati,
la sua apparenza vi affascinerà. Se non si vede la transitorietà,
l’imperfezione e l’insostanzialità sorge
_kāmacchanda_.footnote:[_kāmacchanda._ Desiderio sensoriale; uno dei
cinque impedimenti o ostacoli (_nīvaraṇa_) per il progresso spirituale.]
Siete incantati dalle forme, dai suoni, dagli odori, dai sapori e dalle
sensazioni. Vedere in questo modo significa vedere con gli occhi mondani
della carne, che vi inducono ad amare e odiare, e a discriminare tra
sensazioni piacevoli e spiacevoli.

Il Buddha insegnò che questo non è sufficiente. Dovete vedere con gli
“occhi della mente”. Vedere il corpo all’interno del corpo. Se davvero
guardate dentro il corpo, uh! È così repellente. In esso ci sono cose di
oggi e cose di ieri tutte mischiate insieme, non si possono distinguere
l’una dall’altra. Vedendo in questo modo è tutto molto più chiaro di
quel che si vede con l’occhio della carne. Contemplate, vedete con
l’occhio della mente, con l’occhio della saggezza. La gente capisce
diversamente. Alcuni non comprendono cosa ci sia da contemplare nelle
cinque meditazioni su capelli, peli, unghie, denti e pelle. Dicono che
queste cose già riescono a vederle, ma possono vederle solo con l’occhio
della carne, con questo “folle occhio” che guarda solo le cose che
vuole vedere. Per vedere il corpo nel corpo dovete guardare con maggior
chiarezza.

Questa è la pratica che può sradicare l’attaccamento ai cinque
_khandhā_.footnote:[_khandhā._ Aggregato, insieme di elementi col quale
ci si identifica; le componenti fisiche e mentali della personalità e
dell’esperienza sensoriale in generale.] Sradicare l’attaccamento è
sradicare la sofferenza, perché l’attaccamento ai cinque _khandhā_ è la
causa della sofferenza. Se sorge la sofferenza, è qui che sorge. Non è
che i cinque _khandhā_ di per sé siano sofferenza, ma l’attaccamento a
essi come se ci appartenessero, quella è sofferenza. Se vedete con
chiarezza la verità di queste cose per mezzo della pratica di
meditazione, allora la sofferenza si allenta, come una vite o un
bullone. Quando il bullone si allenta, si ritrae. La mente si allenta
nello stesso modo, lasciando andare; ritirandosi dall’ossessione per il
bene e per il male, per i possessi, per l’apprezzamento e per la
posizione sociale, per la felicità e per la sofferenza.

Non conoscendo la verità di queste cose è come stringere la vite in
continuazione. Si serra sempre più fino a quando, mentre sta per
stritolarvi, soffrite per qualsiasi cosa. Quando sapete come stanno le
cose, allentate la vite. Nel linguaggio del Dhamma questo si chiama
_nibbidā_, disincanto. Diventate stanchi delle cose, non vi affascinano
più. Se svitate in questo modo, troverete la pace.

La causa della sofferenza è l’attaccamento alle cose. Dovremmo perciò
sbarazzarci della causa, tagliare via le sue radici e non consentire di
nuovo all’attaccamento di causare sofferenza. La gente ha un solo
problema: l’attaccamento. In ragione di questa sola cosa le persone si
uccidono a vicenda. Tutti i problemi, siano essi individuali, famigliari
o sociali, sorgono da quest’unica radice. Nessuno vince, si uccidono
l’un l’altro, ma alla fine nessuno ottiene nulla. È privo di senso, non
so perché la gente continui a uccidersi a vicenda.

Potere, possessi, posizione sociale, lode, felicità e sofferenza: questi
sono _dhamma_ mondani. Questi _dhamma_ mondani fagocitano gli esseri
mondani. Gli esseri mondani sono trascinati qui e là dai _dhamma_
mondani. Guadagno e perdita, lode e biasimo, posizione sociale e perdita
di essa, felicità e sofferenza. Questi _dhamma_ generano problemi. Se
non riflettete sulla loro vera natura, soffrirete. La gente arriva a
uccidere per la ricchezza, la posizione sociale o il potere. Perché?
Perché prendono tutto questo troppo seriamente. Vengono scelti per un
qualche ruolo e si montano la testa, come quell’uomo che divenne il capo
del villaggio. Dopo la sua nomina il potere lo ubriacò. Se uno dei suoi
vecchi amici andava a trovarlo, diceva: « Non venire così spesso, le
cose non sono più come prima. »

Il Buddha ci insegnò a comprendere la natura dei possessi, della
posizione sociale, della lode e della felicità. Prendete queste cose
quando arrivano, ma lasciate che siano quello che sono. Non permettete
che vi diano alla testa. Se non comprendete davvero queste cose, sarete
ingannati dal vostro potere, dai vostri figli e parenti, da qualsiasi
cosa! Se le comprendete con chiarezza, saprete che sono tutte condizioni
impermanenti. Se vi attaccate a esse, si contaminano.

Tutte queste cose sorgono in seguito. Appena le persone nascono, sono
solamente __nāma__footnote:[_nāma._ Fenomeno mentale.] e
_rūpa_,footnote:[_rūpa._ Fenomeno fisico; dato sensoriale.] questo è
tutto. Poi aggiungiamo il “signor Tizio”, la “signora Caio” e così
via. Lo si fa in base a convenzioni. Più tardi ancora arrivano le
appendici di “colonnello”, “generale” e quant’altro. Se non
comprendiamo davvero queste cose, pensiamo che siano reali e le portiamo
con noi ovunque. Portiamo con noi nome, possessi, posizione e rango
sociale. Te la suoni e te la canti, se hai potere … « Prendi questo e
giustizialo. Prendi quell’altro e mettilo in carcere. » Il rango sociale
dà potere. L’attaccamento s’aggrappa a questa parola, “rango”. Non
appena le persone occupano una posizione, iniziano a dare ordini. Giusto
o sbagliato che sia, regolano i loro comportamenti in base al loro
umore. Così, vanno avanti e fanno sempre gli stessi vecchi errori,
allontanandosi sempre più dal vero Sentiero.

Chi comprende il Dhamma non si comporterà in questo modo. Non si sa da
quanto tempo bene e male esistono nel mondo. Se possessi e condizione
sociale si presentano sul vostro cammino, lasciate che siano
semplicemente possessi e condizione sociale: non identificatevi con
essi. Utilizzateli solo per adempiere ai vostri obblighi, limitatevi a
questo. Voi restate gli stessi di sempre. Se avete meditato in questo
modo, non importa cosa si presenterà sul vostro cammino, non sarete
condotti fuori strada. Resterete imperturbati, ininfluenzabili e
costanti. Dopo tutto, ogni cosa resta praticamente la stessa.

Il Buddha voleva che comprendessimo le cose in questo modo. Non conta
ciò che ottenete, la mente non aggiunge nulla. Vi nominano consigliere
comunale: « Bene, sono un consigliere comunale, ma non lo sono. » Vi
nominano a capo di un gruppo: « Certo che lo sono, ma non lo sono. »
Qualsiasi cosa vi facciano diventare: « Lo sono, ma non lo sono! »
Comunque, che cos’è che siamo in fin dei conti? Alla fine si muore
tutti. Non importa cosa vi facciano diventare, alla fine è sempre la
stessa cosa. Cosa potete dire? Se riuscite a vedere le cose in questo
modo, avrete salda dimora e vero appagamento. Non sarà cambiato nulla.
Non fatevi ingannare dalle cose. Qualsiasi cosa si presenti sul vostro
cammino, si tratta solo di fenomeni condizionati. Non c’è niente che
riesca meglio di queste cose a indurre una mente a creare, a
proliferare, seducendola e facendola cadere nell’avidità,
nell’avversione e nell’illusione.

Questo significa essere veri sostenitori del buddhismo. Sia che vi
troviate fra coloro che sono sostenuti, il Saṅgha, o tra coloro che lo
sostengono, i laici, prendete accuramente in considerazione tutto
questo. Coltivate il __sīla-dhamma__footnote:[_sīla-dhamma._ Un altro
modo per indicare gli insegnamenti morali del buddhismo.] dentro di voi.
È il modo più sicuro per sostenere il buddhismo. Anche sostenere il
buddhismo offrendo cibo, ricovero e medicine è bene, ma queste offerte
raggiungono solo l’“alburno” del buddhismo. Non dimenticatelo, per
favore. Un albero ha corteccia, alburno e durame, e queste tre parti
sono interdipendenti. Il durame deve poter fare affidamento sulla
corteccia e sull’alburno. L’alburno fa affidamento sulla corteccia e sul
durame. Esistono tutti in modo interdipendente, proprio come gli
insegnamenti di disciplina morale (_sīla_), concentrazione (_samādhi_) e
saggezza (_paññā_). L’insegnamento sulla disciplina morale serve a
fondare le vostre parole e azioni nella rettitudine. L’insegnamento
sulla concentrazione serve a dare stabilità alla mente. L’insegnamento
sulla saggezza è la completa comprensione della natura di tutti i
fenomeni condizionati. Studiate questo, praticate questo, e
comprenderete il buddhismo nel modo più profondo.

Se queste cose non le capite, sarete ingannati dai possessi, sarete
ingannati dal rango sociale, sarete ingannati da tutto ciò con cui
giungerete in contatto. Sostenere il buddhismo solo in modo esteriore
non porrà mai fine a lotte e battibecchi, a rancori e animosità, ad
accoltellamenti e sparatorie. Per far cessare queste cose dobbiamo
riflettere sulla natura dei possessi, del rango, della lode, della
felicità e della sofferenza. Dobbiamo riflettere sulla nostra vita e
metterla in linea con l’insegnamento. Dovremmo riflettere sul fatto che
tutti gli esseri del mondo fanno parte di un tutt’uno. Noi siamo come
loro, loro sono come noi. Hanno felicità e tristezza, proprio come noi.
È tutto molto simile. Se pensiamo in questo modo, sorgeranno pace e
comprensione. Questo è il fondamento del buddhismo.
