[[fatelo]]
= Fatelo!

____
È un vivace discorso in laotiano offerto nel Wat Pah Pong a un’assemblea
di monaci da poco ordinati, il primo giorno del Ritiro delle Piogge, nel
luglio del 1978.
____

Continuate solo a inspirare e a espirare. Non deve interessarvi
nient’altro. Non importa se qualcuno sta a testa in giù e con il sedere
in su. Non prestateci alcuna attenzione. Dimorate semplicemente
nell’inspirazione e nell’espirazione. Concentrate la vostra presenza
mentale sul respiro. Continuate così, semplicemente. Non occupatevi di
nient’altro. Non c’è bisogno di pensare ad accumulare cose. Non
occupatevi assolutamente di nulla. Conoscete solo l’inspirazione e
l’espirazione. L’inspirazione e l’espirazione. _Bud_, con
l’inspirazione, _dho_, con l’espirazione. Dimorate solo nel respiro in
questo modo, fino a quando siete consapevoli dell’inspirazione e
consapevoli dell’espirazione, consapevoli dell’inspirazione e
consapevoli dell’espirazione. Siate consapevoli in questo modo fino a
quando la mente si tranquillizza e, priva di irritazione e agitazione,
resta solo il respiro che entra ed esce. Lasciate che la mente rimanga
in questo stato. Non avete bisogno di una meta. Questo è il primo stadio
della pratica.

Se la mente è a proprio agio, se è in pace, sarà naturalmente
consapevole. Man mano che continuate il respiro s’attenua, diventa più
sottile. Il corpo diviene flessibile, la mente diviene flessibile. È un
processo naturale. Sedete comodi. Non vi annoiate, il capo non vi
ciondola, non siete assonnati. Qualsiasi cosa faccia, la mente ha una
sua naturale fluidità.

È tranquilla. È in pace. Quando uscite dal _samādhi_, dite a voi stessi:
« Oh! Cos’è stato? » Ricordate la pace che avete appena sperimentato.
Non la dimenticherete mai. Dopo vengono quelle cose che sono chiamate
_sati_, la forza della rammemorazione, e _sampajañña_, la consapevolezza
di sé. Qualsiasi cosa facciate o diciate, ovunque andiate, a fare la
questua o altrove, mentre consumate il pasto o lavate la ciotola,
siatene consapevoli. Siate sempre mentalmente presenti. Seguite la
mente.

Quando state per praticare la meditazione camminata (_caṅkama_)
scegliete un sentiero, ad esempio da un albero a un altro, di circa
quindici metri. Fare _caṅkama_ è come fare meditazione seduta.
Focalizzate la vostra attenzione: « Ora intendo impegnarmi a fondo. Sto
per pacificare la mia mente con forte rammemorazione e consapevolezza di
sé. » L’oggetto della concentrazione dipende dalla persona. Cercate ciò
che fa per voi. Alcuni effondono __mettā__footnote:[_mettā._ Gentilezza
amorevole, benevolenza, cordialità, amichevolezza.] su tutti gli esseri
senzienti e poi cominciano con il piede destro, camminano ad andatura
normale e s’avvalgono del mantra _Buddho_, continuamente consapevoli di
tale oggetto di concentrazione. Se la mente si agita, si fermano,
calmano la mente e poi riprendono a camminare, costantemente consapevoli
di se stessi. Consapevoli all’inizio del sentiero, consapevoli in ogni
punto del sentiero, all’inizio, a metà e alla fine. Rendete continua
questa conoscenza.

Questo è un metodo: focalizzarsi sulla camminata _caṅkama_. Camminare
_caṅkama_ significa “camminare avanti e indietro”. Non è facile.
Quando ci vedono camminare su e giù, alcuni pensano che siamo pazzi. Non
capiscono che camminare _caṅkama_ fa sorgere una grande saggezza.
Camminare avanti e indietro. Se siete stanchi, restate in piedi e
fermate la mente. Concentratevi per rendere fluido il respiro. Quando è
ragionevolmente fluido, spostate nuovamente l’attenzione sul camminare.

Le posture cambiano da sé. In piedi, camminando, seduti, distesi.
Cambiano. Non stiamo tutto il tempo solo seduti oppure in piedi, o
distesi. Siccome dobbiamo trascorrere il nostro tempo in queste diverse
posture, rendiamole utili tutte e quattro. Funziona così. Continuiamo
solo così. Non è facile.

Per visualizzare tutto ciò con facilità, prendete questo bicchiere e
posatelo qui per due minuti. Quando i due minuti sono trascorsi,
spostatelo qua per due minuti. Poi rimettetelo di nuovo qui per altri
due minuti. Continuate a farlo. Fatelo in continuazione, fino a che non
cominciate a soffrire, fino a che non dubitate, fino a che non sorge la
saggezza. « Che cosa penso di fare spostando un bicchiere avanti e
indietro come un matto? » La mente penserà secondo le sue normali
abitudini, in accordo con i fenomeni. Non importa quel che dice.
Continuate a spostare quel bicchiere. Fatelo ogni due minuti – bene, non
sognate a occhi aperti – non ogni cinque minuti. Appena i due minuti
sono passati, spostatelo di nuovo qui. Concentratevi su questo. È questo
il punto.

Osservare le inspirazioni e le espirazioni è la stessa cosa. State
seduti con il piede destro poggiato sulla gamba sinistra, a busto
eretto, osservate l’inspirazione per tutta la sua ampiezza finché non
scompare nell’addome. Quando l’inspirazione è completa, lasciate uscire
il respiro finché i polmoni non si svuotano. Non forzate il respiro. Non
importa quanto sia lungo o corto o lieve, lasciate che sia quello giusto
per voi. Sedete e osservate l’inspirazione e l’espirazione, cercate di
sentirvi a vostro agio. Non permettete alla mente di perdersi. Se si
perde fermatevi, osservate per vedere dov’è andata, perché non è con il
respiro. Seguitela e riportatela indietro. Fatela tornare a stare con il
respiro e un giorno – non c’è dubbio – sarete ricompensati. Continuate a
farlo. Fatelo come se non doveste ottenere proprio nulla, come se non
dovesse avvenire nulla, come se non sapeste chi lo stia facendo, ma ad
ogni modo continuate a farlo. Come si fa col riso immagazzinato. Lo
prendete dal magazzino e lo spargete nei campi, come se lo steste
gettando via. Lo spargete nei campi senza interessarvi a ciò che fate,
esso però germoglierà e le piante di riso cresceranno. Lo trapianterete
e poi otterrete del dolce riso verde.footnote:[Si tratta del riso
glutinoso, il _khao niao_ (ข้าวเหนียว).] Così stanno le cose.

È uguale. Basta sedersi lì. A volte potreste pensare: « Perché sto
osservando il respiro così intensamente? Anche se non lo osservassi,
continuerebbe comunque a entrare e uscire. » Bene, troverete comunque
qualcosa da pensare. È solo un punto di vista. È un’espressione della
mente. Dimenticatela. Continuate sempre a cercare di pacificare la
mente. Quando la mente sarà pacificata, il respiro diminuirà, il corpo
si rilasserà, la mente diverrà sottile. Saranno in uno stato di
equilibrio, fino a che il respiro sembrerà non esserci, ma non vi
succederà nulla. Quando raggiungerete questo punto, non entrate in
panico, non alzatevi e non scappate via perché credete di aver smesso di
respirare. Significa solo che la mente è pacificata. Non dovete fare
nulla. Restate solo seduti a guardare tutto ciò che si presenta.

A volte potreste chiedervi: « Ehi, sto respirando? » Si tratta dello
stesso errore. È la mente che pensa. Qualsiasi cosa succeda, consentite
alle cose di seguire il loro corso naturale, quale che sia la sensazione
che sorge. Conoscetela, guardatela. Non lasciate che vi inganni.
Continuate a farlo, continuate a farlo. Fatelo spesso. Dopo il pasto,
appendete il vostro __jeewon__footnote:[La veste monastica dei monaci
_theravādin_ che copre la parte superiore del corpo è un ampio
rettangolo di stoffa (in pāli: _uttarā-saṅgha_; in thailandese _jeewon_,
จีวร) che si avvolge attorno al corpo e che spesso viene messo ad
asciugare dall’umidità e dal sudore al ritorno della questua. Vi è poi
la parte inferiore della veste, un rettangolo più piccolo indossato
dalla vita in giù (in pāli: _antara-vāsaka_; in thailandese: _sabong_,
สบง). Oltre alla veste superiore e a quella inferiore vi è una veste
esterna a doppio strato (in pāli: _saṅghāti_; in thailandese สังฆาฏิ)
che in genere viene portata ripiegata lungo la spalla sinistra in
situazioni cerimoniali.] a prendere aria sulla corda dei panni, e uscite
subito fuori sul sentiero per la meditazione camminata. Continuate a
pensare _Buddho_, _Buddho_. Pensatelo per tutto il tempo che state
camminando. Mentre camminate concentratevi sulla parola _Buddho_.
Continuate a consumare il sentiero, consumatelo fino a che non scavate
una fossa che vi arriva a metà polpaccio o sopra alle ginocchia.
Continuate solo a camminare. Non è passeggiare in modo meccanico e,
lungo il percorso, pensare a questo o a quello per poi tornare nella
vostra capanna, guardare la stuoia sulla quale dormite – « Quant’è
invitante! » – e sdraiarsi e russare come maiali. Se lo fate, non
otterrete proprio nulla dalla vostra pratica.

Continuate a farlo finché non siete esausti e guardate fino a che punto
riesce ad arrivare la pigrizia. Continuate a osservare fino a quando la
pigrizia non si esaurisce. Qualsiasi cosa sperimentiate, per
sconfiggerla dovete prima attraversarla completamente. Non è come
ripetere la parola “pace” a se stessi e, poi, non appena ci si siede,
attendersi che la pace arrivi come al “click” di un interruttore e,
quando questo non succede, rinunciare pigramente. Se fate così, non
troverete mai la pace.

È facile parlarne, ma è difficile farlo. È come quando alcuni monaci
pensano di lasciare l’abito e dicono: « Coltivare il riso non mi pare
difficile. Sarebbe meglio essere un contadino. » Cominciano a fare i
contadini senza sapere nulla di bufali, erpici e aratri, nulla di nulla.
Scoprono che è facile parlare di coltivare il riso, ma è quando ci si
prova davvero che si apprendono esattamente quali sono le difficoltà. A
tutti piacerebbe cercare la pace in quel modo. In realtà, la pace è
proprio qui, ma non lo sapete ancora. Potete inseguirla, parlarne quanto
volete, ma non saprete cos’è.

Fatelo, allora. Praticate finché non ottenete la conoscenza seguendo il
ritmo del respiro, concentrandovi sul respiro con il mantra _Buddho_.
Tutto qui. Non lasciate che la mente vaghi altrove. In questo momento
abbiate questa consapevolezza. Fate questo. Studiate solo questo.
Continuate a farlo, a farlo in questo modo. Se iniziate a pensare che
non sta succedendo niente, proseguite comunque. Proseguite incuranti e
giungerete a conoscere il respiro. Bene, proviamo! Se vi sedete in
questo modo e la mente capisce come si fa, essa raggiungerà uno stato
ottimale, proprio quello giusto. Quando la mente è pacificata, la
consapevolezza di sé sorge naturalmente. Se allora vorrete sedere per
tutta la notte, non ci saranno problemi, perché la mente prova diletto
per se stessa. Quando arriverete a questo punto, quando sarete bravi a
farlo, potreste voler tenere degli interminabili discorsi di Dhamma per
i vostri amici. È così che succede a volte.

È come quando Por Sangfootnote:[Por Sang, un _bhikkhu_ che viveva in
monastero.] era ancora un postulante. Una notte aveva praticato la
meditazione _caṅkama_ e poi aveva cominciato con quella seduta. La sua
mente divenne lucida e acuta. Voleva spiegare il Dhamma. Non riusciva a
fermarsi. Avevo sentito che, oltre il boschetto di bambù, qualcuno stava
insegnando davvero a squarciagola. Pensai: « È qualcuno che tiene un
discorso di Dhamma oppure che protesta per qualcosa? » Non smetteva.
Presi perciò la mia torcia elettrica e andai a dare un’occhiata. Avevo
visto giusto. Nel boschetto di bambù, seduto a gambe incrociate alla
luce di una lanterna, c’era Por Sang che parlava tanto in fretta da non
potergli star dietro. Perciò l’ho chiamato e gli ho detto: « Por Sang,
sei diventato matto? » Mi ha risposto: « Non so cosa mi stia succedendo,
voglio solo esporre il Dhamma. Mi siedo e devo parlare, cammino e devo
parlare. Devo spiegare il Dhamma in continuazione. Non so davvero come
andrà a finire. » « Quando la gente pratica il Dhamma, può succedere di
tutto », ho pensato.

Continuate allora, non smettete. Non seguite i vostri umori. Andate
controcorrente. Praticate quando vi sentite pigri e praticate quando vi
sentite diligenti. Praticate quando siete seduti e praticate quando
camminate. Quando vi distendete, concentratevi sul respiro e dite a voi
stessi: « Non indulgerò al piacere di stare disteso. » Addestrate così
il vostro cuore. Alzatevi appena vi svegliate, e continuate a
impegnarvi. Mentre mangiate, dite a voi stessi: « Mangio questo cibo non
con bramosia, ma perché è una medicina, per sostentare il mio corpo per
un giorno e una notte, solo per poter continuare la mia pratica. »

Quando siete distesi, addestrate la vostra mente. Quando mangiate,
addestrate la vostra mente. Questo atteggiamento mantenetelo
continuamente. Se state per alzarvi, siatene consapevoli. Se state per
sdraiarvi, siatene consapevoli. Qualsiasi cosa facciate, siatene
consapevoli. Quando giacete, giacete sul lato destro e concentratevi sul
respiro, usando il mantra _Buddho_ finché vi addormentate. Quando poi vi
svegliate è come se _Buddho_ fosse stato sempre lì, senza interruzione.
Ci deve essere sempre consapevolezza per far sorgere la pace. Non
guardate gli altri. Non interessatevi degli affari altrui, occupatevi
dei vostri.

Quando praticate la meditazione seduta, sedete eretti; non inclinate la
testa troppo indietro o troppo avanti. Mantenete la “giusta” postura,
siate come un’immagine del Buddha. La vostra mente sarà allora luminosa
e chiara. Sopportate più a lungo che potete prima di cambiare postura.
Se vi fa male, lasciate che faccia male. Non vi affrettate a cambiare
posizione. Non pensate: « Oh! È troppo. Mi riposo. » Sopportate
pazientemente fino a quando il dolore raggiunge il culmine, e poi
sopportate ancora un po’. Sopportate, sopportate finché non riuscite più
a sostenere il mantra _Buddho_. Poi assumete il punto che vi duole come
oggetto della vostra meditazione. « Oh! Dolore. Dolore. Dolore
davvero. » Potete far diventare il dolore l’oggetto della vostra
meditazione al posto di _Buddho_. Concentratevi su di esso in
continuazione. Continuate a stare seduti. Quando il dolore ha raggiunto
il limite, state a vedere cosa succede.

Il Buddha disse che il dolore sorge da sé e svanisce da sé. Lasciatelo
morire, non arrendetevi. Qualche volta potrà succedervi che il sudore
prorompa. Gocce grandi, grandi come chicchi di granturco, che vi
scendono sul petto. Però, quando avrete attraversato una volta la
sensazione del dolore, allora saprete tutto su di esso. Continuate a
farlo. Non esagerate, però. Continuate solo a praticare con fermezza.

Siate consapevoli mentre mangiate. Masticate e deglutite. Dove va il
cibo? Sappiate quale cibo è adatto a voi e quale no. Cercate di
misurarne la quantità. Quando mangiate, osservate in continuazione e
quando pensate che dopo altri cinque bocconi sarete sazi, fermatevi,
bevete un po’ d’acqua e avrete mangiato la giusta quantità. Provate.
Vedete se riuscite a farlo o no. Di solito non è questo il modo in cui
ci comportiamo. Quando ci sentiamo sazi, mangiamo altri cinque bocconi.
È quello che la mente ci dice di fare. Non sa come insegnare a se
stessa. Il Buddha ci disse di continuare a osservare mentre mangiamo.
Fermatevi cinque bocconi prima di essere sazi e bevete un po’ d’acqua, e
sarà il giusto. Se dopo sedete o camminate, non vi sentirete pesanti. La
vostra meditazione migliorerà. Però non vogliamo farlo. Siamo pieni e
mangiamo altri cinque bocconi. Così sono la brama e le contaminazioni,
vanno in una direzione diversa rispetto agli insegnamenti del Buddha.
Chi manca di un genuino desiderio di addestrare la propria mente non
sarà in grado di farlo. Continuate a osservare la vostra mente.

Siate vigili con il sonno. Il vostro successo dipenderà dall’essere
consapevoli dei mezzi abili. L’ora in cui si va a dormire può variare.
Alcune sere andate a letto presto, altre tardi. Cercate di praticare
così: quale che sia l’ora in cui andate a dormire, dormite per un unico
e continuato lasso di tempo. Appena vi svegliate, alzatevi
immediatamente. Non rimettetevi a dormire. Sia che abbiate dormito molto
o solamente un po’, dormite per un unico e continuato lasso di tempo.
Decidete che, pure se non avete dormito abbastanza, vi alzerete appena
vi svegliate, vi laverete la faccia e comincerete con la meditazione
_caṅkama_ o con la meditazione seduta. Sappiate addestrare voi stessi in
questo modo. Non arriverete alla conoscenza ascoltando qualcun altro.
Conoscerete addestrando voi stessi, per mezzo della pratica, facendolo.
Ed è per questo che vi dico di praticare.

Questa pratica del cuore è difficile. Quando state facendo meditazione
seduta, fate in modo che la vostra mente abbia un solo oggetto di
meditazione. Fatela rimanere con l’inspirazione e l’espirazione e la
vostra mente si calmerà gradualmente. Se la vostra mente è agitata,
allora avrà molti oggetti. Ad esempio, pensate a casa vostra non appena
vi sedete? Alcuni pensano di mangiare spaghetti cinesi. I monaci che
sono stati ordinati da poco hanno fame, vero? Volete mangiare e bere.
Pensate a ogni sorta di cibo. La vostra mente impazzisce. Se è questo
che sta per succedere, lasciate che avvenga. Però, non appena lo avrete
superato, scomparirà.

Fatelo! Avete mai camminato _caṅkama_? Com’era mentre camminavate? La
vostra mente vagava? Se lo fa, allora fermatela e riportatela indietro.
Se vaga molto, allora non respirate. Trattenete il respiro fino a quando
i vostri polmoni stanno per scoppiare. Tornerà indietro da sé. Non
importa quanto male faccia, se sta correndo dappertutto qui e là,
trattenete il respiro. Quando i vostri polmoni staranno per scoppiare,
la vostra mente tornerà. Dovete infondere energia alla mente. Addestrare
la mente non è come addestrare gli animali. La mente è davvero difficile
da addestrare. Non scoraggiatevi con facilità. Se trattenete il respiro,
vi sarà impossibile pensare a qualsiasi cosa e la mente tornerà indietro
di corsa da sé.

È come l’acqua in questa bottiglia. Quando incliniamo lentamente la
bottiglia, allora l’acqua gocciola … plic … plic … plic. Se però la
incliniamo di più, l’acqua fuoriesce a getto continuo, non a gocce
separate come prima. Così è per la nostra consapevolezza. Se acceleriamo
i nostri sforzi e pratichiamo in modo uniforme e continuo, la
consapevolezza sarà ininterrotta come una corrente d’acqua. Non importa
se stiamo camminando, se siamo in piedi, seduti o distesi, quella
conoscenza è ininterrotta, fluisce come una corrente d’acqua.

Per la pratica è così. Il nostro cuore un momento pensa a questo e un
altro pensa a quello. È agitato, e la consapevolezza non è continua.
Però, qualsiasi cosa pensi, non preoccupatevene, continuate a sforzarvi
ulteriormente. Avverrà come per le gocce d’acqua che diventano più
frequenti, poi si uniscono e formano una corrente. Allora la nostra
conoscenza sarà comprensiva. In piedi, seduti, distesi o mentre
camminiamo, qualsiasi cosa stiate facendo, questa conoscenza vi
assisterà.

Iniziate adesso. Provate. Non andate di fretta, però. Se state seduti
solo per vedere quel che succede, sprecate il vostro tempo. Siate
accorti. Se provate troppo, non riuscirete. Se non provate affatto, non
riuscirete ugualmente.
