= I due volti della realtà

____
Discorso tenuto al Wat Pah Pong durante il Ritiro delle Piogge del 1976
per un’assemblea di monaci dopo la recitazione del Pāṭimokkha, il codice
di disciplina monastica.
____

Nella vita abbiamo due possibilità: indulgere al mondo o andare oltre il
mondo. Il Buddha fu in grado di liberarsi dal mondo e, così, realizzò la
Liberazione spirituale. Allo stesso modo, ci sono due generi di
conoscenza: la conoscenza del regno mondano e la conoscenza del regno
spirituale, o vera saggezza. Se non abbiamo ancora praticato e
addestrato noi stessi, non importa quanta conoscenza abbiamo, è pur
sempre una conoscenza mondana che, perciò, non può liberarci.

Pensateci e guardate davvero da vicino! Il Buddha disse che le cose del
mondo girano attorno al mondo. Seguendo il mondo, la mente è
intrappolata nel mondo, contamina se stessa qualsiasi cosa faccia, senza
essere mai soddisfatta. La gente del mondo cerca sempre qualcosa, senza
mai trovare abbastanza. In realtà, la conoscenza mondana è ignoranza.
Non è conoscenza con chiara comprensione e, perciò, non c’è mai un punto
d’arrivo definitivo. Gira intorno agli scopi mondani di accumulare cose,
di ottenere uno status sociale, di cercare elogi e piacere. È un ammasso
di illusioni che ci incastra.

Quando otteniamo qualcosa, c’è gelosia, preoccupazione ed egoismo. E
quando ci sentiamo minacciati e non riusciamo a proteggere quel che
abbiamo ottenuto, usiamo la mente per inventare ogni genere di congegni,
anche armi e perfino bombe nucleari solo per farci esplodere a vicenda.
Perché tutti questi problemi, tutte queste difficoltà? Questa è la
strada del mondo. Il Buddha disse che chi la segue gira intorno al mondo
senza mai raggiungere la fine.

Venite a praticare per la Liberazione! Non è facile vivere secondo la
vera saggezza, ma chiunque cerchi onestamente il Sentiero e il Frutto e
aspiri al Nibbāna sarà in grado di perseverare e di sopportare.
Sopportate di accontentarvi e di essere soddisfatti del poco. Mangiate
poco, dormite poco, parlate poco e vivete nella moderazione. Facendo
così si può porre fine alla mondanità. Fino a quando il seme della
mondanità non sarà sradicato, saremo sempre turbati e confusi, ci
troveremo all’interno di un ciclo senza fine. Continua a trascinarvi via
perfino quando avete ricevuto l’ordinazione monastica. Crea i vostri
modi di vedere, le vostre opinioni. Colora e adorna tutti i vostri
pensieri. È così.

La gente non capisce! Dice che otterrà cose prodotte nel mondo. Ha
sempre la speranza di portare a termine qualcosa. Proprio come un
ministro del governo, ansioso di iniziare con la nuova amministrazione.
Pensa di avere tutte le soluzioni, e così scarta ogni cosa della vecchia
amministrazione, dicendo: « Attenzione! Farò a modo mio. » Questo è
tutto quel che le persone fanno, spostano le cose da qui a là e da là a
qui, senza concludere mai nulla. Ci provano, ma senza ottenere alcun
risultato definitivo.

Non potrete mai fare qualcosa che piaccia a tutti. A uno piace un po’,
molto a un altro. C’è a chi piace corto e a chi piace lungo. Ad alcuni
piace salato e ad altri piccante. Mettere tutti insieme e d’accordo non
è possibile. Tutti noi vogliamo realizzare qualcosa nella vita, ma il
mondo, con tutte le sue complessità, rende per lo più impossibile che si
giunga a un vero compimento. Perfino il Buddha, nato con tutte le
possibilità di un nobile principe non trovò completezza nella vita
mondana.

== La trappola dei sensi

Il Buddha parlò del desiderio e delle sei cose tramite le quali esso
viene gratificato: vista, suoni, odori, sapori, sensazioni tattili e
oggetti mentali. Tutto è pervaso dal desiderio e dalla brama per la
felicità, per la sofferenza, per il bene, per il male e così via.

Vista … Non c’è vista che possa eguagliare quella di una donna. Non è
così? Una donna davvero attraente non vi fa venir voglia di guardare?
Una donna con un corpo davvero attraente arriva camminando: swing,
swang, swing, swang, swing, swang. Non potete fare a meno di guardare! E
a proposito dei suoni? Non c’è suono che vi afferri più della voce di
una donna. Vi trafigge il cuore! Lo stesso avviene con l’odore. La
fragranza di una donna è la più seducente di tutte. Non c’è odore che
possa eguagliare quello di una donna. Il sapore. Anche il sapore del
cibo più delizioso non può essere paragonato a quello di una donna. Lo
stesso avviene con il tatto. Quando accarezzate una donna siete
storditi, intossicati, vi gira la testa.

Nell’antica India c’era un maestro di formule magiche che veniva da
Taxila. Insegnava ai suoi discepoli tutto quel che sapeva di magie e
incantesimi. Quando il discepolo era ben addestrato e pronto a fare da
solo, prima che se ne andasse, l’ultima istruzione del maestro era
questa: « Ti ho insegnato tutto quello che so di formule magiche,
incantesimi e versi di protezione. Non devi temere creature né dai denti
affilati né con corna e nemmeno con grandi zanne. Sarai protetto da
tutte, posso assicurartelo. C’è una sola cosa contro la quale non posso
assicurarti alcuna protezione: le attrattive di una
donna.footnote:[Tradotto letteralmente: creature con corna soffici,
ossia i seni, sul loro petto.] Per questo non posso aiutarti. Non c’è
incantesimo che possa proteggerti a tale riguardo, dovrai badare a te
stesso. »

Gli oggetti mentali sorgono nella mente. Nascono dal desiderio: dal
desiderio per oggetti preziosi, dal desiderio di essere ricchi, e in
genere dall’inquieta ricerca di cose. Questo tipo di brama non è così
profonda e forte, non è sufficiente a farvi avere mancamenti o a farvi
perdere il controllo. È quando sorge il desiderio sessuale che perdete
l’equilibrio e il controllo di voi stessi. Potreste dimenticarvi anche
di chi vi ha cresciuto e allevato: i vostri genitori!

Il Buddha insegnò che gli oggetti dei sensi sono una trappola, la
trappola di Māra.footnote:[_Māra._ Letteralmente, “Colui che fa
morire”, divinità che cerca di indurre il Buddha e i meditanti alla
distrazione.] Māra deve essere inteso come una cosa nociva. La trappola
è qualcosa che ci lega, come un laccio. È la trappola di Māra, il laccio
di un cacciatore, e il cacciatore è Māra. Quando gli animali finiscono
nella trappola del cacciatore la situazione è difficile e dolorosa.
Saldamente trattenuti dalla trappola, attendono il suo proprietario.
Avete mai visto degli uccelli presi al laccio? Il laccio scatta e –
tracchete! – l’uccello viene preso per il collo! Una corda bella salda
lo tiene stretto. Ovunque l’uccello tenti di volare non riesce a
fuggire. Vola di qua e vola di là, ma è tenuto stretto mentre attende il
proprietario del laccio. Quando il cacciatore arriva, ecco qua:
l’uccello è preda della paura, ma non c’è scampo!

La trappola della vista, dei suoni, degli odori, dei sapori, del tatto e
degli oggetti mentali è uguale. Ci cattura e ci lega stretti. Se vi
attaccate ai sensi, siete come un pesce preso all’amo. Quando arriva il
pescatore potete dibattervi quanto volete, ma non riuscite a liberarvi.
Nei fatti, non è che siete catturati come un pesce, è più come succede a
una rana. Una rana ingoia l’amo, che le arriva fin nelle viscere, mentre
un pesce viene preso per la bocca. La stessa cosa avviene a tutti quelli
che sono attaccati ai sensi. Come un ubriaco il cui fegato è quasi
distrutto, ma non sa mai quando ha bevuto abbastanza. Continua a
indulgere e beve con noncuranza. È catturato e in seguito patirà per la
malattia con le sue dolorose conseguenze.

Un uomo arriva camminando sulla strada. È molto assetato per il viaggio
e brama di bere dell’acqua. Il proprietario dell’acqua gli dice: « Se
vuoi, puoi bere quest’acqua. Il colore è limpido, non ha odore e il
sapore è buono, ma se la bevi ti ammalerai. Devo dirtelo in anticipo, ti
farà ammalare fino a farti morire o quasi. » L’assetato non ascolta. Ha
sete, come succede a chi è stata vietata l’acqua per sette giorni dopo
un intervento chirurgico: piange per avere dell’acqua! Per chi è
assetato di piaceri sensoriali è la stessa cosa. Il Buddha insegnò che
sono velenosi. Vista, suoni, odori, sapori, tatto e oggetti mentali sono
velenosi, sono una trappola pericolosa. Però, l’uomo è assetato e non
ascolta. A causa della sua sete è in lacrime, piange: « Datemi
dell’acqua, non importa quanto saranno dolorose le conseguenze,
lasciatemi bere! » Così ne beve un sorso e la manda giù, trovandola
molto buona. Ne beve fino a essere pieno e s’ammala quasi fino a
morirne. Non aveva ascoltato a causa del suo prepotente desiderio. Così
succede a chi è catturato dai piaceri sensoriali. Beve quel che vede, i
suoni, gli odori, i sapori, le sensazioni tattili e gli oggetti mentali.
Sono tutti così deliziosi! Beve senza fermarsi e lì resta, saldamente
bloccato fino al giorno della morte.

== La via del mondo e la Liberazione

Alcuni muoiono, altri muoiono quasi. È così per chi resta bloccato nelle
vie del mondo. La saggezza mondana segue i sensi e gli oggetti dei
sensi. Per quanto saggia voglia essere, una persona così è saggia solo
in senso mondano. Non conta quanto attraente possa essere, è attraente
solo in senso mondano. Per quanta felicità ci sia, è solo felicità in
senso mondano. Non è la felicità della Liberazione. Tutto questo non vi
libererà dal mondo.

Siamo venuti a praticare come monaci per penetrare la vera saggezza, per
liberare noi stessi dall’attaccamento. Praticate per essere liberi
dall’attaccamento! Investigate il corpo, investigate tutto intorno a
voi, finché non ne avete abbastanza e siete stanchi di tutto, e allora
subentrerà il distacco. Il distacco, ovviamente, non sorge con facilità
perché non vedete ancora con chiarezza.

Arriviamo e riceviamo l’ordinazione monastica. Studiamo, leggiamo,
pratichiamo, meditiamo. Decidiamo di rendere la nostra mente risoluta,
ma è difficile a farsi. Decidiamo di fare una certa pratica, diciamo che
praticheremo in questo modo. Passano solo uno o due giorni, forse solo
poche ore, e lo dimentichiamo. Poi ce ne ricordiamo, cerchiamo di
rendere di nuovo stabile la nostra mente, e pensiamo: « Questa volta lo
farò bene! » Poco tempo dopo siamo di nuovo trasportati via da uno dei
nostri sensi e tutto crolla di nuovo, e così dobbiamo ricominciare
ancora una volta, da capo! È così. Come una diga mal costruita, la
nostra pratica è debole. Non siamo ancora in grado di capire e di
seguire una vera pratica. E va avanti così fino a quando arriviamo alla
vera saggezza. Appena ci addentriamo nella Verità, siamo liberi da
tutto. Resta solo la pace.

La nostra mente non è serena a causa delle nostre vecchie abitudini. Le
abbiamo ereditate dalle nostre azioni passate ed esse ci seguono, ci
piagano in continuazione. Combattiamo e cerchiamo una via d’uscita, ma
ci legano e ci trascinano indietro. Queste abitudini non dimenticano i
loro vecchi fondamenti. Sono aggrappate a tutte le vecchie cose che ci
sono familiari e che usiamo, ammiriamo e consumiamo. Ecco come viviamo.

Il sesso maschile e quello femminile: le donne danno problemi agli
uomini e gli uomini danno problemi alle donne. Sono opposti, ecco come
stanno le cose. Se gli uomini vivono assieme agli uomini, non ci sono
guai. Se le donne vivono assieme alle donne, non ci sono guai. Quando un
uomo vede una donna, il suo cuore batte come il pestello nel mortaio per
il riso: « deng, dang, deng, dang, deng, dang. » Che cos’è? Che cosa
sono queste forze? Vi spingono e vi risucchiano. Nessuno capisce che c’è
un prezzo da pagare! È la stessa cosa per tutto. Non importa quanto
duramente proviate a liberarvi, fino a quando non vedrete il valore
della Libertà e il dolore delle catene non sarete in grado di lasciar
andare. La gente di solito pratica solo sopportando le difficoltà,
osservando la disciplina, seguendo ciecamente la forma, ma non per
giungere alla Libertà, alla Liberazione. Dovete comprendere l’importanza
di lasciar andare i vostri desideri prima di poter davvero praticare.
Solo allora è possibile praticare davvero.

Tutto quello che fate, lo dovete fare con chiarezza e consapevolezza.
Quando vedrete con chiarezza, non ci sarà più alcun bisogno di
sopportare o di forzare voi stessi. Avete delle difficoltà e siete
gravati perché non avete tenuto conto di questo! La pace arriva quando
le cose sono fatte con completezza a livello del corpo e della mente.
Tutto quello che è lasciato incompiuto lascia un senso di scontentezza.
Queste cose vi preoccupano ovunque andiate. Si vuole portare tutto a
compimento, ma riuscirci è impossibile.

Un esempio. Ci sono dei commercianti che vengono regolarmente a
trovarmi. Dicono: « Quando avrò pagato tutti i miei debiti e tutto sarà
a posto, verrò a farmi ordinare monaco. » Parlano così, ma quand’è che
finiranno di pagare e che tutto sarà a posto? Non c’è una fine. Pagano i
loro debiti con un altro prestito, poi pagano anche quello e ne
contraggono di nuovo un altro. Un commerciante pensa che quando si
libererà dai debiti sarà felice, ma non c’è fine ai pagamenti. Questo è
il modo in cui la mondanità ci inganna. Giriamo sempre in tondo senza
capire quanto sia difficile la situazione nella quale ci troviamo.

== Pratica costante

Nella nostra pratica guardiamo solo la mente, in modo diretto. Tutte le
volte che la nostra pratica inizia ad allentarsi, lo vediamo e la
rinsaldiamo. Poi, poco dopo, succede di nuovo. È così che la mente vi
maltratta. Però, chi ha buona presenza mentale assume una posizione
stabile e costantemente si rinsalda, tornando indietro, addestrandosi,
praticando e coltivando se stesso. Chi ha scarsa consapevolezza va in
pezzi, si allontana e va fuori strada in continuazione. Non è fortemente
e saldamente radicato nella pratica. Così, è ripetutamente trascinato
via dai suoi desideri mondani: qualcosa lo trascina di qua,
qualcos’altro lo trascina di là. Vive seguendo i suoi capricci e i suoi
desideri, senza porre mai fine a questo ciclo mondano.

Venire per ricevere l’ordinazione monastica non è così facile. Dovete
prendere la decisione di rendere stabile la mente. Dovreste avere
fiducia nella pratica, abbastanza fiducia da continuare a praticare fino
a che non ne avete abbastanza sia di ciò che vi piace sia di ciò che non
vi piace, e vedere in accordo con la Verità. Di solito si è
insoddisfatti solo di quello che non ci piace, e se qualcosa ci piace
non siamo pronti a rinunciare. Dovete stancarvi sia di ciò che vi piace
sia di ciò che non vi piace, sia della vostra sofferenza sia della
vostra felicità.

Non capite che proprio questa è l’essenza del Dhamma! Il Dhamma del
Buddha è profondo e raffinato. Non è facile da comprendere. Se la vera
saggezza non è ancora sorta, non potete comprenderlo. Non guardate in
avanti e non guardate indietro. Quando sperimentate la felicità, pensate
che ci sarà solo felicità. Tutte le volte che c’è sofferenza, pensate
che ci sarà solo sofferenza. Non capite che ovunque c’è il grande, c’è
il piccolo, e ovunque c’è il piccolo, c’è il grande. Non vedete in
questo modo. Vedete solo un lato, e perciò non c’è fine. Per ogni cosa
due sono i lati, dovete vederli entrambi. Allora, quando sorge la
felicità, non vi perdete, e quando sorge la sofferenza, non vi perdete.
Quando sorge la felicità, non dimenticate la sofferenza, perché capite
che sono interdipendenti. Allo stesso modo, per tutti gli esseri il cibo
è benefico per il sostentamento del corpo. In realtà il cibo può però
essere anche nocivo, ad esempio quando causa problemi allo stomaco.
Quando vedete i vantaggi di qualcosa, dovete percepire anche gli
svantaggi, e viceversa. Quando provate odio e avversione, dovete
contemplare l’amore e la comprensione. In questo modo, sarete più
equilibrati e la vostra mente diverrà più stabile.

== La bandiera e il vento

Una volta ho letto un libro sullo zen. Nello zen, sapete, non si insegna
con molte spiegazioni. Se ad esempio un monaco si addormenta durante la
meditazione, arrivano con un bastone e – stack! – gli danno un colpo
sulla schiena. Quando il discepolo che ha sbagliato riceve il colpo,
mostra la sua gratitudine ringraziando il maestro. Nella pratica zen si
insegna a essere grati a tutte le sensazioni che danno un’opportunità
per lo sviluppo spirituale.

Un giorno dei monaci si riunirono per un incontro. Fuori dalla sala una
bandiera sventolava al vento. Tra due monaci sorse una disputa sulla
ragione per cui la bandiera stesse sventolando al vento. Uno sostenne
che era a causa del vento, mentre l’altro argomentò che era a causa
della bandiera. Così, per i loro modi di vedere limitati litigarono e
non riuscirono a raggiungere alcun accordo. Avrebbero discusso in questo
modo fino al giorno della morte. Il loro maestro ovviamente intervenne e
disse: « Nessuno di voi ha ragione. Il corretto modo di vedere è che non
c’è né la bandiera né il vento. »

Questa è la pratica, non avere nulla, non avere la bandiera e non avere
il vento. Se c’è la bandiera, allora c’è il vento. Se c’è il vento,
allora c’è la bandiera. Questo dovreste contemplarlo e rifletterci su a
fondo, finché non vedete in accordo con la Verità. Se ci penserete bene,
non resterà nulla. È vuoto, vacuo. Vuoto di bandiera e vuoto di vento.
Nella grande vacuità non c’è bandiera e non c’è vento. Non c’è nascita,
non c’è vecchiaia, non c’è malattia o morte. La nostra conoscenza
convenzionale di bandiera e vento è solo un concetto. In realtà non c’è
nulla. Questo è tutto! Ci sono solo vuote etichette, nient’altro.

Se pratichiamo in questo modo, arriveremo a vedere la completezza, e
tutti i nostri problemi avranno fine. Nella grande vacuità il Re della
Morte non vi troverà mai. Per la vecchiaia, la malattia e la morte non
c’è niente da inseguire. Quando vediamo e comprendiamo in accordo con la
Verità, ossia con Retta Comprensione, allora lì c’è solamente questa
grande vacuità. È qui che non c’è più “noi”, non c’è “loro”, non c’è
alcun sé.

== La foresta dei sensi

Il mondo, con le sue strade che non finiscono mai, va sempre avanti. Se
cerchiamo di capire tutto, questo ci condurrà solo al caos e alla
confusione. Ovviamente, se contempliamo il mondo con chiarezza, sorgerà
la vera saggezza. Il Buddha stesso era un esperto delle vie del mondo. A
causa della sua ampia conoscenza mondana era molto abile a esercitare un
influsso sugli altri e a guidarli. Mediante la trasformazione della sua
saggezza mondana penetrò la saggezza sovramondana e la raggiunse, e ciò
lo rese un essere davvero superiore.

Così, se lavoriamo con il suo insegnamento e rivolgiamo verso l’interno
la contemplazione, la nostra comprensione raggiunge un piano
completamente nuovo. Quando vediamo un oggetto, non c’è alcun oggetto.
Quando sentiamo un suono, non c’è alcun suono. Mentre annusiamo,
possiamo dire che non c’è alcun odore. Tutti i sensi sono attivi, ma
vuoti di alcunché di stabile. Sono solo le sensazioni a sorgere e
svanire. Se comprendiamo in accordo con questa realtà, i sensi cessano
di essere sostanziali. Sono solo sensazioni che vanno e vengono. In
verità non c’è nessuna “cosa”. Se non c’è nessuna cosa, non c’è alcun
“noi” e nessun “loro”. Se non c’è alcun “noi”, non c’è nulla che
“ci” appartenga. È in questo modo che la sofferenza è estinta. Se non
c’è nessuno a patire la sofferenza, chi è allora che soffre?

Quando la sofferenza sorge, ci attacchiamo alla sofferenza e perciò
dobbiamo soffrire davvero. Nello stesso modo, quando sorge la felicità,
ci attacchiamo alla felicità e di conseguenza sperimentiamo piacere.
L’attaccamento a queste sensazioni fa sorgere il concetto del “sé” o
“io”, e i pensieri di “noi” e “loro” si manifestano in
continuazione. Bah! È proprio qui che tutto comincia e ci porta via in
un ciclo senza fine. È per questo che siamo venuti a praticare la
meditazione e a vivere secondo il Dhamma. Lasciamo le nostre case per
venire a vivere nella foresta e assorbire la pace mentale che essa ci
dà. Siamo fuggiti per combattere con noi stessi, non per paura o per
evadere. Però, chi viene a vivere nella foresta si attacca a questo modo
di vivere, proprio come la gente che vive in città e si attacca alla
città. Alcuni perdono la loro via nella foresta, altri la perdono in
città.

Il Buddha lodò la vita nella foresta perché la solitudine fisica e
mentale che ci offre è adatta alla pratica per la Liberazione.
Ovviamente, Egli non voleva che diventassimo dipendenti dalla vita nella
foresta o che restassimo bloccati nella pace e nella tranquillità. Siamo
venuti a praticare affinché sorga la saggezza. Qui nella foresta
possiamo piantare e coltivare i semi della saggezza. Vivendo nella
confusione e nell’agitazione, per quei semi è difficile crescere, ma
quando abbiamo imparato a vivere nella foresta possiamo tornare in città
e combattere con essa e con tutti gli stimoli dei sensi che porta con
sé. Imparare a vivere nella foresta significa consentire alla saggezza
di crescere e svilupparsi. Questa saggezza la possiamo poi applicare
indipendentemente da dove andiamo.

Quando i nostri sensi vengono stimolati ci agitiamo, ed essi diventano i
nostri antagonisti. Diventano i nostri antagonisti perché veniamo ancora
ingannati, non abbiamo la necessaria saggezza per entrare in rapporto
con essi. In realtà i sensi sono i nostri maestri, ma a causa della
nostra ignoranza non la vediamo in questo modo. Quando vivevamo in città
non abbiamo mai pensato che i nostri sensi potessero insegnarci
qualcosa. Finché la vera saggezza non si manifesta, continuiamo a vedere
i sensi e i loro oggetti come nemici. Quando la vera saggezza sorge, i
sensi non sono più i nostri nemici, ma la porta d’ingresso della visione
profonda e della chiara comprensione.

Un buon esempio sono le galline selvatiche che vivono qui nella foresta.
Tutti noi sappiamo quanta paura abbiano degli esseri umani. Però,
siccome ho vissuto nella foresta, sono stato in grado sia di insegnare a
loro sia di imparare da loro. Una volta ho cominciato a spargere del
riso per farle mangiare. Inizialmente erano davvero spaventate e non si
avvicinavano al riso. Dopo molto tempo si abituarono e cominciarono
perfino ad aspettare che dessi loro il riso. Vedete, qui c’è qualcosa da
imparare. All’inizio pensavano che nel riso si nascondesse un pericolo,
che il riso fosse un loro nemico. In realtà non c’era alcun pericolo nel
riso, ma non sapevano che il riso fosse cibo e perciò avevano paura.
Quando alla fine videro che non c’era nulla di cui aver paura, vennero e
mangiarono senza alcun rischio.

Le galline imparano in questa maniera, naturalmente. Vivendo qui nella
foresta noi impariamo in modo simile. In precedenza pensavamo che i
nostri sensi fossero un problema e, siccome la nostra ignoranza non ce
li faceva usare in modo appropriato, essi ci causavano un sacco di guai.
Mediante l’esperienza della pratica ovviamente impariamo a vederli in
accordo con la Verità. Impariamo a usarli proprio come le galline
facevano uso del riso. Poi non li consideriamo più come contrapposti a
noi, e i nostri problemi scompaiono. Quando pensiamo, investighiamo e
comprendiamo in modo erroneo, queste cose ci appaiono come a noi
contrapposte. Però, appena iniziamo a investigare propriamente, quel che
sperimentiamo ci conduce alla saggezza e alla chiara comprensione,
proprio come sono giunte alla comprensione quelle galline. In questo
modo, possiamo dire che hanno praticato _vipassanā_. Conoscono in
accordo con la verità, è la loro visione profonda.

Nella nostra pratica, i nostri sensi sono gli strumenti che, se usati
rettamente, ci rendono in grado di illuminarci al Dhamma. È una cosa che
tutti i meditanti dovrebbero contemplare. Quando non vediamo con
chiarezza, siamo perpetuamente in conflitto. Perciò, mentre viviamo
nella quiete della foresta, continuiamo a sviluppare sensazioni sottili
e prepariamo il terreno per coltivare la saggezza. Non pensiate che sia
sufficiente raggiungere un po’ di pace mentale vivendo qui, nella quiete
della foresta. Non accontentatevi di questo! Ricordate che dobbiamo
coltivare i semi della saggezza e farli crescere. Quando la saggezza
maturerà e cominceremo a comprendere in accordo con la Verità, non
saremo più trascinati su e giù. Di solito, se abbiamo uno stato mentale
piacevole, ci comportiamo in un modo. Se ne abbiamo uno spiacevole, ci
comportiamo in un altro. Se ci piace qualcosa siamo su, ci dispiace
qualcosa e siamo giù. In questo modo siamo ancora in conflitto con i
nemici. Quando queste cose non si oppongono a noi, si stabilizzano e
bilanciano. Non ci sono più su e giù o alti e bassi. Comprendiamo le
cose del mondo e sappiamo che è il modo in cui sono. Si tratta solo di
“__dhamma__ mondani”.footnote:[_dhamma_ mondani. Le otto condizioni
mondane di guadagno e perdita, lode e biasimo, felicità e sofferenza,
fama e discredito.]

I “__dhamma__ mondani” si trasformano per diventare il “Sentiero”. I
“__dhamma__ mondani” hanno otto vie, il “Sentiero” ha otto
vie.footnote:[Nel _Glossario_, p. FIXME:pageref, si veda la voce Nobile
Ottuplice Sentiero.] Tutte le volte che i “__dhamma__ mondani”
esistono, ci deve essere anche il “Sentiero”. Quando viviamo con
chiarezza, tutte le nostre esperienze mondane diventano pratica del
“Nobile Ottuplice Sentiero”. Senza chiarezza, i “__dhamma__ mondani”
predominano e siamo distolti dal “Sentiero”. Quando sorge la Retta
Comprensione, la liberazione dalla sofferenza sta proprio qui, davanti a
noi. Non troverete la Liberazione correndo qui e là guardando altrove!
Perciò, non siate frettolosi e non cercate di forzare o accelerare la
vostra pratica. Fate la vostra meditazione con gentilezza e
gradualmente, passo dopo passo. Per quanto concerne la serenità, se
volete essere sereni, accettate di volerlo essere. Se la serenità non
arriva, accettate anche questo. Questa è la natura della mente. Dovete
trovare la pratica giusta per voi e attenervi a essa con perseveranza.

La saggezza forse non sorge! A proposito della mia pratica, ero solito
pensare che quando la saggezza non c’era, potevo forzarmi ad averla.
Però non funzionava, le cose restavano uguali. Dopo attenta riflessione,
vidi che non si possono contemplare le cose che non abbiamo. Qual è
allora la miglior cosa da fare? È meglio limitarsi a praticare con
equanimità. Se non c’è nulla che ci causa problemi, non c’è nulla cui
porre rimedio. Se non c’è problema, non dobbiamo cercare una soluzione.
Quando c’è un problema, è allora che dovete risolverlo, proprio lì. Non
c’è bisogno di andare a cercare nulla di speciale, vivete in modo
normale, ma conoscete la vostra mente! Vivete con consapevolezza,
comprendendo chiaramente. Siate attenti e accorti! Se non c’è nulla, va
bene. Quando qualcosa sorge, allora investigate e contemplate.

== Andare al centro

Provate a osservare un ragno. Un ragno tesse la sua tela in ogni recesso
adatto, e poi sta al centro, immobile e silenzioso. Più tardi, arriva
una mosca e atterra sulla tela. Non appena tocca e scuote la tela –
buppete! – il ragno si avventa e la avvolge col filo. La mette da parte
e torna di nuovo a raccogliersi silenziosamente al centro della tela. In
questo modo, osservare un ragno può far sorgere la saggezza. I nostri
sei sensi hanno la mente al centro, attorniata dall’occhio,
dall’orecchio, dal naso, dalla lingua e dal corpo. Quando uno dei sensi
viene stimolato, ad esempio una forma contatta l’occhio, essa raggiunge
e scuote la mente. La mente è ciò che conosce, che conosce la forma.
Solo questo è sufficiente per far sorgere la saggezza. È semplice.

Come un ragno nella sua tela, dovremmo vivere attenendoci a noi stessi.
Appena il ragno sente che un insetto è entrato in contatto con la tela,
lo afferra velocemente, lo lega e torna al centro. Non è diverso dalla
nostra mente. “Arrivare al centro” significa vivere consapevolmente
con chiara comprensione, sempre attenti e facendo ogni cosa con
esattezza e precisione: questo è il nostro centro. Per noi non c’è
davvero molto da fare, viviamo solo così, in modo accurato. Però, questo
non significa che viviamo distratti, pensando: « Non c’è bisogno di fare
la meditazione seduta o camminata! » E dimenticare così tutto la nostra
pratica. Non possiamo essere distratti! Dobbiamo restare attenti proprio
come il ragno che attende per ghermire gli insetti, il suo cibo.

Questo è tutto quello che dobbiamo conoscere: ci mettiamo a sedere e
contempliamo quel ragno. Basta solo questo e la saggezza può sorgere
spontaneamente. La nostra mente può essere paragonata al ragno, i nostri
stati e impressioni mentali possono essere paragonati ai vari insetti.
Questo è tutto quel che c’è da fare! I sensi avvolgono la mente e
costantemente la stimolano. Quando uno di essi entra in contatto con
qualcosa, all’istante quella cosa raggiunge la mente. La mente la
investiga ed esamina con accuratezza, dopo di che torna al centro. È
così che dimoriamo: attenti, agendo con precisione e sempre consapevoli,
comprendendo con saggezza. Solo questo, e la nostra pratica è completa.
Questo è un punto davvero importante! Non è che dobbiamo praticare la
meditazione seduta giorno e notte o la meditazione camminata per tutto
il giorno e per tutta la notte. Se questo è il nostro modo di intendere
la pratica, allora ce la rendiamo difficile da soli. Dovremmo fare quel
che possiamo, a seconda della nostra forza e della nostra energia,
facendo uso delle nostre capacità fisiche nella giusta misura.

È davvero importante conoscere bene la mente e gli altri sensi.
Conoscere come arrivano e come se ne vanno, come sorgono e come
svaniscono. Comprendetelo con accuratezza! Nel linguaggio del Dhamma
possiamo anche dire che come il ragno cattura i vari insetti, la mente
lega i sensi con _aniccā_-_dukkha_-_anattā_ (impermanenza,
insoddisfazione, non-sé). Dove possono andare? Li consideriamo come
cibo, queste cose le mettiamo da parte come nostro
nutrimento.footnote:[Nutrimento per la contemplazione, per alimentare la
saggezza.] È abbastanza. Non c’è altro da fare, questo è sufficiente! È
il nutrimento della nostra mente, il nutrimento di chi è consapevole e
comprende.

Se sapete che queste cose sono impermanenti, che sono legate alla
sofferenza e che nessuna di esse è identificabile con voi stessi,
seguirle significherebbe essere folli! Se non vedete con chiarezza in
questo modo, allora dovete soffrire. Quando osservate per bene, vedete
queste cose come davvero impermanenti e, benché possa sembrare che valga
la pena di seguirle, in realtà non è così. Perché le volete, se la loro
natura è dolore e sofferenza? Non sono nostre, non c’è alcun sé, non c’è
nulla che ci appartenga. Allora perché le andate a cercare? Tutti i
problemi finiscono proprio qui. Altrimenti dove riuscirete mai a farli
finire?

Basta dare una bella occhiata al ragno e poi rivolgerla verso l’interno,
applicandola a se stessi. Vedrete che tutto è uguale. Quando la mente ha
visto _aniccā_-_dukkha_-_anattā_, essa lascia andare e si rilassa. Non
si attacca più alla sofferenza o alla felicità. Questo è il nutrimento
per la mente di chi pratica e davvero addestra se stesso. Questo è
tutto, è così semplice! Non dovete andare a cercare da nessuna parte!
Così, non importa cosa stiate facendo, siete lì, non c’è bisogno di un
sacco di confusione e di problemi. In questo modo l’impulso e l’energia
della vostra pratica cresceranno e matureranno in continuazione.

== Una via d’uscita

Questa spinta della pratica ci conduce verso la libertà dal ciclo di
nascita e morte. Non siamo ancora sfuggiti a questo ciclo perché
continuiamo a insistere con la brama e con il desiderio. Non commettiamo
atti malsani o immorali, ma comportarsi così significa solo che stiamo
vivendo in accordo con il Dhamma della moralità. Come quando, ad
esempio, nei canti si chiede che tutti gli esseri non siano separati da
ciò che amano e a cui sono affezionati. Se ci pensate, è proprio
infantile. È la via della gente che ancora non riesce a lasciar andare.
Questa è la natura del desiderio degli esseri umani. Desiderio che le
cose siano diverse da quello che sono. Desiderio per la longevità, con
la speranza che non ci siano morte e malattia. Così le persone sperano e
desiderano. Quando dite alla gente che ogni desiderio non realizzato
causa sofferenza, gli date un colpo in testa. Che possono dire? Niente,
perché è la verità! State indicando proprio i loro desideri.

Quando parliamo di desideri, sappiamo che ognuno ne ha e che vuole
realizzarli, ma nessuno vuole fermarsi, nessuno vuole realmente una via
d’uscita. La nostra pratica deve perciò essere affinata pazientemente.
Coloro che praticano con saldezza, senza deviare o essere indolenti, che
hanno modi gentili e contenuti, e perseverano sempre con costanza,
conosceranno la Verità. Non importa cosa sorgerà, resteranno saldi e
incrollabili.
