= Pratica costante

____
Discorso tenuto per un gruppo di studenti universitari
che avevano ricevuto l’ordinazione monastica temporanea,
durante l’estate del 1978.
____

Qui al Wat Wana Potiyahn c’è sicuramente molta tranquillità, ma questo
non significa nulla se la nostra mente non è calma. Tutti i posti sono
tranquilli. Se alcuni sembrano fonte di distrazione è a causa della
nostra mente. Un posto tranquillo può comunque aiutarci a diventare
calmi, dandoci l’opportunità di addestrarci e, perciò, di entrare in
armonia con la sua tranquillità.

Dovreste tutti tener presente che questa pratica è difficile.
Addestrarsi in altre cose non è molto difficile, è facile, ma la mente
umana è difficile da addestrare. Il Buddha addestrò la sua mente. La
cosa importante è la mente. All’interno di questo sistema corpo-mente
tutto si incontra nella mente. Gli occhi, gli orecchi, il naso, la
lingua e il corpo ricevono le sensazioni e le inviano alla mente, che è
il supervisore di ogni altro organo sensoriale. Per questa ragione è
importante addestrare la mente. Se la mente è ben addestrata, tutti i
problemi finiscono. Se di problemi ce ne sono ancora, è perché la mente
non ha smesso di dubitare, non conosce in accordo con la Verità. Ecco
perché ci sono ancora problemi.

Prendete perciò atto che siete giunti qui del tutto pronti a praticare
il Dhamma. In piedi, camminando, seduti o distesi, ovunque vi troviate
avete a disposizione gli strumenti di cui necessitiamo per la pratica.
Sono lì, proprio come il Dhamma. Il Dhamma abbonda ovunque. Proprio qui,
nella terra o nell’acqua, ovunque, il Dhamma è sempre lì. Il Dhamma è
perfetto e completo, è la nostra pratica che non è ancora completa.

Il Buddha, perfettamente illuminato, insegnò quali sono i mezzi tramite
i quali tutti noi possiamo praticare e pervenire a conoscere il Dhamma.
Non è una gran cosa, è solo una piccola cosa, ma è giusta. Guardate i
capelli, per esempio. Se conosciamo anche una sola ciocca di capelli,
allora conosciamo tutte le ciocche, sia le nostre sia quelle degli
altri. Sappiamo che sono semplicemente “capelli”. Conoscendo una
ciocca di capelli, le conosciamo tutte. Oppure, prendete in
considerazione la gente. Se comprendiamo la vera natura dei fenomeni
condizionati in noi stessi, allora conosciamo pure tutte le altre
persone del mondo, perché la gente è tutta uguale. Così è il Dhamma. È
una piccola cosa, ma è grande. Comprendere la verità di un fenomeno
condizionato significa comprendere la verità di ognuno di essi. Quando
conosciamo la Verità così com’è, tutti i problemi sono finiti.

Nonostante questo, l’addestramento è difficile. Perché è difficile? È
difficile a causa della brama, _taṇhā_. Se non “volete”, allora non
praticate. Se però praticate spinti dal desiderio non vedrete il Dhamma.
Pensateci, tutti voi. Se non volete praticare, non potete praticare. Per
svolgere effettivamente la pratica, dovete prima voler praticare. Si
incontra il desiderio per fare un passo sia avanti sia indietro. Per
questo già molto tempo fa i praticanti hanno detto che questa pratica è
una cosa estremamente difficile. Non vedete il Dhamma a causa del
desiderio. Talvolta il desiderio è molto forte, volete vedere il Dhamma
immediatamente, ma il Dhamma non è la vostra mente, la vostra mente non
è ancora il Dhamma. Il Dhamma è una cosa e la mente un’altra. Non è che
tutto quello che vi piace è il Dhamma e che tutto quello che non vi
piace non lo è. Le cose non stanno così.

In realtà la nostra mente è solo un fenomeno condizionato della natura,
come un albero della foresta. Se volete un’asse o una trave, esse devono
pur provenire da un albero, ma un albero è ancora solo un albero. Non è
già un’asse o una trave. Prima che possa esserci realmente utile
dobbiamo prendere quell’albero e trasformarlo, segandolo, in assi o
travi. È lo stesso albero, ma è stato trasformato in qualcos’altro.
Intrinsecamente è solo un albero, un fenomeno condizionato della natura.
Però, nel suo stato grezzo non è molto utile a chi ha bisogno di
legname. Così è la nostra mente. È un fenomeno condizionato della
natura. Concepisce pensieri, discrimina il bello e il brutto, e così
via. Questa nostra mente deve essere ulteriormente addestrata. Non
possiamo lasciarla così com’è. È un fenomeno condizionato della natura!
Addestratela per comprendere che è un fenomeno condizionato della
natura. Miglioratene la natura, così che si adatti alle nostre
necessità, ossia al Dhamma. Il Dhamma è un qualcosa che deve essere
praticato e portato all’interno.

Se non praticate, non conoscerete. Francamente, non conoscerete il
Dhamma solo leggendo o studiando. Oppure, se lo conoscerete, si tratterà
di una conoscenza ancora imperfetta. La sputacchiera che sta qui, ad
esempio. Tutti sanno che è una sputacchiera, ma non conoscono del tutto
la sputacchiera. Perché non la conoscono del tutto? Se questa
sputacchiera la chiamassi “pentola”, che direste? Supponete che, tutte
le volte che ve la chiedo, dica: « Portatemi quella pentola, per favore.
» Ciò vi confonderebbe. Perché? Perché non conoscete del tutto la
sputacchiera. Altrimenti non ci sarebbero problemi. Prendereste
semplicemente quell’oggetto e me lo consegnereste, perché in realtà non
c’è nessuna sputacchiera. Capite? È una sputacchiera a causa di una
convenzione. Questa convenzione è accettata in tutta la nazione, e
perciò è una sputacchiera. Però, non c’è alcuna reale “sputacchiera”.
Se qualcuno vuole chiamarla pentola, può essere una pentola. Chiamatela
come vi pare. Si tratta di un concetto. Se conoscete completamente la
sputacchiera, anche se qualcuno la chiama pentola non c’è problema. In
qualsiasi modo gli altri la possano chiamare, restiamo imperturbati
perché non siamo ciechi rispetto alla sua vera natura. Così è chi
conosce il Dhamma.

Torniamo a noi. Supponete che ad esempio qualcuno vi dica: « Sei
pazzo! » Oppure: « Sei stupido. » Anche se non fosse vero, non vi
sentireste molto a vostro agio. Tutto diventa difficile a causa delle
nostre ambizioni di ottenere e di raggiungere qualcosa. A causa di
questi desideri di avere e di essere, siccome non conosciamo in accordo
con la Verità, non ci sentiamo appagati. Se conosciamo il Dhamma, se
siamo illuminati al Dhamma, spariranno l’avidità, l’avversione e
l’illusione. Quando comprendiamo il modo in cui sono le cose, non vi è
nulla su cui esse possano poggiarsi.

Perché la pratica è così difficile e ardua? A causa dei desideri. Appena
ci sediamo a meditare, vogliamo essere tranquilli. Se non volessimo
trovare la pace, non sederemmo, non praticheremmo. Appena ci sediamo
vogliamo che la pace sia subito lì, ma volere che la mente sia calma
induce confusione, e ci sentiamo irrequieti. Così vanno le cose. Perciò
il Buddha disse: « Non parlare spinto dal desiderio, non sedere spinto
dal desiderio, non camminare spinto dal desiderio. Qualsiasi cosa tu
faccia, non farla con desiderio. » Desiderio significa volere. Se non
volete fare una cosa, non la fate. Se la nostra pratica raggiunge questo
punto, possiamo scoraggiarci molto. Come facciamo a praticare? Appena ci
sediamo, nella mente c’è il desiderio.

È a causa di tutto questo che il corpo e la mente sono difficili da
osservare. Se non sono il sé e nemmeno appartengono al sé, allora a chi
appartengono? Siccome si tratta di una questione difficile da risolvere,
dobbiamo far affidamento sulla saggezza. Il Buddha disse che dobbiamo
praticare “lasciando andare”. Però, se lasciamo andare, allora non
pratichiamo, vero? Perché abbiamo lasciato andare.

Supponiamo d’essere andati a comprare alcune noci di cocco al mercato e
che, mentre le portiamo a casa, qualcuno ci chieda: « Perché hai
comprato quelle noci di cocco? » « Per mangiarle », rispondiamo.
« Intendi mangiare anche i gusci? » « No. » « Non ti credo. Se non
intendi mangiare anche i gusci, perché hai comprato anche quelli? »
Allora, che ne dite? Come rispondereste a quest’ultima domanda?
Pratichiamo con desiderio. Se non avessimo il desiderio di farlo, non
praticheremmo. Praticare con desiderio è _taṇhā_. Contemplare in questo
modo può far sorgere la saggezza, sappiatelo. Quelle noci di cocco, ad
esempio. Avete intenzione di mangiare anche i gusci? No, ovviamente.
Allora perché li avete presi? Perché per voi non è ancora venuto il
momento di gettarli via. Racchiudono il cocco. Se dopo aver mangiato il
cocco i gusci li gettate via, non c’è alcun problema.

La nostra pratica è così. Il Buddha disse: « Non agire per desiderio,
non parlare per desiderio, non mangiare per desiderio. » In piedi,
camminando, stando seduti o distesi, come che sia, non facciamolo con
desiderio. Significa farlo con distacco. È come comprare le noci di
cocco al mercato. Non abbiamo intenzione di mangiare i gusci, ma non è
ancora giunto il momento di gettarli via. In un primo momento li
teniamo. Così è la pratica.

Concetto (_sammuti_)footnote:[_sammuti._ Realtà convenzionale,
convenzione, verità relativa, supposizione.] e trascendenza
(_vimutti_)footnote:[_vimutti._ Liberazione, libertà dalle formazioni e
dalle convenzioni della mente.] coesistono, come per la noce di cocco.
La polpa e il guscio stanno insieme. Quando compriamo una noce di cocco
compriamo tutto insieme. Se qualcuno vuole accusarci di mangiare gusci
di noci di cocco è affar suo, noi sappiamo quello che stiamo facendo.

La saggezza è una cosa che ognuno di noi deve trovare da sé. Per vederla
non dobbiamo andare né veloci né lenti. Che cosa dovremmo fare? Andare
dove non c’è né velocità né lentezza. Andare veloci o andare lenti non è
la Via. Però, siamo tutti impazienti, andiamo di corsa. Appena
cominciamo ci precipitiamo verso la fine, non vogliamo restare indietro.
Vogliamo riuscire. Quando arriva il momento di fare meditazione, alcuni
esagerano. Accendono l’incenso, si prostrano e fanno un voto: « Fino a
quando questo incenso non brucerà completamente non mi alzerò, dovessi
svenire o morire non importa, morirò sedendo. » Dopo aver fatto il voto
cominciano la loro seduta di meditazione. Appena si mettono seduti gli
eserciti di __Māra__footnote:[_Māra._ Letteralmente, “Colui che fa
morire”, divinità che cerca di indurre il Buddha e i meditanti alla
distrazione.] li assalgono da ogni parte. Sono lì da qualche istante e
già pensano che l’incenso debba essersi consumato. Aprono gli occhi per
una sbirciatina: « Oh! Manca ancora un’eternità! » Stringono i denti e –
accaldati, turbati, agitati e confusi – siedono ancora per un po’.
Quando l’agitazione raggiunge il culmine, pensano: « Ormai si deve
essere consumato. » Sbirciano di nuovo. « Oh no! Nemmeno la metà! » Lo
fanno ancora due o tre volte, ma l’incenso non è ancora finito, e così
rinunciano, desistono dal meditare e, odiando se stessi, si mettono
seduti da un’altra parte. « Sono così stupido! Sono senza speranza! »
Stanno seduti e si odiano, sentendo di essere casi senza speranza. Così
fanno solo sorgere frustrazioni e impedimenti. Si chiama impedimento del
malanimo. Non possono rimproverare gli altri e, così, rimproverano se
stessi. Perché succedono queste cose? A causa del desiderio.

In realtà tutto ciò non è necessario. Concentrarsi significa
concentrarsi con distacco, non concentrarsi annodandosi per la tensione.
Forse nelle Scritture che raccontano la vita del Buddha abbiamo letto
che Egli sedette sotto l’albero della Bodhi e disse: « Fino a quando non
avrò raggiunto la suprema Illuminazione non mi alzerò da qui nemmeno se
il mio sangue dovesse prosciugarsi. » Dopo averlo letto nei libri
potreste pensare che volete provarci. Fare come il Buddha. Però non
avete considerato che la vostra automobile è solo una piccola auto.
Quella del Buddha era un’automobile potente davvero, poteva far tutto in
una sola volta. Con la vostra piccola, minuscola utilitaria, com’è
possibile farlo in una sola volta? Si tratta di una storia completamente
diversa.

Perché pensiamo in questo modo? Perché siamo esagerati. A volte andiamo
troppo lenti, altre volte troppo veloci. È difficile trovare un punto
d’equilibrio. Vi parlo per esperienza. In passato la mia pratica era
così. Praticare per andare oltre il volere. Se non vogliamo, possiamo
praticare? Ero bloccato lì. Però, praticare con desiderio è sofferenza.
Non sapevo che cosa fare, ero perplesso. Allora capii che la cosa
importante era praticare con costanza. Si deve praticare costantemente.
Diciamo che questa pratica è “costante in tutte le posture”.
Continuate a perfezionare la pratica, non lasciate che si trasformi in
un disastro. La pratica è una cosa, un disastro è un’altra.footnote:[Sia
in inglese che in italiano è impossibile rendere il gioco tra le parole
thailandesi _patibat_ (pratica: ปฏิบัติธร) e _wibut_ (disastro:
วิบัติ).] La maggior parte della gente fa disastri. Quando si sente
pigra non si preoccupa di praticare, pratica solo quando si sente piena
d’energia. Le cose tendono ad andare così.

Tutti voi ora chiedetevi: « È giusto? » Praticare quando ve la sentite,
non praticare quando non ve la sentite. È in accordo con il Dhamma? È
cosa retta? È in linea con gli insegnamenti? È questo che rende la
pratica non costante. Che ve la sentiate o meno, dovreste praticare lo
stesso: così insegnò il Buddha. La maggior parte della gente aspetta di
sentirsi dell’umore giusto per praticare. Quando non se la sente, non se
ne preoccupa. Questo è quello che riesce a fare. Si chiama “disastro”,
non pratica. Nella vera pratica, praticate sia che siate felici sia che
siate depressi; che sia difficile o che sia facile, praticate; praticate
se fa caldo o se fa freddo. È così che si deve fare. Nella vera pratica,
che si stia in piedi, si cammini, si stia seduti o distesi, dovete avere
l’intenzione di continuare a praticare con perseveranza, rendendo
costante la vostra _sati_.

All’inizio può sembrare che si debba stare in piedi e camminare per lo
stesso lasso di tempo, camminare e stare seduti per lo stesso lasso di
tempo, e stare seduti e distesi per lo stesso lasso di tempo. Ho
provato, ma non ci sono riuscito. Se un meditante intendesse rendere
tutte le posture uguali – in piedi, camminando, seduti e distesi – per
quanti giorni potrebbe riuscirci? In piedi per cinque minuti, seduti per
cinque minuti, distesi per cinque minuti. Non sono riuscito a farlo
molto a lungo. Perciò mi misi seduto e ci pensai su ancora un po’. « Che
significa tutto questo? In questo mondo la gente non può praticare
così! » Poi capii. « Oh, non è giusto, non può essere giusto perché è
impossibile farlo. In piedi, camminando, seduti, distesi … renderle
tutte quante costanti. Rendere le posture costanti nel modo in cui
spiegano i libri è impossibile. »

Invece farlo è possibile: la mente, prendete in considerazione solo la
mente. Questo si può fare per avere _sati_, rammemorazione,
_sampajañña_, consapevolezza di sé, e _paññā_, saggezza a tutto tondo. È
una cosa che vale davvero la pena di praticare. Ciò significa che quando
stiamo in piedi abbiamo _sati_, quando camminiamo abbiamo _sati_, quando
sediamo abbiamo _sati_ e quando siamo distesi abbiamo _sati_,
costantemente. Questo è possibile. Applichiamo consapevolezza nel nostro
stare in piedi, camminare, stare seduti e distesi, in tutte le posture.

Quando la mente è addestrata in questo modo, rammemorerà costantemente
_Buddho_, _Buddho_, _Buddho_ … questo è conoscere. Conoscere che cosa?
Conoscere sempre quel che è giusto e quel che è sbagliato. Sì, questo è
possibile. Questo significa iniziare a praticare davvero. Ossia in
piedi, camminando, seduti o distesi vi è continuamente _sati_. Poi si
dovrebbe capire a quali condizioni si dovrebbe rinunciare e quali
dovrebbero essere coltivate. Conoscere la felicità, conoscere
l’infelicità. Quando conoscerete la felicità e l’infelicità, la vostra
mente si assesterà nel punto in cui vi è libertà dalla felicità e
dall’infelicità. La felicità è la via dell’indulgenza,
_kāmasukhallikānuyogo_. L’infelicità è la via della tensione,
_attakilamathānuyogo_.footnote:[Questi sono i due estremi indicati come
strade errate nel Primo Discorso del Buddha, il _Dhammacakkappavattana
Sutta_. Sono di solito indicati con “indulgenza al piacere dei sensi”
e “auto-mortificazione”.] Se conosciamo questi due estremi, ci tiriamo
indietro. Sappiamo quando la mente inclina verso la felicità o
l’infelicità e ci tiriamo indietro, non le consentiamo di esporsi.
Abbiamo questo genere di consapevolezza, aderiamo all’Unico Sentiero, al
solo Dhamma. Aderiamo alla consapevolezza, non consentiamo alla mente di
seguire le sue inclinazioni.

La vostra pratica, però, non ha questa tendenza, o no? Voi seguite le
vostre inclinazioni. Seguire le vostre inclinazioni è facile, vero? Però
questa è una facilità che causa sofferenza, è come chi non vuole
prendersi il disturbo di lavorare. La prende alla leggera, ma quando
arriva il momento di mangiare non ha nulla. Così vanno le cose.

In passato ho combattuto con molti aspetti dell’insegnamento del Buddha,
ma non sono proprio riuscito a vincere. Oggi lo accetto. Accetto che i
numerosi insegnamenti del Buddha sono completamente giusti e perciò ho
preso questi insegnamenti e li ho utilizzati per addestrare sia me
stesso sia gli altri.

La pratica importante è _paṭipadā_.footnote:[_paṭipadā._ Strada, via,
sentiero; i mezzi per raggiungere lo scopo o la destinazione finale, il
Nibbāna.] Che cos’è _paṭipadā_? Semplicemente, si tratta di tutte le
nostre varie attività. Stare in piedi, camminare, stare seduti, distesi
e tutto il resto. Questa è _paṭipadā_ del corpo. Ora _paṭipadā_ della
mente. Durante la giornata, quante volte vi siete sentiti giù? Quante
volte vi siete sentiti su? Ci sono state sensazioni degne di nota?
Dovete conoscere voi stessi in questo modo. Dopo aver visto queste
sensazioni, riusciamo a lasciarle andare? Dobbiamo lavorare su ogni cosa
che ancora non riusciamo a lasciar andare. Quando vediamo che non
riusciamo ancora a lasciar andare qualche particolare sensazione,
dobbiamo prenderla ed esaminarla con saggezza. Ragionarci sopra.
Lavorarci sopra. Questo è praticare. Ad esempio, quando vi sentite
zelanti praticate e quando vi sentite pigri cercate di continuare a
praticare. Se non riuscite a continuare a “tutta velocità”, fatelo
almeno a mezza. Non trascorrete pigramente le giornate senza praticare.
Farlo condurrà al disastro, non è la via di un praticante.

Ho sentito alcune persone dire: « Oh, quest’anno sono stato davvero
male. » Ho chiesto: « Come mai? » « Sono stato sempre malato. Non ho
potuto praticare per niente. » Oh! Se non praticano quando la morte è
vicina, quando mai praticheranno? Pensate che praticheranno se si
sentono bene? No, si perdono solamente nella felicità. Nemmeno se stanno
soffrendo praticano, si perdono pure in questo. Non so proprio quando la
gente pensa di voler praticare! Riesce solo a vedere che è malata,
dolorante, quasi morta per la febbre. Bene, forza e coraggio, proprio
qui sta la pratica. Quando la gente è felice si monta la testa, diventa
superficiale e presuntuosa.

Dobbiamo coltivare la nostra pratica. Questo significa che dovete
praticare proprio allo stesso modo sia se siete felici sia se siete
infelici. Dovreste praticare se vi sentite bene e dovreste praticare
anche se siete malati. Ci sono quelli che pensano: « Quest’anno non ho
potuto praticare affatto, sono stato sempre malato. » Se questa gente si
sente bene, se ne va in giro cantando. Questo è pensare in modo errato,
non è retto pensiero. Questa è la ragione per cui i praticanti del
passato hanno tutti quanti mantenuto costante l’addestramento del cuore.
Se per il corpo le cose vanno male, lasciatele al corpo, non alla mente.

Dopo aver praticato per circa cinque anni, nella mia pratica ci fu un
momento in cui sentii che vivere con gli altri era un impedimento. Me ne
stavo seduto nella mia _kuṭī_ e cercavo di meditare, ma la gente
continuava ad arrivare per chiacchierare e mi disturbava. Me ne scappai
a vivere da solo. Pensavo di non poter praticare con tutta quella gente
che m’importunava. Ero stufo, e così me ne andai a vivere in piccolo
monastero abbandonato nella foresta, vicino a un villaggio. Me ne stavo
da solo, senza parlare con nessuno, perché non c’era nessuno con cui
parlare. Dopo essere stato lì una quindicina di giorni, sorse in me un
pensiero: « Hmm. Sarebbe bello avere qui con me un novizio o un
_pah-kao_.footnote:[_pah-kao._ Termine thailandese (ผ้าขาว; ปะขาว) per
_anāgārika_; letteralmente, “non cittadino”, ossia “senza casa” un
postulante che ha assunto gli Otto Precetti.] Potrebbe aiutarmi in
alcuni lavoretti. » Sapevo che questo pensiero sarebbe arrivato, ne ero
abbastanza sicuro, e arrivò! « Ehi! sei proprio un tipo strano! Dicevi
che eri stanco dei tuoi amici, stufo dei tuoi confratelli monaci e
novizi, e ora vuoi un novizio. Cos’è questa roba? » La mente rispose:
« No, è che voglio un buon novizio. » « Ecco! Dove sono tutte queste
brave persone, ne vedi qualcuna in giro? In tutto il monastero non c’era
una sola brava persona. Devi essere stata l’unica brava persona, per
dover scappare via in questo modo! » Dovete seguire la mente in questa
maniera, seguire il filo dei vostri pensieri fino a quando non capite.
« Hmm. Questo è il punto importante. Dov’è che si può trovare una brava
persona? Non c’è nessuna brava persona, la brava persona devi trovarla
dentro te stesso. Se sei buono dentro, allora ovunque andrai starai
bene. Sia che gli altri ti critichino sia che ti lodino, sarai sempre
buono. Se non sei buono, quando gli altri ti criticano ti arrabbi, e
quando ti lodano ti compiaci. »

Ci ho riflettuto su e da quel giorno, fino a ora, ho potuto constatare
che è vero. È dentro noi stessi che va trovata la bontà. Appena riuscii
a capirlo, quella sensazione di volere scappar via scomparve. In
seguito, tutte le volte che nacque quel desiderio, lo lasciai andare.
Quando nacque, ne fui consapevole e mantenni la mia consapevolezza su di
esso. Così ebbi un solido fondamento. Dovunque vivessi, se delle persone
mi biasimavano, qualsiasi cosa dicessero pensavo che la questione non
stava nel fatto che loro fossero buoni o cattivi. Bene e male dobbiamo
vederli dentro noi stessi. Il modo in cui le persone sono è affar loro.

Non state a pensare: « Oh, oggi fa troppo caldo » o « oggi fa troppo
freddo » e così via. Comunque sia, ogni giornata è solo così com’è. In
realtà state rimproverando il tempo a causa della vostra stessa
pigrizia. Dovete vedere il Dhamma dentro di voi, allora c’è un tipo di
pace più certo. In tutti voi che siete venuti anche solo per pochi
giorni qui a praticare sorgeranno molte cose. Possono sorgere anche
molte cose di cui non siete consapevoli. Ci sono alcuni modi giusti e
altri modi sbagliati di pensare, molte, molte cose. Per questo dico che
questa pratica è difficile.

Sebbene qualcuno di voi possa aver sperimentato un po’ di pace quando
siede in meditazione, che non si affretti a congratularsi con se stesso.
Allo stesso modo, se c’è un po’ di confusione, non si rimproveri. Se le
cose sembrano andar bene, non dilettatevi con esse, e, se non vanno
bene, non provate avversione per esse. Osservatele tutte quante,
semplicemente, osservate quel che avete. Osservate e basta, non
preoccupatevi di giudicare. Se è bene, non tenetelo stretto; se è male,
non vi ci attaccate. Sia il bene sia il male possono mordere, perciò non
tratteneteli.

La pratica consiste semplicemente nel sedersi, sedersi e osservare tutto
questo. Buon umore e cattivo umore vanno e vengono, com’è nella loro
natura. Non elogiate solo la vostra mente né condannatela, sappiate qual
è il momento giusto per queste cose. Quando è tempo di congratularsi,
congratulatevi, ma solo un poco, non esagerate. Proprio come quando si
insegna a un bambino, talvolta può essere necessario sculacciarlo un
po’. A volte nella nostra pratica può essere necessario punirsi, ma non
fatelo sempre. Se vi punite sempre, dopo qualche tempo abbandonerete la
pratica. Non potete però divertirvi e basta, e prenderla alla leggera.
Non è questo il modo di praticare. Pratichiamo in accordo con la Via di
Mezzo. Cos’è la Via di Mezzo? Questa Via di Mezzo è difficile da
percorrere, non potete fare affidamento sui vostri umori e sui vostri
desideri.

Non pensiate che praticare sia star solo seduti a occhi chiusi. Se la
pensate in questo modo, allora sbrigatevi a cambiar modo di pensare!
Praticare costantemente significa praticare in piedi, camminando, seduti
o distesi. Quando terminate la meditazione seduta, pensate di star solo
cambiando postura. Se riflettete in questo modo, avrete la pace. Ovunque
vi troverete, avrete sempre con voi questo atteggiamento nella pratica,
avrete con voi una costante consapevolezza.

Fra voi, quelli che seguono i loro stati mentali e passano tutto il
giorno lasciando che la mente vaghi dove vuole, vedranno che durante la
seduta di meditazione serale tutto quello che otterranno sarà il
“riflusso” dovuto a una giornata di pensiero senza meta. Non c’è il
fondamento della calma perché avete fatto raffreddare la vostra pratica
per tutto il giorno. Se praticate in questo modo, gradualmente la vostra
mente si allontanerà sempre di più dalla pratica. Quando chiedo ad
alcuni miei discepoli: « Come va la tua meditazione? » « Ora è tutto
finito », rispondono. Capite? Possono continuare per un mese o due, ma
dopo un anno è tutto finito.

Perché? Perché nella loro pratica non tengono conto di questo punto
essenziale. Quando hanno terminato la meditazione seduta, lasciano
andare il loro _samādhi_. Cominciano a sedere per periodi sempre più
brevi, fino a quando arrivano al punto di volersi alzare non appena
cominciano a stare seduti. Alla fine non siedono più. La stessa cosa
avviene con le prostrazioni di fronte all’immagine del Buddha.
All’inizio fanno lo sforzo di prostrarsi ogni sera prima di andare a
dormire, ma dopo un po’ la loro mente comincia a smarrirsi. Dopo poco
tempo non si preoccupano affatto di prostrarsi, fanno appena un cenno
col capo, fino a quando non è tutto finito. Gettano via del tutto la
pratica.

Capite perciò l’importanza di _sati_, praticate costantemente. La retta
pratica è la pratica costante. In piedi, camminando, stando seduti o
distesi, la pratica deve continuare. Questo significa che la pratica, la
meditazione, si fa con la mente, non con il corpo. Se le nostre menti
sono zelanti, coscienziose e ardenti, ci sarà consapevolezza. La cosa
importante è la mente. La mente sovrintende a tutto ciò che facciamo.

Se comprendiamo bene, pratichiamo bene. Se pratichiamo bene, non ci
perdiamo. Anche se facciamo solo un po’, va comunque bene. Ad esempio,
quando finite la meditazione seduta, ricordate a voi stessi che in
effetti non avete terminato di meditare, state semplicemente cambiando
postura. La vostra mente è ancora composta. In piedi, camminando, stando
seduti o distesi, _sati_ è con voi. Se avete questo tipo di
consapevolezza potete sostenere la vostra pratica interiore. Alla sera,
quando sedete di nuovo, la pratica continua senza interruzione. Il
vostro sforzo ininterrotto consente alla mente di conseguire la calma.

Questa si chiama pratica costante. Sia che parliamo sia che facciamo
altre cose, dovremmo cercare di praticare con continuità. Se la nostra
mente ha rammemorazione e consapevolezza di sé in continuazione, la
nostra pratica si svilupperà naturalmente, e gradualmente si unificherà.
La mente troverà pace, perché saprà quel che è giusto e quel che è
sbagliato. Vedrà cosa sta succedendo dentro di noi e realizzerà la pace.

Se intendiamo sviluppare _sīla_ o _samādhi_, dobbiamo prima avere
_paññā_. Alcuni pensano di sviluppare il contenimento morale per un
anno, il _samādhi_ l’anno dopo e la saggezza quello successivo. Pensano
che queste tre cose siano separate. Pensano che quest’anno svilupperanno
_sīla_, ma se la mente non ha stabilità (_samādhi_), come possono
riuscirci? Se non c’è comprensione, come possono farlo? Senza _samādhi_
o _paññā_, _sīla_ sarà sciatta. Infatti, questi tre fattori si
riuniscono nello stesso punto. Quando abbiamo _sīla_ abbiamo _samādhi_,
quando abbiamo _samādhi_ abbiamo _paññā_. Sono tutti una sola cosa, come
un mango. Che sia piccolo o del tutto cresciuto, è sempre un mango.
Quando è maturo è ancora lo stesso mango. Se pensiamo in questo modo,
con parole semplici, possiamo capirlo con maggior facilità. Non c’è
bisogno di imparare un sacco di cose, basta sapere questo, conoscere la
nostra pratica.

Quando si tratta di meditare, alcuni non ottengono ciò che vogliono e
così rinunciano, dicendo che non hanno ancora meriti sufficienti per
praticare la meditazione. Possono fare delle brutte cose, questo genere
di talento ce l’hanno, ma non lo hanno per fare buone cose. Rinunciano,
dicendo che non hanno un fondamento sufficientemente buono. Così è la
gente, si schiera dalla parte delle contaminazioni.

Ora che avete questa opportunità di praticare, per favore capite che,
difficile o facile che lo troviate, sviluppare il _samādhi_ dipende
completamente da voi, non dal _samādhi_. Se è difficile, è perché state
praticando male. Nella nostra pratica dobbiamo avere Retta Visione
(_sammā-diṭṭhi_). Se la nostra visione è retta, ogni altra cosa è retta.
Retta Visione, Retta Intenzione, Retta Parola, Retta Azione, Retto Modo
di Vivere, Retto Sforzo, Retta Consapevolezza, Retta Concentrazione: è
il Nobile Ottuplice Sentiero. Quando c’è Retta Visione, seguiranno tutti
gli altri fattori.

Qualsiasi cosa succeda, non lasciate che la vostra mente vada fuori
strada. Guardate dentro di voi e vedrete con chiarezza. Dal mio punto di
vista, per praticare in modo perfetto non c’è bisogno di leggere molti
libri. Prendete tutti i libri e metteteli sotto chiave. Leggete solo la
vostra mente. Siete stati tutti sepolti dai libri dal momento in cui
siete entrati a scuola. Ora che avete questa opportunità e tempo a
disposizione, penso che dovreste prendere i libri, metterli in un
armadio e chiuderli a chiave. Leggete solo la vostra mente.

Ogni volta che sorge qualcosa nella mente, che vi piaccia o meno, che vi
sembri giusta o sbagliata, tagliatela via con « questa non è una cosa
certa. » Qualsiasi cosa sorga, abbattetela: « non è certo, non è
certo. » Questa sola scure è sufficiente per abbattere ogni cosa. Tutto
è “non certo”.

Il prossimo mese lo trascorrerete in questo monastero della foresta:
dovreste fare molti progressi. Vedrete la Verità. Questo “non è certo”
è una cosa davvero importante. Sviluppa la saggezza. Più osserverete più
vedrete la “non certezza”. Dopo che avete tagliato qualcosa con “non
è certo”, può succedere che quel qualcosa vi giri attorno e che appaia
nuovamente. Sì, è davvero “non certo”. Qualsiasi cosa sorga
attaccateci sopra questa targhetta: “non certo”. Attaccateci sopra il
cartello “non certo”, e dopo un po’, quando arriva il suo turno di
affiorare di nuovo: « Ah, non è sicuro. » Insistete su questo punto.
Vedrete che si tratta di quel solito vecchio tipo che vi ha ingannato
per mesi, per anni, fin dal giorno della vostra nascita. È stato solo
lui a ingannarvi per tutto il tempo. Vedete questo e capite il modo in
cui le cose sono.

Quando la vostra pratica raggiungerà questo punto, non vi attaccherete
più alle sensazioni, perché sono tutte incerte. Lo avete notato? Può
succedere che vediate un orologio e pensiate: « Oh, è bello. » Lo
acquistate e, non molti giorni dopo, notate che vi annoia già. « Questa
penna è davvero bella », e così vi prendete il disturbo di comprarne
una. Non molti mesi dopo vi ha stancato. È così. Dov’è una qualche
certezza in queste cose? Se vediamo tutto come incerto, il valore delle
cose si dissolverà. Tutto diventerà insignificante. Perché dovremmo
aggrapparci a cose che non hanno valore? Le teniamo solo come terremmo
un vecchio straccio che usiamo per pulirci i piedi. Comprendiamo che
tutte le sensazioni hanno ugual valore perché hanno tutte la stessa
natura.

Quando comprendiamo le sensazioni comprendiamo il mondo. Il mondo è le
sensazioni e le sensazioni sono il mondo. Se non siamo ingannati dalle
sensazioni, non siamo ingannati dal mondo. La mente che vede questo avrà
un saldo fondamento di saggezza. Una mente così non avrà molti problemi.
Tutti i problemi che ha, li può risolvere. Quando non ci sono più
problemi, non ci sono più dubbi. Al loro posto sorge la pace. Questa è
chiamata “pratica”. Se pratichiamo davvero, è così che dev’essere.
