= Retto contenimento

Esercitate contenimento e cautela nei riguardi delle sei facoltà dei
sensi, dell’occhio che vede le forme, dell’orecchio che ode i suoni e
così via. È questo che si insegna, in continuazione e in numerosissimi
modi. Si torna sempre a questo. Però, a essere onesti con noi stessi,
siamo davvero consapevoli di quello che succede? Quando l’occhio vede
qualcosa, arriva il piacere? Investighiamo davvero? Se investigassimo,
sapremmo che è proprio questo piacere che causa la nascita della
sofferenza. L’avversione causa la nascita della sofferenza. Queste due
reazioni hanno in realtà lo stesso valore. Quando avvengono, possiamo
vederne i difetti. Se c’è piacere, è solo piacere. Se c’è avversione, è
solo avversione. Questo è il modo per domarli.

Noi, ad esempio, attribuiamo un’importanza particolare alla testa. In
questa società, fin da quando si nasce impariamo che la testa è una cosa
di estrema importanza. Se qualcuno la tocca o la colpisce, siamo pronti
a morire. Se a essere colpita è qualche altra parte del corpo, non è un
grande problema, ma alla testa attribuiamo un’importanza particolare, e
ci arrabbiamo proprio se qualcuno la colpisce.footnote:[In Thailandia
toccare la testa a una persona è di solito considerato un insulto; come
si vedrà appena più avanti, è però ritenuto di buon auspicio che a
toccarla sia un monaco molto stimato.] Con i sensi è la stessa cosa. I
rapporti sessuali eccitano la mente della gente, ma in verità non si
tratta di una cosa molto diversa dal mettersi un dito nel naso. Si
tratta di una cosa che ha per voi un significato particolare? Gli esseri
mondani hanno quest’attaccamento per quell’altro orifizio. Ha
un’importanza speciale sia per gli animali sia per gli esseri umani.
Quando si mettono un dito nel naso non si eccitano. Però, l’immagine di
quella cosa ci infiamma. Perché? È lì che c’è il divenire. Se non vi
attribuiamo una particolare importanza, allora è come mettersi un dito
nel naso. Qualsiasi cosa succeda lì dentro, non vi eccitate, tirate
fuori una pallina di muco e tutto finisce lì.

Quant’è lontano il vostro modo di pensare da una percezione di questo
genere? Questa è la verità ordinaria, naturale della questione. Se
vedete le cose in questo modo, non create alcun divenire, e senza
divenire non ci sarà nascita. Al riguardo non ci sarà felicità o
sofferenza, lì non giungerà il piacere. Non c’è alcun attaccamento
quando comprendiamo quello che è, quel posto lì. Però gli esseri mondani
lì vogliono metterci qualcosa. È quello che a loro piace. Vogliono darsi
da fare in quel posto sporco. Darsi da fare in un posto pulito non è
interessante, ma in quel posto si precipitano a darsi da fare. E non
devono nemmeno essere pagati per farlo! Per favore, prendete quel che vi
dico in considerazione. Si tratta solo di una realtà convenzionale che
blocca la gente. È un punto importante della nostra pratica. Se
contempliamo i fori e gli ingressi del nostro naso, degli orecchi e di
tutto il resto, possiamo vedere che sono uguali, solo orifizi pieni di
sostanze non pulite. Ce n’è forse uno pulito? Per questa ragione
dovremmo contemplare questa cosa secondo il Dhamma. Quello che c’è da
temere è proprio qui, da nessun’altra parte. È qui che noi esseri umani
ci giochiamo la mente.

Già solo questo è una causa, un punto basilare della pratica. Non penso
che sia necessario fare un sacco di domande a qualcuno o andare in giro
a chiedere. Però non investighiamo questo punto con cura. A volte vedo
dei monaci che se ne vanno camminando di qua e di là attraverso le varie
province della Thailandia, portandosi dietro il loro grande _glot_ sotto
il sole cocente. Quando li osservo, penso: « Deve essere proprio
faticoso. » « Dove stai andando? » « Cerco la pace. » Non so che cosa
rispondere. Non li sto sminuendo, anch’io ero così. Cercavo la pace,
pensavo in continuazione che dovesse trovarsi in qualche altro posto.
Bene, in un certo senso era vero. Quando raggiungevo uno di quei posti,
mi sentivo un po’ a mio agio. Sembra che la gente debba essere così.
Pensiamo sempre che qualche altro posto sia comodo e sereno.

Durante un mio viaggio vidi il cane della famiglia
Pabhākaro.footnote:[Ajahn Chah si riferisce al suo viaggio in
Inghilterra, Francia e Stati Uniti del 1979.] Avevano un grosso cane.
Gli volevano bene davvero. Per la maggior parte del tempo lo facevano
stare fuori. Gli davano da mangiare fuori e dormiva pure fuori, ma a
volte voleva entrare in casa, e così grattava con le zampe la porta e
abbaiava. Ciò infastidiva il padrone, che perciò lo lasciava entrare e
chiudeva la porta. Il cane andava in giro per casa per un po’, e poi si
annoiava e voleva uscire di nuovo. Tornava presso la porta, la grattava
e abbaiava. Il padrone doveva alzarsi e lasciarlo andare fuori. Per un
po’ era contento di star fuori, ma dopo voleva rientrare in casa, e
abbaiava un’altra volta. Quando stava fuori, era come se dentro si
stesse meglio. Stare dentro era divertente, ma per poco, poi si annoiava
e doveva uscire. La mente della gente è così, come un cane. Sta sempre a
fare dentro e fuori, un po’ qui e un po’ lì, senza capire davvero dove
sia il posto nel quale sarà felice.

Se ne siamo un po’ consapevoli, allora quali che siano i pensieri e le
sensazioni che sorgono nella nostra mente, ci sforzeremo di sedarli,
riconoscendo che si tratta solo di pensieri e di sensazioni.
L’attaccamento, l’aggrapparsi a essi è veramente ciò che fa la
differenza. Perciò, anche se viviamo in un monastero siamo ancora
lontani dalla pratica corretta, molto lontani. Quando sono stato
all’estero ho visto molte cose. La prima volta ne ho ricavato un po’ di
saggezza in un senso, la seconda volta in un altro. Durante il mio primo
viaggio ho annotato le mie esperienze in un diario. La seconda volta,
però, ho messo giù la penna. Ho pensato: « Se scrivo queste cose, la
gente quando tornerò a casa sarà in grado di accettarle? »

Quando viviamo nel nostro paese è come se non ci sentissimo molto a
nostro agio. Quando i thailandesi vanno all’estero, siccome sono
riusciti ad arrivarci, pensano di avere un kamma davvero buono. Però,
quando andate in un posto che vi è estraneo, dovete considerare se
sarete in grado o meno di competere con chi lì ci è stato per tutta la
vita. Inoltre, stiamo lì per un po’ e pensiamo che sia meraviglioso,
pensiamo di essere delle persone che hanno proprio un buon kamma. I
monaci stranieri è lì che sono nati: questo significa forse che hanno un
kamma migliore del nostro? Questo genere di idee della gente proviene
dal loro attaccamento, dall’aggrapparsi. Significa che quando la gente
entra in contatto con le cose, si eccita. Alla gente piace essere
eccitata. Però, quando la mente è eccitata non è in uno stato normale.
Quando vediamo cose che non abbiamo mai visto e sperimentiamo cose di
cui non abbiamo mai avuto esperienza, sopraggiunge uno stato mentale
anomalo. Se si tratta di conoscenze scientifiche, d’accordo. Ma per
quanto concerne la conoscenza buddhista, ho ancora qualcosa da dire a
questi stranieri. Però, in relazione alla scienza e allo sviluppo
materiale, con loro non possiamo competere.

In concreto, alcuni hanno un sacco di sofferenze e di difficoltà, ma
continuano ad andare avanti su quella stessa strada che li fa soffrire.
Sono persone che non hanno deciso di mettersi a praticare per arrivare
alla fine della sofferenza, sono persone che non vedono con chiarezza.
La loro pratica non è salda e costante. Quando sopraggiungono sensazioni
belle o brutte, non sono consapevoli di quel che sta avvenendo. « Tutto
quello che è sgradevole, lo rifiuto. » Si tratta della stessa strada
presuntuosa percorsa dal brāhmaṇo. « Tutto quel che mi piace, lo
accetto. » Ad esempio, con alcuni è molto facile andare d’accordo se con
loro si parla in modo gradevole. Se però si dicono cose che a loro non
piacciono, andare d’accordo non è più possibile. Si tratta di
presunzione estrema (_diṭṭhi_). Hanno un forte attaccamento, ma pensano
che si tratti di un modo di vivere giusto. Infatti, coloro che
percorrono il Sentiero sono pochi. Per noi che viviamo qui le cose non
vanno diversamente. Sono davvero pochi quelli che hanno Retta Visione.
Quando contempliamo il Dhamma, sentiamo che non è giusto. Non siamo
d’accordo. Se fossimo d’accordo e pensassimo che è giusto, rinunceremmo
e lasceremmo andare le cose. A volte non siamo d’accordo con gli
insegnamenti. Vediamo le cose in modo differente, vogliamo cambiare il
Dhamma affinché sia diverso da quel che è. Vogliamo correggere il
Dhamma, e continuiamo a lavorarci su.

Questo viaggio mi ha fatto riflettere su molte cose. Ho incontrato delle
persone che praticavano yoga. Era indubbiamente interessante vedere
tutte le varie posture che erano in grado di assumere. Se ci provassi io
mi romperei le gambe. Come che sia, pensavano che le loro giunture e la
loro muscolatura non fossero a posto, e così dovevano distenderle.
Dovevano farlo tutti i giorni, così si sentivano bene. In realtà pensavo
che in questo modo stessero infliggendo delle sofferenze a se stessi. Se
non lo facevano, non si sentivano bene, e così lo facevano tutti i
giorni. Mi sembrava che in questo modo si stessero accollando un
fardello di cui non erano veramente consapevoli. La gente è così, prende
l’abitudine di fare qualcosa. Ho incontrato un cinese. Da quattro o
cinque anni non dormiva disteso. Dormiva seduto, e diceva che così stava
comodo. Faceva il bagno una volta l’anno. Però il suo corpo era forte e
sano. Non aveva bisogno di correre né di fare altri esercizi di questo
genere. Se li avesse fatti probabilmente non si sarebbe sentito bene. È
perché lui si addestrava in quel modo. È solo il nostro modo di
addestrarci che ci fa sentire a nostro agio con alcune cose. Possiamo
aumentare e diminuire le malattie per mezzo dell’addestramento. Così è
anche per noi. È per questo che il Buddha ci insegnò a essere del tutto
consapevoli di noi stessi: questa cosa non lasciatevela scappare. Tutti
voi, non dovete avere attaccamenti. Non lasciatevi eccitare dalle cose.

Ad esempio, vivendo qui, nella nazione in cui siamo nati, in compagnia
degli amici e dei maestri spirituali, ci sentiamo a nostro agio. In
verità non c’è nulla per cui sentirsi a proprio agio. È come un piccolo
pesce che vive in un grande stagno. Nuota agevolmente. Un pesce grande,
se lo mettiamo in uno stagno piccolo, si sente limitato. Quando viviamo
qui, nella nostra nazione, ci sentiamo a nostro agio per il cibo, per le
nostre dimore e per molte altre cose. Se andiamo da qualche altra parte
non è così, siamo come un grande pesce in uno stagno piccolo. Qui in
Thailandia abbiamo la nostra cultura e siamo soddisfatti quando tutti
rispettano le nostre usanze. Non siamo contenti quando qualcuno viene
qui e viola le nostre usanze. Adesso siamo come piccoli pesci in un
grande stagno. Se un pesce grande deve vivere in uno stagno piccolo,
come starà? Lo stesso avviene per quelli che nascono in altre nazioni.
Quando si trovano nella loro terra e tutto risulta familiare, si sentono
a loro agio in quelle circostanze: un piccolo pesce in un grande stagno.
Quando vengono in Thailandia, per loro può essere opprimente adattarsi a
condizioni e usanze diverse: come per un pesce grande in uno stagno
piccolo. Mangiare, andarsene in giro, tutto è diverso. Il pesce grande è
in uno stagno piccolo ora, e non può più nuotare liberamente.

Così differiscono le abitudini e gli attaccamenti degli esseri umani.
Uno resta bloccato a destra, un altro a sinistra. Perciò, la cosa
migliore che possiamo fare è essere consapevoli. Essere consapevoli
delle usanze nei differenti posti in cui ci rechiamo. Se abbiamo
l’usanza del Dhamma, saremo in grado di adattarci alle consuetudini
sociali, sia all’estero sia a casa. Se non comprendiamo l’usanza del
Dhamma, non c’è modo di andare d’accordo. L’usanza del Dhamma è il punto
in cui si incontrano tutte le culture e tutte le tradizioni. Ricordo le
parole del Buddha che dicono: « Quando non capite la loro lingua, quando
non capite il loro modo di parlare, quando nella loro terra non capite
il loro modo di fare le cose, non dovreste inorgoglirvi né darvi delle
arie. » Queste parole posso confermarle: sono una regola valida sempre e
ovunque. Mi tornarono in mente quando viaggiavo all’estero, e le ho
messe in pratica in questi ultimi due anni allorché mi sono trovato
fuori dal nostro paese. Sono utili.

Prima le cose le tenevo strette. Ora le tengo, ma non strette. Una cosa
la prendo, la guardo, e poi la lascio andare. Prima le cose le prendevo
e le trattenevo. Era un tenerle strettamente. Ora il tenerle c’è, ma non
strettamente. È per questa ragione che potete consentirmi di parlarvi
con durezza e di arrabbiarmi con voi, perché « ora il tenerle c’è, ma
non strettamente », prendere e lasciar andare. Per favore, non
dimenticatevene. Possiamo essere davvero felici e a nostro agio se
comprendiamo il Dhamma del Buddha. È per questo che lodo in
continuazione gli insegnamenti del Buddha e pratico per riunire i due
modi di essere, quello del mondo e quello del Dhamma.

Durante questo viaggio sono riuscito a comprendere alcune cose che mi
piacerebbe condividere con voi. Sentivo che stavo per essere di
giovamento, di giovamento per me stesso, per gli altri e per il
_sāsana_, di giovamento per tutta la gente e per il nostro Saṅgha, per
ognuno di voi. Non sono partito per fare un giro turistico, per visitare
altri paesi spinto dalla curiosità. Sono partito con un buon proposito,
per me stesso e per gli altri, per questa vita e per la prossima: un
proposito supremo. Quando si arriva a questo, tutti sono uguali. Chi
avrà saggezza vedrà le cose in questo modo. Chi ha saggezza viaggia
sempre su buoni sentieri, trova un significato quando va e quando viene.
Vi offrirò una similitudine. Potreste andare da qualche parte e
incontrare gente cattiva. Quando ciò avviene, alcuni proveranno
avversione per questa gente. Chi ha il Dhamma si troverà però di fronte
alla cattiva gente e penserà: « Ho trovato il mio maestro. » Grazie a
lui si può conoscere che cosa sia una brava persona. Incontrando una
brava persona si incontra anche un maestro, perché questo ci mostra chi
è una cattiva persona. Vedere una casa bella è una cosa buona, perché
allora si può capire com’è una casa brutta. Vedere una casa brutta è una
cosa buona, perché allora si può capire com’è una bella casa. Con il
Dhamma non scartiamo nessuna esperienza, neanche la più piccola.

Per questo il Buddha disse: « _Bhikkhu_, guardate questo mondo come a un
cocchio reale ornato e ingioiellato che affascina gli sciocchi, ma che è
privo di significato per i saggi. » Quando stavo studiando per il __Nak
Tham Ehk__footnote:[_Nak Tham Ehk_ (นักธรรมเอก). In Thailandia è il
terzo e più alto livello degli esami in Dhamma e Vinaya.] contemplavo
spesso questa frase. Mi sembrava proprio significativa. Fu però quando
iniziai a praticare che il senso di essa mi divenne chiaro.
“__Bhikkhu__” significa tutti noi che siamo qui seduti. “Guardate
questo mondo” si riferisce al mondo degli esseri umani, l’_ākāsaloka_,
i mondi di tutti gli esseri senzienti, tutti i mondi esistenti. Se si
conosce il mondo con chiarezza, non è necessario praticare alcun tipo
speciale di meditazione. Se si sa che “il mondo è così” secondo
realtà, non mancherà nulla. Il Buddha conosceva il mondo con chiarezza.
Conosceva il mondo per quello che è in realtà. Conoscere il mondo con
chiarezza significa conoscere il Dhamma sottile. Non ci si preoccupa né
si è ansiosi in relazione al mondo. Se si conosce il mondo con
chiarezza, allora non ci sono _dhamma_ mondani.footnote:[_dhamma_
mondani. Le otto condizioni mondane di guadagno e perdita, lode e
biasimo, felicità e sofferenza, fama e discredito.] I _dhamma_ mondani
non esercitano più alcun influsso su di noi.

Gli esseri mondani sono governati dai _dhamma_ mondani, e sono sempre in
una condizione conflittuale. Perciò, qualsiasi cosa vediamo e
incontriamo sul nostro cammino, dovremmo contemplare con cura. Proviamo
piacere per le immagini, per i suoni, per gli odori, per i sapori, per
le sensazioni tattili e per i pensieri. Per favore, contemplate. Tutti
voi sapete cosa sono queste cose. Ad esempio le forme che l’occhio vede,
le forme degli uomini e delle donne. Sicuramente sapete cosa sono i
suoni, come pure gli odori, i sapori e i contatti fisici. Poi ci sono le
impressioni mentali e i pensieri. Quando sperimentiamo questi contatti
per mezzo dei sensi, sorge l’attività mentale. Tutte le cose si
riuniscono qui. Potremmo camminare insieme al Dhamma per un anno intero
o per tutta la vita senza riconoscerlo. Viviamo con il Dhamma per tutta
la vita senza conoscerlo. I nostri pensieri vanno troppo lontano.
Miriamo troppo in alto, abbiamo troppi desideri. Ad esempio un uomo vede
una donna, oppure una donna vede un uomo. Si tratta di una cosa alla
quale sono tutti estremamente interessati. È perché la sovrastimiamo.
Quando vediamo un attraente rappresentante dell’altro sesso, tutti i
nostri sensi si risvegliano. Vogliamo vedere, ascoltare, toccare,
osservare i suoi movimenti, ogni cosa. Se però ci sposiamo, allora non è
più una cosa così importante. Dopo un po’ possiamo anche desiderare la
lontananza, forse perfino di andare a ricevere l’ordinazione monastica!
Poi però non lo facciamo.

È come un cacciatore che insegue un capriolo. Appena lo vede è eccitato.
È interessato a tutto, agli orecchi, alla coda, a tutto. Il cacciatore è
proprio felice. Il suo corpo è vigile e leggero. Teme solo che il
capriolo possa fuggire. È la stessa cosa. Appena un uomo vede una donna
che gli piace, o una donna vede un uomo, è tutto così affascinante, la
sua immagine, la voce: ci fissiamo, non riusciamo a staccarci, guardiamo
e pensiamo a più non posso, fino al punto che perdiamo il controllo del
nostro cuore. Proprio come succede al cacciatore. Quando vede il
capriolo, si eccita. È ansioso di vederlo. Tutti i suoi sensi sono
attivi, ne ricava un piacere estremo. La sua unica preoccupazione è che
il capriolo possa fuggire. Cosa sia in realtà quel capriolo, non lo sa.
Lo caccia e alla fine spara, e lo uccide. Il lavoro è fatto. Arriva nel
posto in cui il capriolo è caduto, e lo guarda: « Oh, è morto. » Non è
che sia più tanto eccitato, ora si tratta solo di un pezzo di carne
morta. Può cucinarne un po’ e mangiarla, poi si sentirà sazio, nulla di
più. Ora vede le varie parti del capriolo, ma esse non lo eccitano più
così tanto. L’orecchio è solo un orecchio. Può tirargli la coda, ma è
solo una coda. Quando era vivo, però, ragazzi! Era diverso, allora.
Vedeva il capriolo, osservava ogni suo movimento, era così avvincente ed
eccitante che non poteva tollerare il pensiero che fuggisse. Noi siamo
così, vero? Così succede per la forma di una persona attraente del sesso
opposto. Fino a quando non l’abbiamo catturata, sentiamo che è
insopportabilmente bella. Se però finiamo per viverci insieme, ce ne
stanchiamo. Come il cacciatore che ha ucciso il capriolo e può toccargli
liberamente l’orecchio o tirargli la coda. Adesso non è più come prima,
una volta che l’animale è morto, l’eccitazione svanisce. Quando siamo
sposati possiamo esaudire i nostri desideri, ma non è più una cosa così
importante, e finiamo per andare alla ricerca di una via d’uscita.

Non esaminiamo veramente le cose a fondo. Penso che se contemplassimo,
vedremmo che non si tratta di cose tanto importanti, nulla di più di
come ve le ho appena descritte. È solo che ingigantiamo le cose. Quando
vediamo un corpo, sentiamo che saremmo capaci di consumarne ogni parte,
gli orecchi, gli occhi, il naso. I nostri pensieri corrono
all’impazzata, potremmo perfino farci l’idea che la persona da cui siamo
attratti non abbia delle feci dentro di sé. Non so, forse in Occidente è
così che pensano. Ci facciamo l’idea che non ci siano delle feci lì
dentro, o forse solo poche. Quella persona ce la mangeremmo tutta
quanta. Sopravvalutiamo, ma non è così. È come un gatto che insegue un
topo. Prima di catturarlo, è attento e concentrato. Quando gli si
avventa contro e lo uccide, non è più così attento. Il topo giace lì,
morto, e il gatto perde ogni interesse e se ne va per la sua strada. È
tutto qui. L’immaginazione rende le cose più grandi di quel che sono. È
qui che si muore, a causa della nostra immaginazione. Chi ha ricevuto
l’ordinazione monastica deve astenersi più degli altri, qui, nel regno
della sensorialità. _Kāma_ significa concupiscenza. Desiderare cose
cattive e desiderarne di buone è un tipo di concupiscenza, ma qui mi
riferisco al desiderio per quelle cose che ci attraggono, significa
sensualità. È difficile liberarsene.

Quando Ānanda chiese al Buddha: « Dopo che il _Tathāgata_ è entrato nel
Nibbāna, come dovremmo praticare la consapevolezza? Come dovremmo
comportarci in relazione alle donne? È un problema estremamente
difficile. In questo caso il Beato come ci consiglierebbe di praticare
la consapevolezza? » Il Buddha rispose: « È meglio che tu le donne non
le veda affatto. » Ānanda era perplesso. Com’è possibile non vedere la
gente? Ci pensò su, e fece un’altra domanda al Buddha: « Se ci troviamo
in situazioni che rendono inevitabile vederle, il Beato come ci
consiglierebbe di praticare? » « In queste situazioni, Ānanda, non
parlare. Non parlare! » Ānanda ci pensò ancora su. Pensò che a volte si
poteva camminare in una foresta e perdersi. In quel caso sarebbe stato
necessario parlare con chiunque avesse incontrato. Perciò chiese: « Se
c’è necessità di parlare, il Beato come ci consiglierebbe di
comportarsi? » « Ānanda! Parla con consapevolezza! »

Sempre e in tutte le circostanze, la consapevolezza è la virtù suprema.
Il Buddha istruì Ānanda su cosa fare in caso di necessità. Dovremmo
contemplare per vedere cosa è davvero necessario per noi. Quando ad
esempio parliamo o facciamo domande ad altre persone, dovremmo dire solo
quel che è indispensabile. Quando la mente non è pura, quando ha
pensieri dissoluti, non consentitevi assolutamente di parlare. Non è
però questo il modo in cui ci comportiamo. Più impura è la mente, più
vogliamo parlare. Più dissolutezza c’è nella nostra mente, più vogliamo
far domande, vedere, parlare. Si tratta di due vie molto diverse.

È per questo che ho paura. Di questo ho veramente molta paura. Voi di
paura non ne avete, ma è possibile che a voi vada peggio che a me. « Di
questo non ho paura. Non c’è problema! » Io però devo continuare ad
avere paura. Potrebbe forse succedere pure che un vecchio abbia delle
brame? Per questo nel mio monastero tengo lontani il più possibile i due
sessi. Se non ci fosse alcuna necessità, allora non ci dovrebbe essere
alcun contatto. Quando praticavo da solo nella foresta, a volte vedevo
le scimmie sugli alberi e provavo del desiderio. Stavo seduto lì,
guardavo, pensavo e desideravo: « Mica sarebbe poi male andare assieme a
loro, ed essere una scimmia! » Il desiderio sessuale può fare anche
questo: può destarsi anche per una scimmia. Allora, da me non potevano
venire seguaci di sesso femminile per ascoltare il Dhamma. Avevo troppa
paura di quello che sarebbe potuto succedere. Non è che ce l’avessi con
loro, è solo che ero troppo stolto. Ora se parlo con le donne, lo faccio
con quelle più anziane. Sto sempre in guardia. Ho avuto esperienza di
questo pericolo nella mia pratica. Non spalancavo gli occhi e non
parlavo animatamente per intrattenerle. Avevo troppa paura a comportarmi
così. Fate attenzione! Ogni _samaṇa_ deve affrontare queste cose ed
esercitare il contenimento. È importante.

Tutti gli insegnamenti del Buddha hanno un senso. Hanno un senso anche
le cose che non immaginate che lo possano avere. È così strano.
Inizialmente non avevo alcuna fiducia nella meditazione seduta. Pensavo:
« A che potrà mai servire? » Poi c’era la meditazione camminata.
Camminavo da un albero all’altro, avanti e indietro, avanti e indietro,
poi mi stancavo di farla e pensavo: « Per quale ragione sto camminando?
Camminare avanti e indietro non ha alcun senso. » È così che pensavo.
Nei fatti, però, la meditazione camminata ha un grande valore. Stare
seduti per praticare il _samādhi_ ha un grande valore. È l’indole di
alcune persone a renderle confuse a proposito della meditazione
camminata e della meditazione seduta.

Non possiamo fare meditazione solo in una postura. Quattro sono le
posture degli esseri umani: in piedi, camminare, seduti e distesi. Gli
insegnamenti parlano di rendere le posture uniformi ed uguali. Potreste
farvi l’idea che ciò significhi dover stare in piedi, camminare, stare
seduti e stare distesi per lo stesso numero di ore. Quando si ascolta
questo insegnamento, non si riesce ad immaginare che cosa significhi
realmente, perché è il linguaggio del Dhamma, non linguaggio ordinario.
« Bene, starò seduto per due ore, in piedi per due ore e poi disteso per
due ore. » Forse è in questo modo che pensate. Io ho pensato così.
Cercai di praticare in questa maniera, ma non funzionò. È perché non
ascoltiamo nel modo giusto, stiamo a sentire solo le parole. « Rendere
uguali le posture » è riferito alla mente, a nient’altro. Significa
rendere la mente chiara e luminosa per far sorgere la saggezza, in modo
tale che si abbia conoscenza di qualsiasi cosa avvenga in ogni postura e
situazione. Quale che sia la postura, si conoscono i fenomeni e gli
stati mentali per quello che sono: impermanenti, insoddisfacenti e non
riconducibili a un sé. La mente è fondata in questa consapevolezza in
ogni momento e in tutte le posture. Quando la mente prova attrazione o
quando prova avversione, non smarrite il Sentiero, conoscete queste
condizioni per quello che sono. La vostra consapevolezza è ferma e
costante, e lasciate andare con fermezza e con costanza. Non siete
ingannati dalle buone condizioni. Non siete ingannati dalle cattive
condizioni. Restate sul retto Sentiero. Questo si chiama “rendere
uguali le posture”. Si riferisce all’interiorità, non all’esteriorità.
È della mente che si sta parlando.

Se con la mente rendiamo uguali le posture, quando siamo lodati è solo
quel che è. Quando siamo calunniati è solo quel che è. Non andiamo su e
giù per quelle parole, restiamo stabili. Perché? Perché in queste cose
vediamo il pericolo. Vediamo lo stesso pericolo tanto nella lode quanto
nella critica: questo significa rendere uguali le posture. Abbiamo
questa consapevolezza interiore quando guardiamo sia i fenomeni
interiori sia quelli esteriori. Nel modo ordinario di sperimentare le
cose, quando appare qualcosa di piacevole abbiamo una reazione positiva
e quando appare qualcosa di spiacevole abbiamo una reazione negativa. Le
posture non sono uguali. Quando sono uguali la consapevolezza l’abbiamo
sempre. Sapremo quando ci stiamo aggrappando al bene e quando ci stiamo
aggrappando al male: così va meglio. Anche se non riusciamo a lasciar
andare, siamo continuamente consapevoli di questi stati mentali. Essendo
continuamente consapevoli di noi stessi e dei nostri attaccamenti,
giungeremo a vedere che questo aggrapparsi non è il Sentiero. Saperlo è
già il cinquanta per cento, anche se non riusciamo a lasciar andare.
Anche se non riusciamo a lasciar andare, comprendiamo che lasciar andare
quelle cose recherà pace. Vediamo il pericolo nelle cose che ci
piacciono e in quelle che non ci piacciono. Vediamo il pericolo nella
lode e nella critica. Questa è una consapevolezza costante.

Sia che veniamo lodati sia che veniamo criticati, siamo continuamente
consapevoli. Quando la gente del mondo è criticata e calunniata, non
riesce a tollerarlo, si sente ferita. Quando è lodata, è contenta ed
eccitata. Nel mondo, tutto questo è naturale. Però, quando coloro che
praticano ricevono una lode, conoscono il pericolo. Quando ricevono una
critica, conoscono il pericolo. Sanno che attaccarsi a entrambe queste
cose porterà cattive conseguenze. Sono tutte quante dannose, se ci
aggrappiamo a esse e vi attribuiamo un significato. Quando abbiamo
questo tipo di consapevolezza, conosciamo i fenomeni quando si
verificano. Sappiamo che se ci attacchiamo ai fenomeni, ci sarà davvero
sofferenza. Se non siamo consapevoli, l’aggrapparsi a quel che riteniamo
bene o male fa sorgere la sofferenza. Se prestiamo attenzione, vediamo
questo aggrapparsi, vediamo come ci impossessiamo del bene e del male, e
come tutto questo causi sofferenza. Così, inizialmente ci aggrappiamo
alle cose e, con consapevolezza, vediamo che questo è un errore. Come
mai? Perché ci aggrappiamo saldamente e sperimentiamo la sofferenza. Poi
iniziamo a cercare un modo per lasciar andare ed essere liberi.
Riflettiamo: « Che cosa dovrei fare per essere libero? »

L’insegnamento buddhista dice di non aggrapparsi, di non attaccarsi, di
non tenere strette le cose. Non lo comprendiamo del tutto. Il punto è
tenere, ma non strettamente. Ad esempio, vedo questo oggetto davanti a
me. Sono curioso di sapere che cosa sia, allora lo prendo e lo guardo. È
una torcia elettrica. Adesso la poso. Questo è tenere, ma non
strettamente. Se ci viene detto di non prendere nulla in alcun modo, che
possiamo fare? Penseremo che non dovremmo praticare la meditazione
seduta o quella camminata. Perciò inizialmente dobbiamo tenere, ma senza
forte attaccamento. Si può dire che si tratti di _taṇhā_, ma diventerà
_pāramī_.footnote:[_pāramī._ “Perfezione”. Per l’elenco delle dieci
relative qualità, si veda il <<glossary#parami,Glossario, pāramī>>.] Ad esempio
siete venuti qui al Wat Pah Pong, e prima di venire dovete aver avuto il
desiderio di farlo. Senza desiderio, non sareste venuti. Possiamo dire
che siete venuti per il desiderio di venire: è come il tenere le cose.
Poi ritornerete a casa: è un non aggrapparsi. Proprio come essere
incerti a proposito di cosa sia questo oggetto, lo prendiamo, vediamo
che è una torcia elettrica e lo posiamo. Prendere per vedere, conoscere
e lasciar andare, conoscere e lasciar andare. Delle cose si può dire che
sono bene o che sono male, ma voi limitatevi a conoscerle e a lasciarle
andare. Siete consapevoli di tutti i buoni fenomeni e di tutti quelli
cattivi, e li lasciate andare. Non li afferrate con ignoranza. Li
afferrate con saggezza e li posate.

In questo modo le posture possono essere uguali ed uniformi. Significa
che la mente è capace. La mente ha consapevolezza ed è nata la saggezza.
Quando la mente ha saggezza, oltre a questo che altro potrebbe esserci?
Prende le cose, ma non c’è pericolo. Non c’è aggrapparsi strettamente,
ma conoscere e lasciar andare. Ascoltando un suono, lo sapremo: « Il
mondo dice che questo è bene. » E lo lasciamo andare. Il mondo può anche
dire: « Questo è male. » Ma noi lasciamo andare. Conosciamo il bene e il
male. Chi non conosce il bene e il male si attacca al bene e al male, e
il risultato è la sofferenza. Chi ha la conoscenza non ha questo
attaccamento.

Riflettiamo. Per quale scopo stiamo vivendo? Cosa vogliamo ottenere dal
nostro lavoro? Stiamo vivendo in questo mondo. Per quale scopo stiamo
vivendo? Svolgiamo il nostro lavoro. Che cosa vogliamo ottenere dal
nostro lavoro? Secondo la via del mondo, la gente svolge il proprio
lavoro perché vuole delle cose e tutto questo lo considera logico.
L’insegnamento del Buddha va oltre. Dice di svolgere il lavoro senza
desiderare nulla. Nel mondo si fa questo e si ottiene quello, si fa
quello e si ottiene questo, si fa sempre una cosa per ottenere qualcosa
in cambio. Questa è la via della gente del mondo. Il Buddha dice di
lavorare per lavorare, senza volere nulla. Tutte le volte che lavoriamo
desiderando qualcosa, soffriamo. Provateci.
