[[si-puo-fare]]
= Si può fare

Per favore ora persuadete la vostra mente ad ascoltare il Dhamma. Oggi è
la tradizionale giornata di _dhammasavaṇa_.footnote:[_dhammasavaṇa._
L’ascolto o lo studio del Dhamma.] È il tempo giusto, per noi buddhisti,
per accrescere la nostra consapevolezza e la nostra saggezza studiando
il Dhamma. Dare e ricevere gli insegnamenti è una cosa che facciamo da
lungo tempo. Le attività che di solito svolgiamo durante questa giornata
– cantare omaggio al Buddha, prendere i precetti morali, meditare e
ascoltare gli insegnamenti – dovrebbero essere intese come metodi e
principi per lo sviluppo spirituale. Questo sono, nient’altro.

Per esempio, quando si tratta di prendere i precetti, un monaco li
espone e i laici fanno voto di assumerli. Non fraintendete quel che
avviene. La verità è che la moralità non è una cosa che può essere data.
In realtà, non può essere né richiesta né ricevuta da qualcuno. Non
possiamo darla a nessun altro. Nel nostro dialetto sentiamo che la gente
dice: « il venerabile monaco ha dato i precetti » o « abbiamo ricevuto i
precetti. » Qui in campagna parliamo così, e questo è diventato il
nostro modo abituale di pensare. Se è così che pensiamo, che veniamo a
ricevere i precetti dai monaci nei giorni di osservanza lunare e che, se
i monaci non ci danno i precetti, non avremo alcuna moralità, allora dai
nostri antenati abbiano ricevuto solo una tradizione di illusioni.
Pensare in questo modo significa rinunciare a una nostra responsabilità,
senza che in noi vi sia salda fiducia e convinzione. Tutto questo viene
poi tramandato alla generazione successiva e anch’essa viene a
“ricevere” i precetti dai monaci. I monaci, poi, arrivano a credere di
essere gli unici a poter “dare” i precetti ai laici. Nei fatti, per la
moralità e i precetti non è così. Non sono una cosa da “dare” o
“ricevere”. Nelle cerimonie per “accumulare meriti” e in occasioni
consimili, usiamo però questa forma rituale che concorda con la
tradizione e ne utilizziamo la terminologia.

In verità, la moralità risiede nelle intenzioni delle persone. Se avete
la consapevole determinazione di astenervi dalle azioni dannose e
sbagliate del corpo e della parola, la moralità trova in voi una
realizzazione. Dovreste saperlo dentro di voi. Va bene fare voto a
un’altra persona di osservarli. Anche da soli potete riconfermare i
precetti. Se non sapete come si faccia, potete richiederli a qualcun
altro. Non si tratta di una cosa davvero complicata o lontana. Così,
tutte le volte che desideriamo ricevere la moralità e il Dhamma, li
abbiamo proprio in quel momento. È come l’aria tutt’intorno a noi. Entra
in noi tutte le volte che respiriamo. Per ogni genere di bene e di male
è così. Se desideriamo fare del bene, possiamo farlo ovunque e in ogni
momento. Possiamo farlo da soli o insieme ad altri. Lo stesso vale per
il male. Possiamo farlo con molte o poche persone, in un posto nascosto
o all’aperto. È così.

Sono cose che esistono già. Però, che gli esseri umani pratichino la
moralità dovremmo considerarla una cosa normale. Una persona priva di
moralità non è diversa da un animale. Se decidete di vivere come un
animale, ovviamente per voi non esiste né bene né male, perché un
animale non conosce affatto cose di questo genere. Un gatto cattura i
topi, ma noi non diciamo che fa del male, perché il gatto non ha né i
concetti né la conoscenza di bene o male, di giusto o sbagliato. Questi
esseri viventi non fanno parte degli esseri umani. Sono nel regno
animale. Il Buddha fece notare che questo gruppo di esseri vive
semplicemente secondo il tipo di kamma che è proprio degli animali. Chi
comprende giusto e sbagliato, bene e male, è l’essere umano. Il Buddha
insegnò il Dhamma agli esseri umani. Se noi esseri umani non abbiamo
moralità e non conosciamo queste cose, non siamo poi molto diversi dagli
animali. Per questo è opportuno che studiamo e impariamo la moralità, e
la mettiamo in pratica. Ciò significa trarre profitto e portare a
compimento la preziosa realizzazione dell’esistenza umana.

Il Dhamma profondo consiste nell’insegnamento che la moralità è
necessaria. Quando c’è moralità, abbiamo un fondamento che ci consente
di progredire nel Dhamma. Moralità significa i precetti in relazione a
ciò che è proibito e a ciò che è consentito. Il Dhamma si riferisce alla
natura e a quello che gli uomini sanno della natura, a come le cose
esistano secondo natura. La natura non è una cosa che abbiamo
organizzato noi. Essa esiste secondo le sue stesse condizioni. Per un
semplice esempio, basta guardare gli animali. Alcune specie, come i
pavoni, nascono in vari esemplari e colori. Non sono creati in quel modo
o modificati dagli esseri umani, sono nati così, secondo natura. È solo
un piccolo esempio.

Tutte le cose della natura esistono nel mondo. Questo è ancora parlare
di una comprensione di tipo mondano. Il Buddha ci insegnò il Dhamma per
conoscere la natura, per lasciarla andare e farla esistere in accordo
con le sue condizioni. Questo è parlare del mondo materiale esteriore.
Per quanto concerne il _nāmadhammā_,footnote:[_nāmadhammā._ Fenomeno
mentale.] ossia la mente, non le si può consentire di seguire le
condizioni sue proprie. Deve essere addestrata. Alla fine, possiamo dire
che la mente è la maestra del corpo e della parola, e necessita perciò
di essere ben educata. Se si consente alla mente di seguire le proprie
naturali tendenze, si diventa animali. Deve essere ben istruita e
addestrata. Deve giungere a conoscere la natura, non essere solo
lasciata a seguire la natura.

Siamo nati in questo mondo e tutti noi siamo ovviamente afflitti dal
desiderio, dalla rabbia e dall’illusione. Il desiderio ci fa bramare
varie cose e induce nella mente uno stato di squilibrio e turbamento.
Così è la natura. Non fate che la mente segua questi impulsi di
bramosia, ciò porta solo a bollori e disagi. Meglio formarsi nel Dhamma,
nella Verità. Quando in noi si presenta l’avversione, vogliamo esprimere
rabbia nei riguardi delle persone; si può perfino arrivare al punto di
aggredire fisicamente o di uccidere. Ma noi non “lasciamo andare” la
mente in accordo con la sua natura. Conosciamo quello che sta
succedendo. Lo vediamo per ciò che è, e lo insegniamo alla mente. Questo
è studiare il Dhamma.

Lo stesso avviene con l’illusione. Quando si presenta, siamo confusi. Se
la lasciamo così com’è, restiamo nell’ignoranza. Per questo il Buddha ci
disse di conoscere la natura, di insegnare alla natura, di addestrare e
adattare la natura, di conoscere esattamente cos’è la natura. Ad
esempio, le persone nascono con una forma fisica e con una mente.
All’inizio queste cose sorgono, alla metà cambiano e alla fine si
estinguono. È normale. È la loro natura. Non possiamo fare molto per
alterare tutto questo. Addestriamo le nostre menti come possiamo e
quando arriva il momento dobbiamo lasciar andare tutto. È al di là della
capacità degli esseri umani di modificare o evitare questo dato di
fatto. Il Dhamma insegnato dal Buddha è una cosa che deve essere
applicata mentre siamo qui, per agire, parlare e pensare in modo
corretto e appropriato. Egli insegnava alla mente delle persone affinché
non si illudessero a riguardo della natura, della realtà convenzionale e
delle supposizioni. Il Maestro ci insegnò a vedere il mondo. Il suo
Dhamma è un insegnamento che è al di sopra e al di là del mondo. Siamo
nel mondo. Siamo nati in questo mondo. Egli ci insegnò a trascenderlo, a
non essere prigionieri delle sue vie e abitudini.

È come un diamante che cade in un fosso fangoso. Non importa quanta
sporcizia e quanto sudiciume lo ricoprano, esse non distruggono la sua
radiosità, i suoi colori e il suo valore. Anche se il fango è
appiccicato al diamante, esso non perde nulla, resta come
originariamente era. Sono cose separate.

Il Buddha insegnò a essere al di sopra del mondo, il che significa
conoscere il mondo con chiarezza. Con “mondo” Egli non intendeva la
terra, il cielo e gli elementi, ma la mente, la ruota del _saṃsāra_ che
è nel cuore delle persone. Egli intendeva questa ruota, questo mondo.
Questo è il mondo che il Buddha conobbe con chiarezza. Quando parliamo
di conoscere il mondo con chiarezza, stiamo parlando di questo. Se fosse
altrimenti, il Buddha avrebbe dovuto volare dappertutto per “conoscere
il mondo con chiarezza”. Non è così. Si tratta di un punto solo. Tutti
i _dhamma_ si riducono a un solo punto. Ad esempio le persone, gli
uomini e le donne. Se osserviamo un uomo e una donna, conosciamo la
natura di tutte le persone dell’universo. Non sono diverse.

Ce lo insegna un altro esempio, il calore. Se conosciamo solo questa
qualità, l’essere caldo, non importa quale sia la fonte o la causa del
calore. La condizione “caldo” è così. Se conosciamo con chiarezza
questa sola cosa, allora ovunque nell’universo ci sia del calore,
sappiamo che così è il calore. Il Buddha conobbe un unico punto e la sua
conoscenza incluse tutto il mondo. Conoscendo che il freddo è in un
certo modo, quando e ovunque nel mondo Egli incontrò il freddo, già lo
conosceva. Insegnò agli esseri che vivono nel mondo un unico punto per
conoscere il mondo, per conoscere la natura del mondo, per conoscere le
persone, gli uomini e le donne, per conoscere il modo di esistere degli
esseri nel mondo. Così era la sua conoscenza. Conoscendo un solo punto,
conosceva tutte le cose.

Il Dhamma esposto dal Maestro serviva per andare al di là della
sofferenza. Che cosa s’intende con “andare al di là della sofferenza”?
Che cosa dovremmo fare per “sfuggire alla sofferenza”? Ci è necessario
studiare un po’, abbiamo bisogno di studiare i pensieri e le sensazioni
nei nostri cuori. Tutto qui. Si tratta di una cosa che attualmente non
siamo in grado di modificare. Possiamo essere liberi da tutta la
sofferenza e da tutta l’insoddisfazione della vita solo modificando
quest’unico punto: la nostra visione abituale del mondo, il nostro modo
di pensare e di sentire. Se arriviamo ad attribuire un nuovo significato
alle cose, se arriviamo a una nuova comprensione, trascendiamo le
vecchie percezioni e comprensioni.

L’autentico Dhamma del Buddha non indica cose lontane. Insegna in
relazione all’_attā_, al “sé”, insegna che le cose in realtà non sono
un “sé”. Questo è tutto. Tutti gli insegnamenti che il Buddha impartì
sottolineavano che « questo non è un “sé ”, questo non appartiene a un
“sé”, non esiste un qualcosa come “noi stessi” o gli “altri”. »
Ora, quando entriamo in contatto con questo insegnamento, in realtà non
riusciamo neanche a leggerlo veramente, non “traduciamo” il Dhamma
correttamente. Continuiamo a pensare « questo sono io, questo è mio. »
Ci attacchiamo alle cose e le rivestiamo di un significato. Finché
facciamo così, non possiamo districarci dalle cose; il coinvolgimento si
approfondisce e il pasticcio peggiora sempre più. Sapendo che non c’è
alcun “io” e che, come il Buddha insegnò, corpo e mente sono in realtà
_anattā_,footnote:[_anattā._ Non-sé, non sostanziale, impersonale.] se
continuiamo a investigare infine giungeremo a comprendere l’effettiva
condizione di assenza di un “sé”. Comprenderemo davvero che non c’è
alcun “sé”.

Il piacere è solo piacere. La sensazione è solo sensazione. Il ricordo è
solo ricordo. Il pensiero è solo pensiero. Sono tutte cose che sono
“solo” così. La felicità è solo felicità, la sofferenza è solo
sofferenza. Il bene è solo bene, il male è solo male. Qualsiasi cosa
esista è solo così. Non c’è alcuna reale felicità né alcuna reale
sofferenza. Ci sono solo condizioni che semplicemente esistono:
semplicemente felice, semplicemente sofferente, semplicemente caldo,
semplicemente freddo, semplicemente un essere o una persona. Dovreste
continuare a osservare per vedere che le cose sono solo così. Solo
terra, solo acqua, solo fuoco, solo vento. Dovreste continuare a
“leggere” queste cose e a investigare questo punto. Alla fine la
nostra percezione cambierà e avremo una diversa sensazione a proposito
delle cose. La convinzione saldamente condivisa che esistano un sé e
delle cose che a un sé appartengano, gradualmente scomparirà. Quando
questa percezione delle cose verrà rimossa, quella ad essa opposta
continuerà costantemente ad aumentare.

Quando la comprensione di _anattā_ sarà completa, saremo in grado di
rapportarci alle cose di questo mondo – ai nostri più amati possessi e
coinvolgimenti, agli amici e alle relazioni, alla ricchezza, a quanto
abbiamo raggiunto e alla nostra posizione sociale – esattamente come se
fossero degli indumenti. Quando camicie e pantaloni sono nuovi, li
indossiamo. Si sporcano e li laviamo. Dopo un po’ si usurano e li
scartiamo. Sono questioni di ordinaria amministrazione. Ci sbarazziamo
continuamente delle cose vecchie per poi usare abiti nuovi. Avremo
questa stessa sensazione a proposito della nostra esistenza in questo
mondo. Non piangeremo né ci lamenteremo delle cose. Non saremo
tormentati o appesantiti da esse. Rimarranno le stesse cose che erano in
precedenza, ma la nostra sensazione e la nostra comprensione cambierà.
La nostra conoscenza si eleverà e vedremo la Verità. Otterremo la
suprema visione e avremo imparato quell’autentico Dhamma che dovremmo
conoscere e vedere. Dov’è il Dhamma che dovremmo conoscere e vedere? È
proprio qui, dentro di noi, dentro questo corpo e questa mente. Già lo
abbiamo, dovremmo solo riuscire a conoscerlo e vederlo.

Siamo tutti nati in questo regno umano. Tutto quello che abbiamo
ottenuto siamo in procinto di perderlo. Abbiamo visto nascere e morire
delle persone. Lo abbiamo visto mentre succedeva, ma in realtà non lo
abbiamo visto con chiarezza. Quando c’è una nascita, ce ne rallegriamo;
quando la gente muore, piangiamo. Non c’è fine. Le cose vanno in questo
modo e non c’è fine alla nostra follia. Vediamo la nascita e siamo
sconsiderati. Vediamo la morte e siamo sconsiderati. C’è solo questa
follia senza fine. Diamo uno sguardo a tutto questo. Si tratta di eventi
naturali. Contemplate il Dhamma qui, il Dhamma che dovremmo conoscere e
vedere. Questo Dhamma esiste proprio ora. Decidetevi. Esercitate
moderazione e autocontrollo. Ora siamo in mezzo alle cose di questa
vita.

Non dovremmo temere la morte. Dovremmo aver paura dei regni inferiori.
Non abbiate paura di morire, abbiate piuttosto paura di cadere negli
inferi. Dovreste aver paura di fare cose sbagliate mentre siete ancora
in vita. Le cose con cui abbiamo a che fare sono roba vecchia, non
nuova. Alcuni sono vivi, ma non conoscono affatto se stessi. « Che
importanza ha quel che faccio ora? Non posso sapere cosa succederà
quando muoio. » Pensano così. Non pensano ai nuovi semi che stanno
creando per il futuro. Vedono solo il vecchio frutto. Restano fissi
sull’esperienza attuale, senza capire che se c’è un frutto deve
provenire da un seme, e che all’interno del frutto ora abbiamo i semi
del frutto futuro. Questi semi desiderano solo d’essere piantati. Le
azioni nate dall’ignoranza continuano la catena in questo modo, ma
mentre state mangiando il frutto non pensate a tutte le conseguenze.

Ovunque nella mente c’è molto attaccamento, proprio lì sperimentiamo
un’intensa sofferenza, un’intensa afflizione, un’intensa difficoltà. Il
punto nel quale sperimentiamo la maggior parte dei problemi è dove
esiste attrazione, bramosia e preoccupazione. Per favore cercate di
risolvere il problema. Ora, mentre siete vivi e respirate, continuate a
osservare quel punto fino a che non siete in grado di “tradurlo” e di
risolvere il problema.

Qualsiasi cosa stiamo sperimentando come parte della nostra vita ora, un
giorno dovremo separarcene. Non lasciate perciò semplicemente che il
tempo passi. Praticate l’educazione spirituale. Assumete questa
divisione, questa separazione e perdita quale vostro oggetto di
contemplazione nel presente, proprio ora, fino a che non riuscite a
vedere che si tratta di una cosa normale e naturale. Quando c’è ansia e
rimpianto, abbiate la saggezza di riconoscere i limiti di questa ansia e
di questo rimpianto, conoscendoli per quel che sono secondo verità. Se
riuscite a vedere le cose in questo modo, sorgerà la saggezza. Tutte le
volte che ci capita di soffrire, se investighiamo, può nascere la
saggezza. La gente, però, di solito non vuole investigare. Dovunque vi
siano esperienze piacevoli o spiacevoli, lì può nascere la . Se
conosciamo la felicità e la sofferenza per ciò che esse realmente sono,
allora conosciamo il Dhamma. Se conosciamo il Dhamma, conosciamo il
mondo con chiarezza. Se conosciamo il mondo con chiarezza, conosciamo il
Dhamma.

In effetti, la maggior parte di noi se qualcosa è spiacevole non ne
vuole sapere proprio nulla. Restiamo catturati dall’avversione. Se
qualcuno non ci piace, non vogliamo guardarlo in volto o stargli vicino.
È il contrassegno della persona folle e poco abile, una brava persona
non si comporta così. Se qualcuno invece ci piace, ovviamente vogliamo
stargli vicino, facciamo ogni sforzo per stare con lui, per deliziarci
con la sua compagnia. Anche questa è follia. In realtà si tratta della
stessa cosa, come la palma e il dorso della mano. Quando giriamo la mano
verso l’alto e vediamo la palma, il dorso è nascosto alla vista. Quando
la capovolgiamo, allora non si vede la palma. Nella nostra prospettiva
il piacere nasconde il dolore e il dolore nasconde il piacere. Lo
sbagliato nasconde il giusto, il giusto nasconde lo sbagliato. Guardando
un solo lato la nostra conoscenza non è completa. Le cose dobbiamo farle
con completezza finché siamo vivi. Continuiamo a osservare, a separare
il vero dal falso, notando come le cose realmente sono e alla fine del
percorso troveremo la pace. Quando verrà il momento, potremo sbarazzarci
di tutto e lasciar andare completamente. Ora dobbiamo sforzarci con
fermezza a separare le cose e continuare a cercare di sbarazzarci di
tutto.

Il Buddha nei suoi insegnamenti ci parlò dei capelli, dei peli, delle
unghie, dei denti e della pelle. Ci insegnò a come meditare per
separarli dal resto del corpo. Chi non sa come farlo, sa solamente come
attaccarsi a essi per trattenerli. Ora, mentre non ci siamo ancora
staccati da queste cose, dovremmo essere abili nel meditare su di esse.
Non abbiamo ancora lasciato questo mondo, perciò dovremmo stare attenti.
Dovremmo contemplare tanto, fare cospicue offerte caritative, recitare
molto le Scritture e praticare molto. Dovremmo sviluppare la visione
profonda nell’impermanenza, nel carattere insoddisfacente e nella
mancanza di un sé. Anche se la mente non vuole ascoltare, dovremmo
continuare a frantumare le cose in questo modo per giungere alla
conoscenza nel presente. Ci si può certamente riuscire. Tutti possono
realizzare la conoscenza che trascende il mondo. Siamo bloccati in
questo mondo. Questa è una maniera per “distruggere” il mondo:
mediante la contemplazione, vedere al di là del mondo per poterlo
trascendere dentro noi stessi. Anche mentre stiamo vivendo in questo
mondo, la nostra visuale può andare al di là di esso.

In un’esistenza mondana si può generare sia il bene sia il male. Ora
cerchiamo di praticare la virtù e di rinunciare al male. Quando arrivano
i buoni risultati, non dovremmo stare sotto quel bene, bensì essere in
grado di trascenderlo. Se non lo si trascende, si diventa schiavi della
virtù e di quello che si ritiene essere bene. Vi troverete in
difficoltà, e le vostre lacrime non avranno fine. Non importa quanto vi
siate impegnati per il bene, se siete attaccati a esso non sarete ancora
liberi e le vostre lacrime non avranno fine. Chi però oltre al male
trascende il bene, non ha più lacrime da versare. Si sono asciugate. Ci
può essere una fine. Dovremmo imparare a usare la virtù, non a esserne
usati.

In poche parole, il nucleo dell’insegnamento del Buddha è trasformare il
nostro modo di vedere. È possibile cambiarlo. Bisogna solo osservare le
cose, e avviene. Siamo nati e perciò sperimenteremo invecchiamento,
malattia, morte e separazione. Queste cose sono proprio qui. Non abbiamo
bisogno di guardare su in cielo o giù in terra. Il Dhamma di cui abbiamo
bisogno per guardare e per conoscere può essere visto proprio qui,
dentro di noi, in ogni momento, tutti i giorni. Quando c’è una nascita,
siamo pieni di gioia. Quando c’è una morte, ci addoloriamo. È così che
trascorre la nostra vita. Queste sono le cose che dobbiamo conoscere, ma
non abbiamo ancora guardato davvero dentro di esse e visto la Verità.
Siamo profondamente bloccati in questa ignoranza. « Quando vedremo il
Dhamma? » Ce lo chiediamo, ma il Dhamma è proprio qui affinché lo si
veda ora, nel presente.

Questo è il Dhamma che dovremmo imparare e vedere. Questo è quel che il
Buddha insegnò. Non insegnò a proposito di déi, di demoni e
_nāga_,footnote:[_nāga._ Categoria di esseri non umani dalle fattezze
serpentine; elefanti; uno degli epiteti del Buddha.] di divinità
protettrici e semidéi gelosi, di spiriti della natura e così via.
Insegnò cose che tutti dovrebbero conoscere e vedere. Queste sono le
verità che davvero dovremmo essere in grado di comprendere. I fenomeni
esterni sono così, palesano le Tre Caratteristiche.footnote:[Tre
Caratteristiche (_tilakkhaṇa_). Le qualità di tutti i fenomeni;
impermanenza (_anicca_), carattere insoddisfacente (_dukkha_) e non-sé
(_anatta_).]

Se siamo veramente interessati a tutto questo e contempliamo con
serietà, possiamo ottenere genuina conoscenza. Se si trattasse di un
qualcosa che non può essere realizzato, il Buddha non si sarebbe
disturbato a parlarne. Quante decine e centinaia di migliaia dei suoi
discepoli sono giunti alla Realizzazione? Chi davvero si applica a
osservare le cose, può giungere alla conoscenza. Il Dhamma è così. Noi
stiamo vivendo in questo mondo. Il Buddha voleva che lo conoscessimo.
Vivendo nel mondo, otteniamo la nostra conoscenza dal mondo. Il Buddha è
detto _lokavidū_, ossia Colui che Conosce, che conosce il mondo con
chiarezza. Significa vivere nel mondo senza restare bloccati nelle vie
del mondo, vivere in mezzo all’attrazione e all’avversione senza restare
bloccati nell’attrazione e nell’avversione. Questo è quel che si può
dire e spiegare con un linguaggio ordinario. Così insegnò il Buddha.

Anche se normalmente parliamo in termini di _attā_, di sé, di io e mio,
di tu e tuo, la mente può continuare a rimanere senza sosta nella
percezione dell’_anattā_, del non-sé. Pensateci. Quando parliamo ai
bambini lo facciamo in un modo e quando abbiamo a che fare con gli
adulti parliamo in un altro. Se usiamo parole adatte ai bambini per
parlare agli adulti, o se usiamo parole da adulti per parlare con i
bambini, non funzionerà. Dobbiamo conoscere l’uso appropriato delle
convenzioni quando si parla con i bambini. Può essere opportuno parlare
di io e mio, di tu e tuo e così via, ma nell’interiorità la mente è
Dhamma, dimora nella percezione dell’_anattā_. Dovreste avere questo
tipo di fondamento.

È per questo che il Buddha disse che, mentre si vive nel mondo, si
dovrebbe assumere il Dhamma quale fondamento e base per la pratica. Non
è giusto assumere le vostre idee, i vostri desideri e le vostre
opinioni. Il Dhamma dovrebbe essere il vostro criterio. Se assumete come
criterio voi stessi, diventate egocentrici. Se assumete qualcun altro
come vostro criterio, siete solo infatuati di quella persona. Essere
schiavi di se stessi o di un altro non è la via del Dhamma. Il Dhamma
non inclina verso alcuna persona né segue le personalità. Segue la
Verità. Non si accorda semplicemente con ciò che piace e ciò che non
piace alla gente. Le reazioni abituali non hanno nulla a che fare con la
verità delle cose.

Se prendiamo davvero in considerazione tutto questo e investighiamo a
fondo per conoscere la Verità, entreremo nel giusto Sentiero. Il nostro
modo di vivere diverrà corretto. Il pensiero diverrà corretto. Le nostre
azioni e le nostre parole diverranno corrette. Così, dovremmo veramente
guardare dentro tutto questo. Perché abbiamo sofferto? A causa della
mancanza di conoscenza: non conoscere dove le cose cominciano e
finiscono, non conoscere le cause. Questa è ignoranza. Quando c’è questa
ignoranza sorgono vari desideri, e siccome siamo stati guidati da essi
abbiamo creato le cause della sofferenza. Il risultato doveva essere la
sofferenza. Quando mettete insieme legna da ardere e avvicinate a essa
un fiammifero acceso sperando che non si generi calore, quali
possibilità avete? State accendendo un fuoco, o no? Questa è
l’originazione stessa.

Se comprendete queste cose, nascerà la moralità. Allora nascerà il
Dhamma. Perciò, preparatevi. Il Buddha ci ammonì a prepararci. Non c’è
bisogno di preoccuparsi troppo delle cose o di essere ansiosi al
riguardo. Guardate solo qui. Guardate il luogo senza desideri, il luogo
privo di pericoli. Il Buddha insegnò _Nibbāna paccayo hotu_, lasciate
che sia una causa per il Nibbāna. Se sarà una causa per la realizzazione
del Nibbāna, è perché avete guardato il luogo in cui le cose sono vuote,
dove le cose nascono e raggiungono la loro fine, si esauriscono.
Guardate il luogo in cui non ci sono più cause, dove non c’è più il sé o
l’altro da sé, io e mio. Questo sguardo diventa una causa o una
condizione, una condizione per conseguire il Nibbāna. Praticare la
generosità diventa una causa per la realizzazione del Nibbāna. Praticare
la moralità diventa una causa per la realizzazione del Nibbāna.
Ascoltare gli insegnamenti diventa una causa per la realizzazione del
Nibbāna. Così, possiamo fare in modo che tutte le nostre attività di
Dhamma diventino cause per il Nibbāna. Se però non stiamo guardando
verso il Nibbāna, se stiamo guardando il sé e l’altro da sé, se ci
stiamo aggrappando e ci stiamo attaccando, senza fine, ciò non diventerà
una causa per il Nibbāna.

Quando abbiamo a che fare con gli altri, che parlano in termini di sé,
di io e di mio, e di ciò che è nostro, siamo subito d’accordo con questi
punti di vista. Subito pensiamo: « Sì, è giusto! » Ma non è giusto.
Anche se la mente lo sta dicendo – « giusto, giusto » – dobbiamo tenerla
sotto controllo. È come un bambino che teme i fantasmi. Forse anche i
genitori hanno paura. Non è però opportuno che i genitori ne parlino. Se
lo fanno, il bambino non si sentirà né protetto né al sicuro. « No,
ovviamente papà non ha paura. Non ti preoccupare, papà è qui. Non ci
sono fantasmi. Non c’è nulla di cui preoccuparsi. » Bene, anche il padre
potrebbe avere molta paura. Se lui comincia a parlarne, si agiteranno
tutti per i fantasmi al punto da saltar su e correre via, padre, madre e
figlio, e finiranno per non avere più una casa.

Questo non è essere intelligenti. Dovete guardare le cose con chiarezza
e imparare come relazionarvi a esse. Anche quando sentite che apparenze
illusorie sono reali, dovete dire a voi stessi che non lo sono. Andateci
contro in questo modo. Insegnate a voi stessi interiormente. Quando la
mente sta sperimentando il mondo in termini di sé e dice « È vero »,
dovete essere in grado di risponderle « Non è vero. » Dovreste
galleggiare sull’acqua, non essere sommersi, inondati dal modo consueto
in cui il mondo vede le cose. L’acqua inonda i nostri cuori se
rincorriamo le cose. Abbiamo mai osservato che cosa succede? Ci sarà lì
ancora qualcuno a “badare alla casa”?

_Nibbāna paccayo hotu_. Non c’è alcun bisogno di proporsi degli
obiettivi o di desiderare qualcosa. Mirate solo al Nibbāna. Tutti i modi
di divenire e di nascere, di merito e di virtù in senso mondano, non
portano lì. Non abbiamo bisogno di desiderare molte cose, di creare
meriti e un buon kamma, sperando che siano la ragione per ottenere una
condizione migliore, mirate direttamente al Nibbāna. Volendo _sīla_,
volendo la tranquillità, finiremo nel solito vecchio posto. Non è
necessario desiderare queste cose, dovremmo solo desiderare il luogo
della cessazione.

È così. Durante tutto il nostro divenire, fin dalla nascita, siamo tutti
terribilmente ansiosi per così tante cose. Quando c’è la separazione,
quando c’è la morte, piangiamo e ci lamentiamo. Riesco a pensare solo a
quanto ciò sia assolutamente folle. Per cosa stiamo piangendo? Dove
pensate mai che la gente vada? Se sono ancora legati al divenire e alla
nascita, in realtà non stanno andando via. Quando i bambini crescono e
si trasferiscono nella grande Bangkok, pensano ancora ai loro genitori.
Non sentiranno la mancanza dei genitori di nessun altro, solo dei
propri. Quando torneranno, andranno nella casa dei loro genitori, non in
quella di qualcun altro. E quando andranno via di nuovo, penseranno
ancora alla loro casa, qui a Ubon. Sentiranno la nostalgia di qualche
altro posto? Che ne pensate?

Così, quando il respiro non c’è più e si muore, se le cause del divenire
e del nascere esistono ancora, è probabile che la coscienza cerchi di
nascere in un posto che le è familiare, non importa attraverso quante
vite si sia già passati. Penso che abbiamo solo troppa paura di tutto
questo. Perciò, per favore, non state a piangere più del dovuto. Pensate
a questo. _Kammaṃ satte vibhajati_, il kamma conduce nelle loro varie
nascite gli esseri, che non vanno poi molto lontano. Vanno vorticando
avanti e indietro attraverso il ciclo delle nascite, questo è tutto,
cambiano solo apparenza. La volta dopo compaiono con un volto
differente, ma non lo sappiamo. Solo andare e venire, andare e tornare
nella ruota del _saṃsāra_, in verità senza andare da nessuna parte.
Restano qui. Come un mango che cade dall’albero. Come il laccio che non
arriva al nido delle vespe e cade in terra, non va da nessuna parte.
Resta semplicemente qui. Perciò il Buddha disse « Nibbāna paccayo
hotu », che il vostro solo scopo sia il Nibbāna. Sforzatevi duramente
per riuscirci. Non fate la fine del mango, che cade a terra e non va da
nessuna parte.

Trasformate in questo modo il significato che date alle cose. Se lo
modificate, conoscerete una grande pace. Cambiatelo, per favore. Venite
a vedere, venite a conoscere. Queste sono davvero le cose che si
dovrebbero vedere e conoscere. Se vedete e conoscete, dove avrete mai
bisogno di andare? La moralità giungerà in essere. Il Dhamma giungerà in
essere. Non è nulla di lontano. Perciò, per favore, investigate tutto
questo. Quando trasformerete la vostra visione, comprenderete che è come
guardare le foglie che cadono dagli alberi. Quando diventano vecchie e
secche, cadono. E quando torna la stagione giusta, cominciano ad
apparire di nuovo. Qualcuno piangerebbe quando le foglie cadono, o
riderebbe quando crescono? Se lo faceste, significherebbe che siete
matti, o no? È tutto qui. Se possiamo vedere le cose in questo modo,
tutto sarà a posto. Sapremo che questo è solo l’ordine naturale delle
cose. Non importa a quante nascite siamo soggetti, sarà sempre così.
Quando si studia il Dhamma e si guadagna la chiara conoscenza, si
verifica un cambiamento di questo genere nella visione del mondo, e si
ottiene la pace e la libertà dal disorientamento a riguardo dei fenomeni
di questa vita.

L’importante è che siamo vivi adesso, nel presente. Proprio ora stiamo
sperimentando i risultati delle azioni compiute in passato. Quando gli
esseri nascono nel mondo, è la manifestazione delle azioni passate. Ogni
felicità e sofferenza nel presente sono il frutto di quello che si è
fatto in precedenza. Sono nate dal passato e vengono sperimentate nel
presente. Poi, quando generiamo ulteriori cause dietro l’influsso
dell’esperienza presente, questa diventa base del futuro, e così
l’esperienza futura diventa il risultato. Anche il movimento da una
nascita a quella successiva si verifica in questo modo. Tutto questo
dovreste comprenderlo.

Ascoltare il Dhamma dovrebbe risolvere i vostri dubbi. Dovrebbe chiarire
il vostro modo di vedere le cose e modificare il vostro modo di vivere.
Quando i dubbi sono risolti, la sofferenza può finire. Non generate più
desideri e afflizioni mentali. Allora qualsiasi cosa sperimenterete, se
è spiacevole non soffrirete, perché ne comprenderete la mutevolezza, e
se è piacevole non vi lascerete trasportare né ne sarete intossicati,
perché conoscerete come lasciar andare in modo appropriato. Conserverete
una prospettiva equilibrata, perché comprendete l’impermanenza e saprete
come risolvere le cose in coerenza con il Dhamma. Saprete che condizioni
buone e cattive sono in continuo cambiamento. Conoscendo i fenomeni
interni comprendete i fenomeni esterni. Non attaccati all’esterno, non
sarete attaccati all’interno. È del tutto uguale osservare le cose
all’interno o al di fuori di voi stessi.

In questo modo possiamo dimorare in uno stato naturale, che è di pace e
tranquillità. Se siamo criticati, restiamo impassibili. Se siamo lodati,
restiamo impassibili. Lasciare che le cose siano in questo modo, non
essere influenzati dagli altri: questa è libertà. Conoscendo i due
estremi per quel che sono, si può sperimentare il benessere. Non ci si
ferma su nessuno dei due lati. Questa è genuina felicità e pace, questo
è trascendere tutte le cose del mondo. Si trascende tutto il bene e
tutto il male. Si è al di sopra di causa ed effetto, al di là di nascita
e morte. Benché nati in questo mondo, possiamo trascendere il mondo.
Essere al di là del mondo, conoscendo il mondo: questo è il fine
dell’insegnamento del Buddha. Egli non voleva che la gente soffrisse.
Desiderava che raggiungesse la pace, conoscesse la verità delle cose e
realizzasse la saggezza. Questo è il Dhamma, conoscere la natura delle
cose. Qualsiasi cosa esista nel mondo, è natura. Non c’è bisogno di
sentirsi confusi in proposito. Dovunque vi troviate si applicano le
stesse leggi.

Il punto più importante è che, mentre siamo in vita, dovremmo addestrare
la mente a essere equilibrata nei riguardi delle cose. Dovremmo essere
in grado di condividere ricchezza e possessi. Quando è il momento,
dovremmo darne una parte a chi ne ha bisogno, come se la stessimo dando
ai nostri figli. Spartendo le cose in questo modo saremo felici. Se
riusciamo a dar via ogni nostra ricchezza, in qualsiasi momento il
nostro respiro si dovesse fermare non ci sarà attaccamento o ansia
perché è tutto finito. Il Buddha insegnò a “morire prima di morire”, a
farla finita con le cose prima che esse finiscano.

Questa fu l’intenzione del Buddha quando insegnò il Dhamma. Anche se
ascoltate gli insegnamenti per centinaia o migliaia di eoni, se non
capite questo non sarete in grado di annullare la vostra sofferenza e
non troverete la pace. Non vedrete il Dhamma. Comprendere queste cose in
accordo con l’intenzione del Buddha ed essere in grado di risolvere le
questioni è detto vedere il Dhamma. Questo modo di vedere le cose può
porre fine alla sofferenza. Può alleviare ogni bollore e tensione.
Coloro che si sforzano sinceramente e con diligenza nella pratica, che
perseverano, che si addestrano e sviluppano se stessi completamente:
queste sono le persone che raggiungeranno la pace e la cessazione.
Dovunque si trovino, non proveranno sofferenza. Giovani o anziani che
siano, saranno liberi dalla sofferenza. Quale che sia la loro situazione
o il lavoro che svolgono non soffriranno, perché la loro mente ha
raggiunto il posto in cui la sofferenza è esaurita, ove c’è pace. È
così. È una cosa naturale.

Perciò il Buddha disse che modificando le percezioni si troverà il
Dhamma. Quando la mente è in armonia con il Dhamma, il Dhamma entra nel
cuore. Allora non è più possibile distinguere la mente dal Dhamma. La
trasformazione del modo di vedere e di fare esperienza delle cose deve
essere realizzata da coloro che praticano. Tutto il Dhamma è
_paccattaṃ_,footnote:[_paccattaṃ._ Da sperimentare individualmente e
personalmente (_veditabba_) da parte dei saggi (_viññūhi_).] da
conoscere personalmente. Non può essere dato da nessuno, è impossibile.
Se lo riteniamo difficile, sarà una cosa difficile. Se lo riteniamo
facile, sarà facile. Chiunque contempli e veda quell’unico punto non ha
bisogno di conoscere molte cose. Vedendo quel solo punto, vedendo la
nascita e la morte, il sorgere e lo svanire dei fenomeni secondo natura,
conoscerà tutte le cose. È una questione di verità.

Questa è la via del Buddha. Il Buddha impartì i suoi insegnamenti
desiderando che fossero di beneficio a tutti gli esseri. Desiderò che
noi andassimo oltre la sofferenza e che ottenessimo la pace. Per
trascendere la sofferenza non dobbiamo prima morire. Non dovremmo
pensare che ci riusciremo dopo la morte, andiamo oltre la sofferenza qui
e ora, nel presente. La trascendiamo nella nostra percezione delle cose,
proprio in questa vita, attraverso la visione che sorge nelle nostre
menti. Allora seduti, siamo felici. Distesi, siamo felici. Ovunque ci
troviamo siamo felici. Non sbagliamo, non sperimentiamo cattive
conseguenze, e viviamo in una condizione di libertà. La mente è limpida,
luminosa e serena. Non vi sono più oscurità e contaminazioni. Questo
avviene per chi ha raggiunto la suprema felicità della via del Buddha.
Per favore, investigatelo voi stessi. E tutti voi, seguaci laici,
contemplatelo per ottenere comprensione e abilità. Se soffrite,
praticate per alleviare la vostra sofferenza. Se è grande, rendetela
piccola, e se è piccola, ponete fine a essa. Ognuno deve farlo da sé.
Fate allora uno sforzo e prendete in considerazione queste parole, per
favore. Che possiate prosperare e svilupparvi spiritualmente.
