= Un messaggio dalla Thailandia

____
Questo messaggio di Ajahn Chah fu inviato ai suoi discepoli
in Inghilterra mentre egli risiedeva in una filiazione monastica,
chiamata “La Grotta della Luce del Diamante”, immediatamente
prima che la sua salute peggiorasse gravemente durante
il Ritiro delle Piogge del 1981.
____

Quest’anno sono venuto fino al Wat Tham Saeng Pet per il Ritiro delle
Piogge, soprattutto per cambiare aria poiché non sono stato molto bene.
Con me ci sono alcuni monaci occidentali: Santa, Pabhakaro, Pamutto,
Michael e il _sāmaṇera_ Guy. Ci sono pure alcuni monaci thailandesi e un
piccolo gruppo di laici abili nella pratica. Si tratta di un periodo per
noi piacevole e provvidenziale. In questo momento la mia malattia si è
placata, e perciò mi sento sufficientemente bene per registrare questo
messaggio per voi.

A causa di questa malattia non posso venire in Inghilterra e, per
questo, sentire vostre notizie da alcuni sostenitori laici che stanno
qui mi ha sollevato e reso davvero felice. Quel che più mi fa piacere è
che ora Sumedho possa ordinare dei monaci.footnote:[È un riferimento
alla nomina ufficiale di Ajahn Sumedho come precettore da parte delle
autorità ecclesiastiche thailandesi.] Questo dimostra che i vostri
sforzi di impiantare il buddhismo in Inghilterra hanno avuto successo.
Mi fa anche piacere vedere i nomi dei monaci e delle monache che conosco
e che ora vivono con Sumedho a Chithurst: Anando, Viradhammo, Sucitto,
Uppanno, Kittisaro e Amaro. Anche le __mae chee__footnote:[Monaca
novizia che segue gli Otto Precetti, forma monastica tradizionale
femminile diffusa in Thailandia.] Rocana e Candasiri. Spero che siate
tutti in buona salute, che viviate insieme in armonia, che collaboriate
e che progrediate nella pratica del Dhamma.

Sia in Inghilterra sia qui in Thailandia ci sono dei sostenitori che mi
hanno aiutato a tenermi aggiornato sugli ultimi sviluppi. Da loro ho
saputo che i lavori di costruzione a Chithurstfootnote:[Si allude alla
costruzione di Cittaviveka, il primo monastero della Tradizione della
Foresta del lignaggio di Ajahn Chah fondato in Occidente.] sono stati
completati, e che ora lì si vive molto meglio. Chiedo spesso di questo,
perché ricordo che i miei sette giorni di soggiorno lì furono piuttosto
difficili! (Risata.) Ho sentito che la sala di meditazione e le altre
aree principali sono ora state portate tutte a termine. Con meno lavoro
da svolgere, ora la comunità potrà applicarsi di più alla pratica
formale. So pure che alcuni dei monaci più anziani sono stati spostati
per la fondazione di monasteri affiliati. Si tratta di una prassi
normale, ma che può condurre al predominio dei monaci più giovani nel
monastero principale. Così è in passato avvenuto al Wat Nong Pah Pong.
Ciò può indurre delle difficoltà nell’insegnamento e nell’addestramento
dei monaci, e in queste situazioni è perciò davvero importante che ci si
aiuti reciprocamente.

Ho fiducia nel fatto che Sumedho non consenta a queste cose di pesare su
di lui! Si tratta di piccole cose, del tutto normali, che non
costituiscono affatto un problema. Ci sono indubbiamente delle
responsabilità. Però, si può anche vedere le cose come se non ce ne
fossero. L’abate di un monastero può essere paragonato a un bidone per
la spazzatura: chi viene infastidito dalla spazzatura, predispone un
bidone, con la speranza che la gente ci metta dentro la spazzatura. In
realtà, quel che avviene è che la persona che predispone il bidone
finisce col diventare anche colui che la spazzatura la raccoglie. Così
stanno le cose. Lo stesso succede al Wat Nong Pah Pong. Lo stesso
succedeva ai tempi del Buddha. Nessuno butta la spazzatura nel bidone, e
così dobbiamo farlo da noi stessi, e tutto finisce per essere gettato
nel bidone dell’abate! Chi si trova in questa posizione deve vedere
lontano, essere profondo e incrollabile nel bel mezzo di ogni cosa, deve
avere costanza e perseveranza. Di tutte le qualità che sviluppiamo nella
nostra vita, la paziente sopportazione è quella più importante.

È pur vero che la realizzazione di un’opportuna dimora a Chithurst è
stata condotta a termine. La costruzione di un edificio non è
complicata, un paio d’anni ed è fatta. Quel che tuttavia non è stato
condotto a termine è il lavoro di mantenimento e di manutenzione:
ramazzare, pulire e così via sono cose che dureranno per sempre.
Costruire un monastero non è difficile, ma è difficile conservarlo. Allo
stesso modo, non è difficile ordinare i monaci, ma lo è addestrarli
pienamente alla vita monastica. Tuttavia, ciò non dovrebbe essere
considerato un problema perché è fare quel che è difficile che reca
beneficio. Fare solo quel che è facile non è molto utile. Per questa
ragione, al fine di nutrire e mantenere il seme del buddhismo che è
stato piantato a Chithurst, dovete tutti quanti impegnarvi con energia,
collaborando gli uni con gli altri.

Spero che quel che ho detto oggi possa esprimere un sentimento di calore
e di supporto. Ogni volta che incontro dei thailandesi che hanno
contatti con l’Inghilterra, chiedo se sono stati a Chithurst. Da quel
che loro mi dicono, pare che ci sia un gran interesse nei riguardi di
quella filiazione monastica. Inoltre, gli stranieri che vengono qui e
che spesso visitano il Wat Pah Nanachat, hanno pure notizie di voi in
Inghilterra. Vedo che c’è una relazione di stretta collaborazione tra il
Wat Pah Pong, il Wat Pah Nanachat e il Wat Chithurst, e questo mi rende
felice.

Questo è tutto quello che ho da dirvi, oltre al fatto che i miei
sentimenti di gentilezza amorevole sono con tutti voi. Che voi possiate
star bene ed essere felici, che possiate vivere insieme in armonia,
collaborazione e solidarietà. Che le benedizioni del Buddha, del Dhamma
e del Saṅgha possano radicarsi profondamente nel vostro cuore. Possiate
tutti voi stare bene.
