= Una sorgente di saggezza

____
Discorso offerto ai monaci riuniti dopo la recitazione
del _Pāṭimokkha_ al Wat Pah Pong durante
il Ritiro delle Piogge del 1978.
____

Tutti noi abbiamo deciso di diventare _bhikkhu_ e
__sāmaṇera__footnote:[_sāmaṇera._ Letteralmente, “piccolo _samaṇa_”,
un monaco novizio che osserva Dieci Precetti ed è candidato per
l’ammissione nell’Ordine dei _bhikkhu_.] buddhisti per trovare la pace.
Cos’è però la vera pace? La vera pace, disse il Buddha, non è molto
lontana, sta proprio dentro di noi, ma tendiamo continuamente a
trascurarla. La gente ha una sua idea sul modo in cui trovare la pace,
ma continua pur sempre a sperimentare confusione e agitazione, tende
ancora a essere insicura e a non trovare una realizzazione nella
pratica. Non ha ancora raggiunto la meta. È come se avessimo lasciato la
nostra casa per viaggiare in molti luoghi. Che si viaggi con
l’automobile o con la nave, non importa dove si vada, non abbiamo ancora
raggiunto la nostra casa. Fino a quando non siamo a casa non ci sentiamo
soddisfatti, abbiamo ancora delle cose da sbrigare. Questo avviene
perché il nostro viaggio non è ancora finito, non abbiamo ancora
raggiunto la nostra destinazione. Viaggiamo ovunque in cerca della
Liberazione.

Tutti voi _bhikkhu_ e _sāmaṇera_ qui presenti volete la pace, ognuno di
voi la vuole. Io stesso quando ero più giovane cercavo la pace
dappertutto. Ovunque andassi non ero soddisfatto. Andavo nella foresta,
andavo a far visita a vari insegnanti, ascoltavo discorsi di Dhamma, ma
non riuscivo a essere soddisfatto. Perché? Cerchiamo la pace in posti
tranquilli, perché in essi non ci sono immagini, suoni, odori e sapori,
pensando che vivere serenamente in questa maniera sia il modo per
trovare appagamento, pensiamo che lì stia la pace. Però, se in realtà
viviamo molto tranquillamente in posti nei quali non sorge nulla, in
questi posti può sorgere la saggezza? Siamo consapevoli di qualcosa?
Pensateci. Come sarebbe se i nostri occhi non vedessero? Se il naso non
sperimentasse degli odori, come sarebbe? Se il corpo non avesse alcuna
sensazione, come sarebbe? Essere così significherebbe essere come ciechi
e sordi, persone alle quali sono caduti il naso e la lingua, o diventate
insensibili per una paralisi. Che cosa ci potrebbe mai essere lì? Si ha
tuttavia la tendenza a pensare che la pace si trovi quando si va in un
posto in cui non succede nulla. Bene, io stesso ho pensato così, anch’io
ho pensato in questo modo.

Ero un giovane monaco, avevo appena iniziato a praticare, e quando
sedevo in meditazione i rumori mi disturbavano. Fra me e me pensavo:
« Che cosa posso fare per rendere la mia mente serena? » Così prendevo
un po’ di cera e me la mettevo negli orecchi per non sentire nulla.
Restava un ronzio. Pensavo che sarei stato tranquillo, e invece no,
perché in fin dei conti tutti quei pensieri e tutta quella confusione
non sorgevano dagli orecchi. Sorgevano nella mente. Quello è il posto in
cui bisogna cercare la pace. Per dirla in un altro modo,
indipendentemente da dove andiate a stare, è che non volete fare nulla
perché pensate che interferisca con la vostra pratica. Non volete
spazzare il suolo né fare altri lavori, volete solo stare tranquilli e,
in questo modo, trovare la pace. Quando l’insegnante vi chiede di dare
una mano a sbrigare delle faccende o qualsiasi incombenza quotidiana,
non aiutate mettendoci il cuore perché pensate che si tratti solo di
occupazioni esteriori.

Prendo spesso come esempio uno dei miei discepoli che desiderava davvero
“lasciar andare” e trovare la pace. Avevo insegnato il “lasciar
andare” e lui aveva capito che se avesse lasciato andare ogni cosa
avrebbe trovato la serenità. In realtà, fin dal primo giorno che era
stato qui non aveva mai voluto far nulla. Non gli importò niente neanche
quando il vento portò via mezzo tetto alla sua _kuṭī_. Disse che si
trattava solo di una cosa esteriore. Così non si preoccupò di
aggiustarlo. Quando i raggi del sole e la pioggia entravano da una
parte, lui si spostava dall’altra. Non era affar suo. Affar suo era
rendere serena la mente. Tutto il resto era una distrazione, non si
lasciava coinvolgere. È così che vedeva le cose. Un giorno, mentre
camminavo lì vicino, vidi che il tetto era crollato. « Eh? Di chi è
questa _kuṭī_? » Qualcuno mi disse di chi era, e io pensai: « Mmm.
Strano. … » Così gli parlai, gli spiegai molte cose, ad esempio i doveri
nei riguardi dei luoghi in cui dimoriamo, i _senāsana-vatta_. « Dobbiamo
avere un luogo nel quale dimorare, e dobbiamo prendercene cura.
“Lasciar andare” non è come intendi tu, non significa sottrarsi alle
responsabilità. Sono i folli a comportarsi così. La pioggia entra da una
parte e tu ti sposti dall’altra. Poi esce il sole e tu torni da quella
parte. Perché ti comporti così? Perché non ti sforzi di lasciar andare
proprio questo comportamento? » Gli parlai a lungo e, quando terminai di
parlare, mi disse: « Oh, Luang Por, a volte mi insegni l’attaccamento e
altre volte mi insegni di lasciar andare. Non riesco a capire cosa vuoi
che io faccia. Perfino quando il mio tetto crolla e io lascio andare
fino a questo punto, tu dici che non va bene. Però mi insegni a lasciar
andare! Non so più cosa vuoi da me. » Capite? La gente è così. Si può
essere stupidi fino a questo punto.

All’interno dell’occhio ci sono oggetti visivi? Se non ci fossero
oggetti visivi potrebbero i nostri occhi vedere qualcosa? Ci sarebbero
dei suoni all’interno dei nostri orecchi, se dei suoni esterni non
entrassero in contatto con essi? Se esternamente non ci fossero degli
odori, potremmo sperimentarli? Dove sono le cause? Pensate a quel che
disse il Buddha: tutti i __dhamma__footnote:[Come si è già accennato,
questo termine può avere molti significati (si veda il
<<glossary#dhamma,Glossario, Dhamma>>); in questo discorso il venerabile Ajahn Chah fa
riferimento ai fenomeni fisici e mentali.] hanno delle cause che li
fanno sorgere. Se non avessimo gli orecchi, potremmo sperimentare dei
suoni? Se non avessimo gli occhi, potremmo vedere? Occhi, orecchi, naso,
lingua, corpo e mente: queste sono le cause. Si dice che tutti i
_dhamma_ sorgono a causa di condizioni. Quando cessano è perché sono
cessate le condizioni causali. Prima che sorgano i risultati delle
condizioni causali, devono sorgere le condizioni causali stesse.

Se pensiamo che la pace stia dove non ci sono sensazioni, potrebbe
sorgere la saggezza? Potrebbero esserci lì le condizioni causali e i
loro effetti? Ci sarebbe qualcosa con cui praticare? Se ce la prendiamo
con i suoni, allora laddove i suoni esistono non possiamo essere sereni.
Pensiamo che quel posto non vada bene. Ovunque ci siano cose da vedere,
diciamo che non è un luogo tranquillo. Se è così, allora per trovare la
pace dovremmo essere persone cieche e sorde, i cui sensi sono
completamente morti. Ci ho pensato. « Mmm. È strano. La sofferenza sorge
a causa degli occhi, degli orecchi, del naso, della lingua, del corpo e
della mente. Dovremmo essere allora ciechi? Allora non vedere proprio
nulla potrebbe essere meglio. Non sorgerebbero contaminazioni, se
fossimo ciechi o sordi. È così che stanno le cose? » Ripensandoci, però,
è una cosa del tutto errata. Se fosse così, tutta la gente cieca e sorda
sarebbe illuminata. Tutti sarebbero esseri realizzati, se le
contaminazioni sorgessero al livello degli occhi e degli orecchi. Dove
sorge la causa, è lì che dobbiamo contemplare.

In realtà, tutte le basi dei sensi – gli occhi, gli orecchi, il naso, la
lingua, il corpo e la mente – possono facilitare il sorgere della
saggezza, se li conosciamo così come sono. Se non li conosciamo
veramente, dobbiamo negarli, dicendo che non vogliamo vedere immagini,
ascoltare suoni e così via, perché ci disturbano. Se eliminiamo le
condizioni causali, che cosa contempleremo? Pensateci. Ci sarebbero
ancora causa e effetto? Si tratta di un nostro modo errato di pensare.
Questa è la ragione per cui ci viene insegnato a essere contenuti. Il
contenimento è _sīla_. Dove c’è _sīla_, c’è un senso di contenimento.
Occhi, orecchi, naso, lingua, corpo e mente: questi sono il nostro
_sīla_ e questi sono il nostro _samādhi_. Riflettete sulla storia di
Sāriputta. Prima che diventasse un _bhikkhu_, vide Assaji Thera che
faceva la questua. Guardandolo, Sāriputta pensò: « Questo monaco è
alquanto singolare. Non cammina né troppo veloce né troppo lento,
indossa la sua veste con accuratezza, è contenuto nel comportamento. »
Sāriputta si sentì ispirato dal venerabile Assaji e così si avvicinò,
gli porse omaggio e gli chiese: « Scusami venerabile, chi sei? » « Sono
un _samaṇa_. » « Chi è il tuo maestro? » « Il mio maestro è il
venerabile Gotama. » « Cosa insegna il venerabile Gotama? » « Insegna
che tutte le cose sorgono a causa di condizioni. Quando cessano è perché
le condizioni causali sono cessate. » Quando Sāriputta chiese del
Dhamma, Assaji lo spiegò solo brevemente, parlò di causa e effetto. « I
_dhamma_ sorgono in ragione di cause. Prima sorgono le cause e poi gli
effetti. Per far cessare l’effetto, deve prima cessare la causa. » Fu
tutto quel che disse, ma per Sāriputta fu sufficiente.footnote:[Quella
volta Sāriputta ebbe il primo contatto con il Dhamma, e raggiunse la
condizione di _sotāpanna_, ossia di “Chi è entrato nella corrente” e
conseguì perciò il primo livello dell’Illuminazione.]

Fu una causa per il sorgere del Dhamma. Allora Sāriputta aveva occhi e
orecchi, aveva un naso, una lingua, un corpo e una mente. Tutte le sue
facoltà erano intatte. Se non avesse avuto queste facoltà, ci sarebbero
state cause sufficienti affinché in lui sorgesse la saggezza? Sarebbe
stato consapevole di qualcosa? Però, la maggior parte di noi teme un
contatto tramite le basi dei sensi. Oppure ci piace avere un contatto,
ma da esso non sviluppiamo alcuna saggezza. Indulgiamo invece
ripetutamente per mezzo degli occhi, degli orecchi, del naso, della
lingua, del corpo e della mente, deliziandoci e smarrendoci negli
oggetti dei sensi. Così stanno le cose. Queste basi dei sensi possono
trascinarci nel piacere e nell’indulgenza o possono condurci alla
conoscenza e alla saggezza. Sono sia dannose sia benefiche, dipende
dalla nostra saggezza.

Cerchiamo di capire che per noi tutto dovrebbe essere pratica, visto che
abbiamo intrapreso la vita monastica e siamo arrivati qui per praticare.
Anche le cose cattive. Dovremmo conoscerle tutte. Perché? Per essere in
grado di conoscere la Verità. Quando si parla di pratica, non ci si
riferisce solo alle cose buone e che ci piacciono. Non è così. In questo
mondo alcune cose ci piacciono, altre no. È in questo mondo che esistono
tutte queste cose, da nessun’altra parte. Di solito vogliamo tutto quel
che ci piace, anche dai nostri compagni monaci e novizi. Quando un
monaco o un novizio non ci piacciono, non vogliamo la loro compagnia,
vogliamo stare assieme solo a quelli che ci piacciono. Capite? Si
sceglie sulla base delle nostre preferenze. Tutto quello che non ci
piace non vogliamo vederlo, né saperne nulla. In realtà il Buddha voleva
che facessimo esperienza di queste cose.
_Lokavidū_:footnote:[_lokavidū._ “Conoscitore del mondo”, un epiteto
del Buddha.] guardate questo mondo e conoscetelo con chiarezza. Se non
conosciamo la Verità del mondo con chiarezza, allora non possiamo andare
da nessuna parte. Vivendo nel mondo, dobbiamo comprendere il mondo. Gli
Esseri Nobili del passato, compreso il Buddha, vivevano tutti con queste
cose, vivevano in questo mondo, tra gli esseri illusi. Realizzarono la
Verità proprio in questo mondo, non da qualche altra parte. Non è che
scapparono in qualche altro mondo per trovare la Verità. Avevano
saggezza. Contenevano i loro sensi, ma la pratica consiste nel guardare
all’interno di queste cose e conoscerle per quello che sono.

È per questo che il Buddha ci insegnò a conoscere le basi dei sensi, i
nostri punti di contatto. Gli occhi contattano le forme e le mandano
“dentro” per farle diventare immagini. Gli orecchi entrano in contatto
con i suoni, il naso entra in contatto con gli odori, la lingua entra in
contatto con i sapori, il corpo entra in contatto con le sensazioni
tattili, e così sorge la consapevolezza. Dove sorge la consapevolezza, è
lì che dovremmo guardare per vedere le cose così come sono. Se non
conosciamo quelle cose per quello che sono veramente, o ce ne
innamoriamo o le odiamo. Dove queste sensazioni sorgono, è lì che
possiamo diventare Illuminati, è lì che può sorgere la saggezza. A volte
però non vogliamo che le cose vadano così. Il Buddha ci insegnò il
contenimento, ma contenimento non significa che non vediamo nulla, che
non sentiamo nulla, che non percepiamo alcun odore, sapore, sensazione
tattile né che non abbiamo alcun pensiero. Non è così. Se i praticanti
non lo capiscono, allora appena vedono o sentono qualcosa, si ripiegano
su se stessi e scappano via. Non entrano in relazione con le cose.
Scappano via pensando che, se fanno così, quelle cose alla fine
perderanno il potere che hanno su di loro, che alla fine le
trascenderanno. Non ci riusciranno. In questo modo non trascenderanno
nulla. Se scappano via senza conoscere la Verità di esse, dopo qualche
tempo dovranno avere a che fare con quella stessa roba, che di nuovo
salterà fuori.

Ad esempio, quei praticanti sempre insoddisfatti, sia che si trovino nei
monasteri sia che dimorino nella foresta o sulle montagne. Si dedicano
alla pratica del “pellegrinaggio _dhutaṅga_” e guardano questo, quello
e quell’altro ancora, pensando che così si sentiranno appagati. Vanno, e
poi tornano. Non hanno visto nulla. Cercano di raggiungere la cima di
una montagna. « Ah! Questo posto! Ora sì che sto bene. » Si sentono in
pace per qualche giorno e poi si stancano. « Oh, bene, ora si va giù,
verso il mare. » « Ah! Che bel posto fresco! Mi farà bene. » Dopo un po’
si stancano pure del mare. Stanchi delle foreste, stanchi delle
montagne, stanchi del mare, stanchi di tutto. Questo non significa
essere stanchi delle cose in modo giusto,footnote:[Ossia _nibbidā_, il
disinteresse nei riguardi dei richiami del mondo sensoriale.] questa non
è Retta Visione. Si tratta solo di noia, di un tipo di visione errata.
Questo modo di vedere non è in accordo con il modo in cui le cose
veramente sono. Quando tornano in monastero dicono: « E ora che cosa
faccio? Sono stato dappertutto e sono tornato senza aver concluso
nulla. » Perciò gettano via la ciotola e lasciano l’abito monastico.
Perché lasciano l’abito monastico? Perché non hanno aderito alla
pratica, non hanno visto nulla. Sono andati a nord e non hanno visto
nulla. Sono andati al mare, sono andati su per le montagne e nella
foresta, e tuttavia non hanno visto nulla. Così è tutto finito:
“muoiono”. È così che vanno le cose. È perché scappano continuamente
via dalle cose. E la saggezza non sorge.

Facciamo un altro esempio. Supponiamo che un monaco decida di stare con
le cose, di non scappare via. Si prende cura di se stesso. Conosce se
stesso e conosce pure coloro che vengono a stare con lui. Ha sempre a
che fare con i problemi. Un abate, ad esempio. Se si è abati di un
monastero, ci sono sempre problemi di cui occuparsi, c’è un continuo
fluire di cose che richiedono attenzione. Perché è così? Perché la gente
fa domande in continuazione. Le domande non finiscono mai, e si è sempre
sul chi va là. Si devono risolvere sempre problemi, sia i propri sia
quelli degli altri. Bisogna essere sempre vigili. Ti sei appena
appisolato che ti svegliano con un altro problema. Ciò induce a
contemplare e a comprendere le cose. Si diventa abili: abili nei
riguardi di se stessi e abili nei riguardi degli altri. Abili in molti,
in moltissimi modi. Questa è un’abilità che sorge dal contatto, dal
confronto e dalla relazione con le cose, non scappando da esse. Noi non
scappiamo via fisicamente, “scappiamo via” con la mente, usando la
nostra saggezza. È proprio qui che comprendiamo con saggezza, non
scappiamo da nulla. Questa è una sorgente di saggezza. Si deve lavorare,
ci si deve relazionare con altre cose. Vivendo ad esempio in un
monastero grande come questo, per prenderci cura delle cose dobbiamo
tutti darci una mano. Guardando tutto questo, da un certo punto di vista
si potrebbe dire che sono solo contaminazioni. Quando si vive con molti
monaci e con molti novizi, con molti laici che vanno e vengono, possono
sorgere molte contaminazioni. Certo, lo ammetto, ma è che dobbiamo
vivere in questo modo per sviluppare la saggezza e abbandonare la
stupidità. In che direzione stiamo andando? Stiamo vivendo per vincere
la nostra stupidità oppure per aumentarla?

Dobbiamo contemplare. Tutte le volte che i nostri occhi, i nostri
orecchi, il nostro naso, la nostra lingua, il nostro corpo e la nostra
mente entrano in contatto con qualcosa, dobbiamo essere contenuti e
circospetti. Quando sorge la sofferenza dovremmo chiederci: « Chi è che
sta soffrendo? Perché sorge questa sofferenza? » L’abate di un monastero
deve sorvegliare molti discepoli. Questo può significare sofferenza.
Quando la sofferenza sorge, dobbiamo conoscerla. Conoscere la
sofferenza. Se abbiamo paura della sofferenza e non la affrontiamo,
quand’è che la combatteremo? Se la sofferenza sorge e noi non la
conosciamo, com’è che la affronteremo? Tutto questo è di estrema
importanza: dobbiamo conoscerla la sofferenza. Salvarsi dalla sofferenza
significa conoscere la via che conduce fuori dalla sofferenza, non
significa scappare via dal posto nel quale la sofferenza sorge, quale
che esso sia. Facendo così portate solo la vostra sofferenza con voi.
Quando la sofferenza sorgerà di nuovo da qualche altra parte, dovrete
fuggire di nuovo. Questo non è trascendere la sofferenza, non è
conoscere la sofferenza. Se volete comprendere la sofferenza, dovete
guardare nella situazione che vi trovate a vivere. Gli insegnamenti
dicono che ovunque un problema sorga, è proprio lì che deve essere
risolto. Proprio lì dov’è la sofferenza, sorgerà la non sofferenza, la
sofferenza cesserà nello stesso luogo in cui sorge. Se la sofferenza
sorge, è proprio lì che dovete contemplare, non dovete scappare via. È
proprio lì che dovreste risolvere il problema. Chi per la paura scappa
dalla sofferenza è il più folle di tutti. Aumenterà solo all’infinito la
sua stupidità.

Dobbiamo capire: la sofferenza non è nient’altro che la Prima Nobile
Verità, vero? Avete intenzione di considerarla come qualcosa di male?
_Dukkha sacca_, _samudaya sacca_, _nirodha sacca_, _magga
sacca_.footnote:[Sono le Quattro Nobili Verità (_ariya-saccāni_) che
costituiscono il primo e centrale insegnamento del Buddha a riguardo
della sofferenza (_dukkha_), della sua origine (_samudaya_), della sua
cessazione (_nirodha_) e del Sentiero (_magga_) che conduce a tale
cessazione (_dukkha-nirodha-gāminī-paṭipadā_). La completa comprensione
delle Quattro Nobili Verità equivale alla fruizione del Nibbāna.]
Scappare via da queste cose significa non praticare in accordo con il
vero Dhamma. Quando vedrete mai la Verità della sofferenza? Se
continuiamo a scappare dalla sofferenza, non la conosceremo mai. La
sofferenza la dobbiamo riconoscere: se non la si osserva, quando la
riconosceremo? Quando non siete contenti qui, scappate di là, quando la
scontentezza sorge là, scappate di nuovo. Sarete sempre di corsa. Se è
così che praticate, gareggerete a correre con il demonio per tutto il
paese. Il Buddha ci insegnò a “scappare” mediante la saggezza.

Supponete ad esempio d’aver calpestato una spina, o che vi si sia
conficcata una scheggia in un piede. Quando camminate, a volte fa male,
altre volte no. Quando vi imbattete in un sasso o in un pezzo di legno,
il piede vi fa male davvero. Se però ciò non avviene, una scrollatina di
spalle e si continua a camminare ancora un po’. Alla fine però vi
imbattete in qualche altra cosa e ci camminate sopra, e il dolore si
ripresenta di nuovo. Vi succede molte volte. Qual è la causa di quel
dolore? La causa è quella scheggia, quella spina conficcata nel piede.
Il dolore è sempre pronto a manifestarsi. Tutte le volte che sorge il
dolore magari date un’occhiata e provate a sentire con la mano se c’è
qualcosa ma, siccome non vedete la spina, lasciate perdere. Dopo un po’
vi fa ancora male, e così date un’altra occhiata. Quando la sofferenza
sorge, dovete notarla, non scrollarvela di dosso. Tutte le volte che
sorge il dolore, pensate: « Mmm … quella spina è ancora lì. » Ogni volta
che il dolore sorge, sorge anche il pensiero che quella spina dovete
toglierla. Se non la togliete, in seguito lì sorgerà di nuovo altro
dolore. Il dolore continua a ripresentarsi, fino a quando il desiderio
di togliere quella spina è sempre con voi. Infine giunge il momento in
cui una volta per tutte prendete la decisione di togliervi quella spina
dal piede perché fa male!

Così devono essere i nostri sforzi con la pratica. Tutte le volte che fa
male, tutte le volte che c’è un attrito, dobbiamo investigare.
Affrontare il problema, a testa alta. Toglietevi quella spina dal piede,
tiratela fuori e basta. Tutte le volte che la vostra mente resta
bloccata, dovete prenderne nota. Quando guarderete proprio dentro quel
punto, lo conoscerete, lo vedrete e lo sperimenterete per quello che è.
La nostra pratica deve essere incrollabile e persistente. Questo si
chiama _viriyārambha_: impegnarsi con uno sforzo costante. Ad esempio,
tutte le volte che nel vostro piede sorge una sensazione spiacevole,
dovete ricordare a voi stessi che quella spina deve essere tolta, e non
rinunciare al vostro proposito. Allo stesso modo, quando nel nostro
cuore sorge la sofferenza, dobbiamo avere l’incrollabile proposito di
cercare di sradicare le contaminazioni, di rinunciare a esse. Questo
proposito è sempre lì, incessantemente. Infine le contaminazioni ci
capiteranno fra le mani e potremo farle fuori.

Per quanto concerne la felicità e la sofferenza, che cosa dobbiamo fare?
Se non avessimo queste cose, che cosa potremmo mai usare per far sorgere
in fretta la saggezza? Se non ci sarà alcuna causa, come potrà sorgere
l’effetto? Tutti i _dhamma_ sorgono in ragione di cause. Quando
l’effetto cessa, è perché è cessata la causa. Le cose stanno così, ma la
maggior parte di noi non lo capisce veramente. La gente vuole solo
fuggire dalla sofferenza. Questo genere di conoscenza non colpisce il
bersaglio. In realtà abbiamo necessità di conoscere il mondo nel quale
viviamo, proprio questo mondo, non c’è bisogno di scappare da
nessun’altra parte. Dovreste avere questo atteggiamento: restare va
bene, e anche andare va bene. Pensateci accuratamente.

Dove stanno la felicità e la sofferenza? Se non ci aggrappiamo, se non
ci attacchiamo a niente, se non ci fissiamo, come se lì non ci fosse
nulla, la sofferenza non sorge. La sofferenza sorge dall’esistenza
(_bhava_). Se c’è esistenza, allora c’è nascita. _Upādāna_:
l’attaccamento, l’aggrapparsi. Questo è il pre-requisito che crea la
sofferenza. Ovunque sorga la sofferenza, guardateci dentro. Non guardate
lontano, guardate direttamente nel momento presente. Guardate la vostra
mente e il vostro corpo. Quando sorge la sofferenza, chiedetevi perché
lì c’è la sofferenza. Guardate proprio ora. Quando sorge la felicità,
qual è la causa di quella felicità? Guardate proprio lì. Tutte le volte
che queste cose sorgono, state attenti. Sia la felicità sia la
sofferenza sorgono dall’attaccamento. In passato i praticanti di Dhamma
osservavano la loro mente in questo modo. C’è solo il sorgere e il
cessare. Non c’è alcuna entità nella quale dimorare. Contemplavano da
tutti i punti di vista, e videro che non c’è poi molto in questa mente,
videro che non c’è nulla di stabile. C’è solo sorgere e cessare, cessare
e sorgere, non c’è nulla che sia fatto di una sostanza durevole. In
meditazione, mentre camminavano o sedevano, videro le cose in questo
modo. Tutte le volte che guardavano là, c’era solo sofferenza, questo è
tutto. È proprio come una grande palla di ferro che sia appena stata
arroventata in una fornace. È rovente dappertutto. La toccate sopra ed è
rovente, la toccate di lato ed è rovente, è rovente dappertutto. Non è
fredda da nessuna parte.

Se non prendiamo in considerazione queste cose, non le conosceremo
affatto. Dobbiamo vederle con chiarezza. Non “nascete” in queste cose,
non cadete nella nascita. Dovete conoscere il modo in cui funziona la
nascita. Non sorgeranno più pensieri come questo: « Oh, quella persona
non posso sopportarla proprio, tutto quel che fa è sbagliato. » Oppure:
« Mi piace davvero questo o quello. » Queste cose non sorgeranno.
Resteranno soltanto i convenzionali criteri mondani a proposito di quel
che piace o che non piace, ma le parole sono una cosa, la mente è
un’altra. Sono cose separate. Dobbiamo usare le convenzioni del mondo
per comunicare gli uni con gli altri, ma interiormente dobbiamo essere
vuoti. La mente è al di là di queste cose. Dobbiamo condurre la mente
verso la trascendenza in questo modo. Così dimoravano gli Esseri Nobili.
Tutti noi dobbiamo mirare a questo, e praticare di conseguenza. Non
fatevi intrappolare dai dubbi.

Prima d’iniziare a praticare, mi dicevo: « La religione buddhista è qui,
a disposizione di tutti, e allora perché sono solo alcuni a praticare,
mentre altri non lo fanno? Oppure praticano solo per un po’ e dopo
rinunciano a farlo. E ancora, ammesso che non rinuncino, tuttavia non ce
la mettono tutta quando praticano. Perché succede questo? » Presi una
decisione: « Bene, in questa vita rinuncerò al mio corpo e alla mia
mente e cercherò di seguire gli insegnamenti del Buddha fin nei minimi
dettagli. Raggiungerò la conoscenza proprio in questa vita perché se non
lo farò, continuerò a sprofondare nella sofferenza. Lascerò andare ogni
altra cosa e mi sforzerò con determinazione, non importa quante saranno
le difficoltà e le sofferenze che dovrò affrontare: persevererò. Se non
lo faccio continuerò solo a dubitare. » È pensando in questo modo che mi
sono messo a praticare. Pensai che lo avrei fatto, che non mi importava
quanta felicità, quanta sofferenza o quante difficoltà avrei dovuto
sopportare. Vidi tutta la mia vita come se durasse solo un giorno e una
notte. Rinunciai a essa. « Seguirò l’insegnamento del Buddha, seguirò il
Dhamma per capire: perché questo mondo fatto di illusioni è così
infelice? » Volevo conoscere, volevo conoscere a fondo l’Insegnamento, e
così mi dedicai alla pratica del Dhamma.

Noi monaci a quanto della vita mondana dovremmo rinunciare? Se siamo
diventati monaci per bene allora significa che rinunciamo a tutto, che
non c’è nulla a cui non rinunciamo. Ci liberiamo di tutte le cose
mondane per le quali la gente prova piacere: immagini, suoni, odori,
sapori e sensazioni, gettiamo tutto via. Però li sperimentiamo. Per
questo i praticanti del Dhamma devono accontentarsi di poco ed essere
distaccati. Che si tratti di parlare, di mangiare o di qualsiasi altra
cosa, dobbiamo sentirci soddisfatti facilmente: mangiare con semplicità,
dormire con semplicità, vivere con semplicità. Proprio come si dice di
solito: una “persona semplice” s’accontenta di poco. Più praticate più
sarete in grado di trarre soddisfazione dalla vostra pratica. Vedrete
dentro il vostro cuore. Il Dhamma è _paccattaṃ_, lo dovete conoscere da
voi stessi. Conoscerlo da voi stessi significa che dovete praticare voi
stessi. Nel vostro cammino potete dipendere dal vostro insegnante solo
per il cinquanta per cento. Anche l’insegnamento che vi ho offerto oggi
è di per sé completamente inutile, anche se vale la pena di ascoltarlo.
Se però vi capitasse di credere a questo insegnamento solo perché sono
stato io a parlarvi, non lo usereste in modo appropriato. Qualora
crediate ciecamente, sareste completamente folli. Ascoltare
l’insegnamento, vederne i benefici, metterlo in pratica voi stessi,
guardare dentro voi stessi, farlo da soli: tutto questo è molto più
utile. Conoscerete allora da voi stessi il sapore del Dhamma.

Il motivo per cui il Buddha non parlò dettagliatamente dei frutti della
pratica è perché si tratta di qualcosa che non si può esprimere con le
parole. Sarebbe come cercare di descrivere i colori a uno che è cieco
fin dalla nascita. Ad esempio: « Oh, il bianco è così. » Oppure: « Così
è il giallo acceso. » Non è possibile descrivergli a parole quei colori.
Potreste provarci, ma non servirebbe a molto. Il Buddha ricondusse le
cose a ogni singolo individuo: vedi chiaramente da te stesso. Se vedrete
chiaramente da voi stessi, avrete una chiara prova dentro di voi. In
piedi, camminando, seduti o distesi sarete liberi dal dubbio. Mettiamo
che qualcuno vi dica: « Il tuo modo di praticare non è corretto, è del
tutto sbagliato. » Rimarreste comunque impassibili, perché ne avete la
prova. Un praticante del Dhamma deve essere così ovunque vada. Gli altri
non possono dirvelo, dovete conoscere da voi stessi.
__Sammā-diṭṭhi__footnote:[_sammā-diṭṭhi._ La Retta Visione, il primo
fattore del Nobile Ottuplice Sentiero.] deve essere lì con voi. È così
che la pratica deve essere per ognuno di noi. È raro che si pratichi
realmente in questo modo anche per un solo mese durante cinque o dieci
Ritiri delle Piogge.

I nostri organi dei sensi devono essere costantemente in funzione.
Conoscere la soddisfazione e l’insoddisfazione. Conoscere l’apparenza e
conoscere la trascendenza. L’apparenza e la trascendenza devono essere
comprese simultaneamente. Bene e male devono essere visti come
coesistenti: sorgono assieme. Questo è il frutto della pratica del
Dhamma. Qualsiasi cosa possa essere utile a voi stessi e agli altri,
ogni pratica che sia di beneficio a voi stessi e agli altri, tutto ciò
si chiama “seguire il Buddha”. Ne ho parlato spesso. La gente pare
voler trascurare le cose che dovrebbero essere fatte. Ad esempio il
lavoro in monastero, i punti fondamentali della pratica, e così via. Ho
parlato spesso di queste cose, però la gente non sembra averle a cuore.
Alcuni non sanno, altri sono pigri e non vogliono essere disturbati,
altri ancora sono dispersivi e confusi. Si tratta di cause che fanno
sorgere la saggezza. Se andassimo in posti in cui nessuna di queste cose
sorge, cosa potremmo capire? Prendiamo ad esempio il cibo. Se il cibo
non avesse alcun sapore, potrebbe essere delizioso? Se uno fosse sordo,
potrebbe sentire? Se non percepiste nulla, avreste qualcosa da
contemplare? Se non ci fossero problemi, ci sarebbe qualcosa da
risolvere? Pensate alla pratica in questo modo.

Una volta sono andato a vivere nel nord della Thailandia. Allora vivevo
con molti monaci, tutti più vecchi di me, ma di recente ordinazione, con
solo due o tre Ritiri delle Piogge alle spalle. Io ne avevo dieci.
Stando con quei monaci più anziani d’età decisi di svolgere vari
compiti: occuparmi delle loro ciotole, lavare le loro vesti, svuotare le
loro sputacchiere, e così via. Non pensavo di farlo per qualcuno in
particolare, semplicemente sostenevo la mia pratica. Se gli altri non
facevano questi lavori, li facevo io. La consideravo una buona
opportunità per ottenere meriti. Mi faceva sentire bene, ero
soddisfatto. Nei giorni di __uposatha__footnote:[_uposatha._ Giorno di
osservanza lunare, corrispondente alle fasi lunari, in corrispondenza
delle quali i laici buddhisti si riuniscono per ascoltare il Dhamma e
per osservare gli Otto Precetti.] sapevo quello che c’era da fare.
Andavo a pulire la sala per l’_uposatha_ e preparavo l’acqua per lavarsi
e per bere. Gli altri non sapevano che cosa dovessero fare, guardavano
solo. Non li criticavo, perché non sapevano. Facevo tutto da me, e dopo
averlo fatto mi sentivo contento di me stesso, mi sentivo ispirato e
avevo molta energia per la pratica. Ogni volta che potevo fare qualcosa
in monastero lo facevo. Sia che la mia _kuṭī_ o che quella degli altri
fossero sporche, pulivo. Non lo facevo per qualcuno in particolare, e
nemmeno per far colpo sugli altri, era solo per mantenere un buon
livello di pratica. Pulire una _kuṭī_ o un posto in cui si vive è come
spazzar via immondizia dalla mente.

È una cosa che tutti voi dovreste tenere ben presente. Non dovete
preoccuparvi dell’armonia, ci sarà automaticamente. Vivere insieme con
Dhamma, con pace e contenimento. Addestrate la mente in questo modo e
non sorgeranno problemi. Se c’è del lavoro pesante da fare, se ognuno
aiuta è subito fatto, tutto si fa con facilità. È questo il modo
migliore. Ne ho viste di tutti i colori, ma per me sono state
opportunità di crescita. Ad esempio, quando si vive in un grande
monastero i monaci e i novizi devono mettersi d’accordo sul giorno in
cui lavare l’abito. Io mettevo a bollire il legno dell’albero del
pane,footnote:[Quando il durame dell’albero del pane viene bollito ne
deriva un liquido colorato che i monaci della Tradizione della Foresta
usano sia per tingere che per lavare il loro abito.] e c’erano dei
monaci che aspettavano sempre che lo facesse qualcun altro, e poi
arrivavano e si mettevano a lavare l’abito, lo riportavano nella loro
_kuṭī_, lo stendevano fuori ad asciugare e si mettevano a fare un
pisolino. Né avevano acceso il fuoco, né s’erano sentiti dopo in dovere
di pulire e risistemare le cose. Pensavano di aver fatto una cosa buona,
di essere stati furbi. È il massimo della stupidità. Questa gente fa
solo crescere la propria stupidità perché non fa nulla, lascia tutto il
lavoro agli altri. Aspettano fino a quando le cose sono tutte pronte e
poi arrivano e le usano, per loro è facile. Si limitano ad alimentare la
loro follia. Questa maniera di comportarsi non li aiuta assolutamente.
Alcuni pensano in questo modo folle. Trascurano i loro doveri e pensano
che ciò significhi essere furbi, ma in realtà è pura follia. Con questo
atteggiamento non si va lontano.

Che si parli, che si mangi, qualsiasi cosa si faccia, riflettete perciò
su voi stessi. Potreste voler vivere in modo agiato, mangiare e dormire
bene, e così via, ma non potete. Che cosa siete venuti a fare qui? Se
pensiamo regolarmente a questo saremo accorti, non dimenticheremo,
saremo costantemente vigili. Questa vigilanza vi consentirà di sostenere
il vostro impegno in ogni postura. Se non vi impegnate, le cose vanno in
un altro modo. Se state seduti lo fate come se foste in città, e se
camminate lo fate come se foste in città. Vorrete solo andarvene in giro
a perdere tempo in città con i laici. Se non ci si sforza nella pratica,
la mente tenderà ad andare in quella direzione. Non vi opponete e non
resistete alla vostra mente, le consentite solo di essere trasportata
dal vento dei vostri stati mentali. Questo si chiama seguire i propri
umori. Come per un bambino: se indulgiamo a tutto quel che vuole, sarà
un buon bambino? È una cosa buona se i genitori indulgono a tutti i
desideri del figlio? Anche se all’inizio sono accondiscendenti, di tanto
in tanto quando inizia a parlare gli danno uno scapaccione perché temono
che diventi uno sciocco. Così deve essere l’addestramento della nostra
mente. Dovete conoscere voi stessi e sapere come addestrare voi stessi.
Se non sapete come addestrare la vostra mente e aspettate che qualcun
altro la addestri per voi, finirete per avere problemi.

Non pensate che qui non si riesca a praticare. La pratica non ha
confini. Che stiate in piedi o che camminiate, seduti o distesi, potete
sempre praticare. Potete realizzare il Dhamma anche mentre spazzate il
suolo del monastero o quando vedete un raggio di sole. Dovete però avere
con voi _sati_. Perché? Perché se meditate con ardore potete realizzare
completamente il Dhamma in ogni momento e in qualsiasi luogo. Non siate
distratti. Siate attenti, vigili. Mentre camminate per la questua sorge
ogni genere di sensazioni, ed è tutto Dhamma di ottima qualità. Quando
tornate in monastero e mangiate il vostro cibo, c’è per voi una gran
quantità di Dhamma dentro il quale guardare. Se vi impegnate con
costanza, tutte queste cose diventeranno oggetti di contemplazione. Ci
sarà saggezza, vedrete il Dhamma. Questo si chiama _dhammavicaya_,
investigazione del Dhamma. È uno dei fattori per
l’Illuminazione.footnote:[Per i sette fattori dell’Illuminazione o del
Risveglio, si veda il <<glossary#bojjhanga,Glossario, bojjhaṅga>>.]
Se c’è _sati_, rammemorazione, l’effetto sarà il
_dhammavicaya_. Questi sono fattori per l’Illuminazione. Se abbiamo
rammemorazione, non la prenderemo alla leggera, ci sarà pure indagine
nel Dhamma. Queste cose diventano fattori per la realizzazione del
Dhamma.

Se raggiungiamo questo livello, per la nostra pratica non ci sarà né
giorno né notte, continuerà indipendentemente dall’orario. Nulla
macchierà la pratica, o se ci sarà qualcosa lo si saprà immediatamente.
Consentite al _dhammavicaya_ di essere sempre nella vostra mente,
guardate nel Dhamma. Quando la vostra pratica “entrerà nella
Corrente”, la mente tenderà a essere così. Non andrà alla ricerca di
altre cose. « Penso che andrò a fare una gita in quel posto, oppure in
quell’altro. » « In quella regione ci dovrebbe essere qualcosa di
interessante. » Questa è la via del mondo. E poco tempo dopo la pratica
muore. Decidetevi. Non svilupperete la saggezza solo stando seduti a
occhi chiusi. Occhi, orecchi, naso, lingua, corpo e mente sono
costantemente con noi: perciò siate costantemente vigili. Studiate
costantemente. Vedere gli alberi o gli animali può essere un’opportunità
di studio. Portate tutto verso l’interno. Vedete con chiarezza dentro il
vostro cuore. Se qualche sensazione ha un impatto sul vostro cuore,
testimoniatelo con chiarezza a voi stessi, non limitatevi a trascurarla.

Un paragone semplice: cuocere mattoni. Avete mai visto una fornace per
cuocere i mattoni? Si accende il fuoco a mezzo metro dall’imboccatura e
tutto il fumo è convogliato nella fornace. Se pensate a questa immagine
potete comprendere con maggior chiarezza la pratica. Affinché una
fornace per cuocere i mattoni funzioni bene, il fuoco deve essere acceso
in modo che tutto il fumo sia convogliato all’interno di essa, senza
dispersioni. Tutto il calore va nella fornace, e il lavoro procede
velocemente. Noi praticanti del Dhamma dovremmo sperimentare le cose in
questo modo. Tutte le nostre sensazioni dovrebbero essere convogliate
verso l’interno e trasformate in Retta Visione. Le immagini che vediamo,
i suoni che udiamo, gli odori e i sapori che sentiamo, e così via, la
mente li dovrebbe convogliare tutti verso l’interno per convertirli in
Retta Visione. Quelle sensazioni diventano esperienze che fanno sorgere
la saggezza.
